(()=>{
  if(window.__agentieActivityProjectPolish)return;window.__agentieActivityProjectPolish=true;
  const style=document.createElement('style');style.textContent=`
    #persistentAgentList .agent-row{position:relative;transition:transform .15s,background .15s}.agent-activity-dot{position:absolute;left:31px;top:29px;width:9px;height:9px;border-radius:50%;border:2px solid var(--panel);box-sizing:border-box;z-index:3}.agent-activity-dot.working{background:#22c55e}.agent-activity-dot.queued{background:#f59e0b}.agent-activity-dot.done{background:#3b82f6}.agent-activity-dot.failed{background:#ef4444}.agent-activity-dot.idle{background:#9ca3af;opacity:.5}.agent-row[data-activity="working"] .agent-copy small{color:#22c55e}.agent-row[data-activity="queued"] .agent-copy small{color:#d97706}.agent-row[data-activity="done"] .agent-copy small{color:#3b82f6}.agent-row[data-activity="failed"] .agent-copy small{color:#ef4444}
    .scoped-project-card{width:min(610px,90vw)}.scoped-project-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.scoped-project-title{font-size:15px;font-weight:750}.scoped-project-status{font-size:9px;padding:3px 7px;border-radius:999px;background:var(--soft);text-transform:capitalize}.scoped-project-task{margin-top:12px;padding:10px 11px;border-radius:10px;background:var(--soft)}.scoped-project-task small{display:block;color:var(--muted);font-size:9px;text-transform:uppercase;letter-spacing:.06em;margin-bottom:4px}.scoped-project-task strong{display:block;font-size:12px;line-height:1.45}.scoped-project-meta{font-size:10px;color:var(--muted);margin-top:7px}.scoped-project-section{margin-top:12px;padding-top:10px;border-top:1px solid var(--border)}.scoped-project-section-title{font-size:9px;color:var(--muted);text-transform:uppercase;letter-spacing:.06em;margin-bottom:6px}.scoped-project-section-body{font-size:11px;line-height:1.5;white-space:pre-wrap}.scoped-project-summary{padding:8px 9px;border-radius:9px;background:var(--soft)}.already-deleted-card{width:min(430px,90vw)}.already-deleted-mark{font-size:12px;line-height:1.5;margin-top:8px}.already-deleted-mark strong{color:var(--muted)}
  `;document.head.appendChild(style);
  const messages=document.getElementById('messages'),chat=document.querySelector('.chat-shell'),input=document.getElementById('messageInput');
  const scrollLatest=(smooth=true)=>{if(!chat)return;requestAnimationFrame(()=>{chat.scrollTo({top:chat.scrollHeight,behavior:smooth?'smooth':'auto'})})};
  if(messages)new MutationObserver(()=>scrollLatest(true)).observe(messages,{childList:true,subtree:true});
  input?.addEventListener('input',()=>scrollLatest(false));window.addEventListener('resize',()=>scrollLatest(false));setTimeout(()=>scrollLatest(false),250);

  const activityRank={working:4,queued:3,failed:2,done:1,idle:0};
  function recent(job,ms=60000){const t=Date.parse(job?.finished_at||job?.updated_at||'');return Number.isFinite(t)&&Date.now()-t<ms}
  function activityFromJobs(jobs){const map=new Map();for(const job of jobs||[]){for(const h of job.handoffs||[]){const name=String(h.agent||'').trim();if(!name)continue;let state='idle';if(h.status==='working')state='working';else if(h.status==='queued')state='queued';else if(h.status==='failed'&&recent(job))state='failed';else if(h.status==='completed'&&recent(job))state='done';const prev=map.get(name);if(!prev||activityRank[state]>activityRank[prev.state])map.set(name,{state,task:job.task||'',jobId:job.id,status:h.status})}}return map}
  function applyActivities(map){const list=document.getElementById('persistentAgentList');if(!list)return;const rows=[...list.querySelectorAll('.agent-row')];rows.forEach((row,index)=>{row.dataset.originalOrder=row.dataset.originalOrder||String(index);const name=row.querySelector('.agent-copy strong')?.textContent?.trim()||'';const info=map.get(name)||{state:'idle',task:'',status:'idle'};row.dataset.activity=info.state;row.dataset.activityRank=String(activityRank[info.state]||0);let dot=row.querySelector('.agent-activity-dot');if(!dot){dot=document.createElement('span');dot.className='agent-activity-dot';row.appendChild(dot)}dot.className=`agent-activity-dot ${info.state}`;dot.title=info.state==='working'?`Working · ${info.task}`:info.state==='queued'?`Queued · ${info.task}`:info.state==='done'?`Done · ${info.task}`:info.state==='failed'?`Failed · ${info.task}`:'Idle';const sub=row.querySelector('.agent-copy small');if(sub){const role=(window.__agentieAgents||[]).find(a=>a.name===name)?.role||sub.dataset.baseRole||sub.textContent;sub.dataset.baseRole=role;sub.textContent=info.state==='idle'?role:`${role} · ${info.state==='done'?'done':info.state}`}});rows.sort((a,b)=>Number(b.dataset.activityRank||0)-Number(a.dataset.activityRank||0)||Number(a.dataset.originalOrder||0)-Number(b.dataset.originalOrder||0)).forEach(row=>list.appendChild(row))}
  async function refreshActivities(){try{const r=await fetch('/agent/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Show team jobs',agent_type:'general',session_id:'ui:agent-activity'})});const d=await r.json();if(!r.ok)return;const jobs=d.card?.type==='team_jobs'?(d.card.items||[]):[];applyActivities(activityFromJobs(jobs))}catch(_){}}
  setInterval(refreshActivities,1600);setTimeout(refreshActivities,500);
  const agentList=document.getElementById('persistentAgentList');if(agentList)new MutationObserver(()=>setTimeout(refreshActivities,40)).observe(agentList,{childList:true});

  function extractVisibleContext(raw){const text=String(raw||'').replace(/\r/g,'');if(!text)return'';const keep=[];const patterns=[['Goal',/GOAL:\s*([\s\S]*?)(?=\n\n[A-Z][A-Z _—-]+:|\n\nACTIVATED SKILL|$)/],['Relevant decisions',/DECISIONS:\s*([\s\S]*?)(?=\n\n[A-Z][A-Z _—-]+:|$)/],['Relevant project context',/RELEVANT PROJECT KNOWLEDGE:\s*([\s\S]*?)(?=\n\n[A-Z][A-Z _—-]+:|$)/],['Milestones',/MILESTONES:\s*([\s\S]*?)(?=\n\n[A-Z][A-Z _—-]+:|$)/]];patterns.forEach(([label,re])=>{const m=text.match(re);if(m&&m[1]?.trim())keep.push(`${label}\n${m[1].trim()}`)});return keep.join('\n\n')}
  function scopedProject(card){const wrap=document.createElement('div');wrap.className='card-wrap scoped-project-card';const el=document.createElement('div');el.className='result-card';wrap.appendChild(el);const work=card.viewer_assignment||{};const head=document.createElement('div');head.className='scoped-project-head';const title=document.createElement('div');title.className='scoped-project-title';title.textContent=`📁 ${card.name||'Project'}`;const status=document.createElement('span');status.className='scoped-project-status';status.dataset.teamJobId=work.team_job_id||'';status.dataset.agentName=work.agent_name||'';status.textContent=work.status||'assigned';head.append(title,status);el.appendChild(head);const task=document.createElement('div');task.className='scoped-project-task';const lab=document.createElement('small');lab.textContent='Your delegated task';const strong=document.createElement('strong');strong.textContent=work.task||'Work on this project';task.append(lab,strong);el.appendChild(task);const meta=document.createElement('div');meta.className='scoped-project-meta';meta.textContent=[work.from_agent?`Delegated by ${work.from_agent}`:'',work.role||'',work.team_job_id||''].filter(Boolean).join(' · ');el.appendChild(meta);const visible=extractVisibleContext(work.scoped_brief);if(visible){const sec=document.createElement('div');sec.className='scoped-project-section';const h=document.createElement('div');h.className='scoped-project-section-title';h.textContent='Context for your work';const body=document.createElement('div');body.className='scoped-project-section-body';body.textContent=visible;sec.append(h,body);el.appendChild(sec)}if(work.latest_summary){const sec=document.createElement('div');sec.className='scoped-project-section';const h=document.createElement('div');h.className='scoped-project-section-title';h.textContent='Your latest result';const body=document.createElement('div');body.className='scoped-project-section-body scoped-project-summary';body.textContent=work.latest_summary;sec.append(h,body);el.appendChild(sec)}return wrap}
  function alreadyDeleted(card){const wrap=document.createElement('div');wrap.className='card-wrap already-deleted-card';const el=document.createElement('div');el.className='result-card';wrap.appendChild(el);const title=document.createElement('div');title.className='card-title';title.textContent='✓ Already deleted';const body=document.createElement('div');body.className='already-deleted-mark';const names=(card.names||[]).filter(Boolean);body.innerHTML=`<strong>${names.length?names.join(', '):card.name||card.entity_type||'Item'}</strong> was already deleted. No second delete action was performed.`;el.append(title,body);return wrap}
  const previous=window.renderCard;if(typeof previous==='function')window.renderCard=function(card,message){if(card?.type==='project'&&card.viewer_assignment)return scopedProject(card);if(card?.type==='already_deleted')return alreadyDeleted(card);return previous(card,message)};

  async function refreshScopedStatuses(){try{const nodes=[...document.querySelectorAll('.scoped-project-status[data-team-job-id]')].filter(n=>n.dataset.teamJobId);if(!nodes.length)return;const r=await fetch('/agent/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Show team jobs',agent_type:'general',session_id:'ui:project-work-status'})});const d=await r.json();const jobs=d.card?.type==='team_jobs'?(d.card.items||[]):[];nodes.forEach(n=>{const job=jobs.find(j=>j.id===n.dataset.teamJobId);const h=job?.handoffs?.find(x=>x.agent===n.dataset.agentName);if(h)n.textContent=h.status||job.status||'assigned'})}catch(_){}}
  setInterval(refreshScopedStatuses,1700);setTimeout(refreshScopedStatuses,800);
})();
