(()=>{
 const style=document.createElement('style');style.textContent=`.agent-copy strong{display:flex!important;align-items:center;gap:6px}.agent-role-tag{display:inline-flex;max-width:115px;padding:2px 6px;border:1px solid var(--border);border-radius:999px;background:var(--soft);color:var(--muted);font-size:9px;font-weight:650;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.agent-last-message{font-size:10px!important;color:var(--muted);margin-top:3px!important}.agent-edit{border:0;background:transparent;color:var(--muted);cursor:pointer;padding:4px;border-radius:7px}.agent-edit:hover{background:var(--soft);color:var(--text)}.agent-handoff-flow{display:flex;align-items:center;gap:8px;margin-top:10px}.agent-handoff-person{display:flex;align-items:center;gap:6px;min-width:0}.agent-handoff-orb{width:25px;height:25px;border-radius:50%;display:grid;place-items:center;font-size:8px;font-weight:800;color:#111}.agent-handoff-arrow{color:var(--muted)}.agent-handoff-role{font-size:10px;color:var(--muted)}.agent-handoff-status{margin-top:10px;padding:8px 9px;border-radius:9px;background:var(--soft);font-size:11px}`;document.head.appendChild(style);
 const last=new Map();const oldAdd=window.addAssistant;
 function initials(n){return String(n||'A').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
 function color(a){const cs=['#ff6b6b','#ffd166','#06d6a0','#4cc9f0','#5e60ce','#c77dff','#f72585','#fb8500'];let n=0;for(const ch of String(a?.id||a?.name||''))n=(n*31+ch.charCodeAt(0))>>>0;return cs[n%cs.length]}
 function rerender(){if(typeof window.loadPersistentAgents==='function')window.loadPersistentAgents()}
 if(oldAdd)window.addAssistant=function(message,card){const active=window.__agentieActiveAgent?.();if(active&&message)last.set(active.id,String(message).replace(/\s+/g,' ').trim());const r=oldAdd(message,card);setTimeout(()=>window.__agentieRefreshAgentRows?.(),0);return r};
 window.__agentieRefreshAgentRows=()=>{document.querySelectorAll('#persistentAgentList .agent-row').forEach(row=>{const name=row.querySelector('.agent-copy strong')?.textContent||'';const a=(window.__agentieAgents||[]).find(x=>x.name===name);if(!a)return;const copy=row.querySelector('.agent-copy');if(!copy)return;const strong=copy.querySelector('strong');strong.replaceChildren(document.createTextNode(a.name+' '));const tag=document.createElement('span');tag.className='agent-role-tag';tag.textContent=a.role||'general';strong.appendChild(tag);let sub=copy.querySelector('small');if(!sub){sub=document.createElement('small');copy.appendChild(sub)}sub.className='agent-last-message';sub.textContent=last.get(a.id)||'No messages yet';if(!row.querySelector('.agent-edit')){const edit=document.createElement('button');edit.type='button';edit.className='agent-edit';edit.title='Edit agent';edit.textContent='⋯';edit.onclick=e=>{e.stopPropagation();const nextName=prompt('Agent name',a.name);if(nextName===null)return;const nextRole=prompt('Role / title',a.role||'general');if(nextRole===null)return;const commands=[];if(nextName.trim()&&nextName.trim()!==a.name)commands.push(`Rename agent ${a.name} to ${nextName.trim()}`);const roleTarget=nextName.trim()||a.name;if(nextRole.trim()&&nextRole.trim()!==a.role)commands.push(`Change agent ${roleTarget} role to ${nextRole.trim()}`);(async()=>{for(const message of commands){const r=await fetch('/agent/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,agent_type:'general',session_id:'ui:agent-edit'})});if(!r.ok)break}await rerender()})()};const del=row.querySelector('.agent-delete');row.insertBefore(edit,del)}})};
 const observer=new MutationObserver(()=>window.__agentieRefreshAgentRows?.());const list=document.getElementById('persistentAgentList');if(list)observer.observe(list,{childList:true});setTimeout(()=>window.__agentieRefreshAgentRows?.(),50);
 const previous=window.renderCard;window.renderCard=function(c,m){if(c?.type!=='agent_handoff')return previous(c,m);const w=document.createElement('div');w.className='card-wrap';const e=document.createElement('div');e.className='result-card';w.appendChild(e);const title=document.createElement('div');title.className='card-title';title.textContent='Agent handoff';e.appendChild(title);const flow=document.createElement('div');flow.className='agent-handoff-flow';for(const [a,arrow] of [[c.from_agent,true],[c.to_agent,false]]){const p=document.createElement('div');p.className='agent-handoff-person';const orb=document.createElement('span');orb.className='agent-handoff-orb';orb.style.background=color(a);orb.textContent=initials(a?.name);const txt=document.createElement('div');const n=document.createElement('strong');n.textContent=a?.name||'Agent';const role=document.createElement('div');role.className='agent-handoff-role';role.textContent=a?.role||'';txt.append(n,role);p.append(orb,txt);flow.appendChild(p);if(arrow){const ar=document.createElement('span');ar.className='agent-handoff-arrow';ar.textContent='→';flow.appendChild(ar)}}e.appendChild(flow);const status=document.createElement('div');status.className='agent-handoff-status';status.textContent=`${c.reason||'Specialty matched'} · ${c.team_job?.status||'queued'} · ${c.team_job?.id||''}`;e.appendChild(status);return w};
})();
