if(typeof ServiceWorkerGlobalScope!=='undefined'&&self instanceof ServiceWorkerGlobalScope){
  self.addEventListener('install',()=>self.skipWaiting());
  self.addEventListener('activate',event=>event.waitUntil(self.clients.claim()));
  self.addEventListener('fetch',event=>{
    if(event.request.mode!=='navigate')return;
    event.respondWith(fetch(event.request).then(response=>{
      const headers=new Headers(response.headers);
      headers.set('Cross-Origin-Opener-Policy','same-origin');
      headers.set('Cross-Origin-Embedder-Policy','credentialless');
      headers.set('Permissions-Policy','cross-origin-isolated=*');
      return new Response(response.body,{status:response.status,statusText:response.statusText,headers});
    }));
  });
}else{
(()=>{
  if('serviceWorker' in navigator&&!window.crossOriginIsolated&&!sessionStorage.getItem('agentie-coi-reload')){
    navigator.serviceWorker.register('/browser-screen.js',{scope:'/'}).then(()=>{
      sessionStorage.setItem('agentie-coi-reload','1');
      if(navigator.serviceWorker.controller)location.reload();
      else navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});
    }).catch(()=>{});
  }else if(window.crossOriginIsolated){sessionStorage.removeItem('agentie-coi-reload')}

  const messages=document.getElementById('messages'),input=document.getElementById('messageInput'),send=document.getElementById('sendButton'),agentType=document.getElementById('agentType');
  if(!messages||!input||!send||window.__agentieRealComputer)return;window.__agentieRealComputer=true;

  const style=document.createElement('style');style.textContent=`
    .agentie-real-row{display:flex;margin:8px 0 12px;justify-content:flex-start}.agentie-real-computer{width:min(500px,84vw);border:1px solid var(--border);border-radius:13px;background:var(--panel);overflow:hidden;box-shadow:0 7px 20px rgba(0,0,0,.11);transition:width .18s ease,box-shadow .18s ease}.agentie-real-computer.arc-minimized{width:min(395px,82vw)}
    .arc-head{height:34px;display:flex;align-items:center;gap:7px;padding:0 7px 0 10px;border-bottom:1px solid var(--border);user-select:none}.arc-dot{width:7px;height:7px;border-radius:50%;background:#888}.arc-dot.on{background:#32a567;box-shadow:0 0 0 3px rgba(50,165,103,.14)}.arc-dot.error{background:#d64b4b}.arc-title{font-size:11px;font-weight:700;flex:1}.arc-status{font-size:9px;color:var(--muted);max-width:145px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.arc-window-controls{display:flex;align-self:stretch;margin:-1px -7px -1px 3px}.arc-window-controls button{width:34px;height:100%;border:0;border-left:1px solid transparent;border-radius:0;background:transparent;color:var(--text);font:13px/1 system-ui,sans-serif;cursor:pointer;display:grid;place-items:center}.arc-window-controls button:hover{background:var(--soft)}.arc-window-controls .arc-close:hover{background:#c42b1c;color:#fff}.arc-window-controls .arc-close{font-size:15px}.arc-window-controls .arc-maximize{font-size:12px}.arc-window-controls .arc-minimize{font-size:15px;padding-bottom:5px}
    .arc-screen{position:relative;width:100%;aspect-ratio:16/9;background:#111;overflow:hidden}.arc-screen:fullscreen{width:100vw;height:100vh;aspect-ratio:auto;background:#000}.arc-frame{position:absolute;left:0;top:0;width:1440px;height:900px;border:0;background:#111;transform-origin:0 0}.arc-overlay{position:absolute;inset:0;display:grid;place-items:center;background:linear-gradient(145deg,#121b2a,#1d334d);color:#eef3f8;text-align:center;padding:14px;z-index:2}.arc-overlay.hidden{display:none}.arc-spinner{width:18px;height:18px;border:2px solid rgba(255,255,255,.25);border-top-color:#fff;border-radius:50%;animation:arcspin .8s linear infinite;margin:0 auto 8px}@keyframes arcspin{to{transform:rotate(360deg)}}.arc-overlay strong{font-size:12px}.arc-overlay p{font-size:10px;color:#b9c5d2;line-height:1.4;max-width:390px;margin:5px auto 0}.arc-setup{margin:8px auto 0;max-width:430px;background:rgba(0,0,0,.32);padding:7px 9px;border-radius:8px;font:10px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;text-align:left;user-select:text}.arc-start{margin-top:9px;border:1px solid rgba(255,255,255,.25);background:rgba(255,255,255,.1);color:#fff;border-radius:8px;padding:6px 10px;cursor:pointer}.arc-foot{display:flex;gap:7px;padding:5px 9px;border-top:1px solid var(--border);font-size:9px;color:var(--muted)}.arc-foot .arc-detail{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.agentie-real-computer.arc-starting .arc-status,.agentie-real-computer.arc-starting .arc-foot{display:none}.arc-minimized .arc-screen,.arc-minimized .arc-foot{display:none}.arc-minimized .arc-head{border-bottom:0}.arc-minimized .arc-minimize{padding-bottom:0}.arc-minimized .arc-minimize::after{content:'↥';font-size:13px}.arc-minimized .arc-minimize{font-size:0}
    .browser-actions-card,.browser-approval-card,.web-snapshot-card,.computer-takeover-card{width:min(680px,92vw)}.browser-actions-list{display:grid;gap:6px;margin-top:10px}.browser-action{padding:8px 10px;border-radius:9px;background:var(--soft);font-size:12px}.browser-approval-step,.computer-takeover-reason{margin-top:10px;padding:10px;border-radius:10px;background:var(--soft);font-size:12px}.browser-approval-actions,.computer-takeover-actions{display:flex;gap:7px;margin-top:10px}.browser-approval-actions button,.computer-takeover-actions button{border:1px solid var(--border);border-radius:8px;padding:6px 10px;background:var(--panel);color:var(--text);cursor:pointer}.browser-approval-actions .approve,.computer-takeover-actions .approve{background:var(--accent);color:var(--accent-text);border-color:var(--accent)}.web-snapshot-card img{display:block;width:100%;max-height:520px;object-fit:contain;border-radius:11px;border:1px solid var(--border);background:#111;margin-top:10px}.web-snapshot-url{font-size:10px;color:var(--muted);margin-top:7px;overflow-wrap:anywhere}.web-snapshot-excerpt{font-size:12px;line-height:1.45;margin-top:8px;color:var(--muted)}
    @media(max-width:760px){.agentie-real-computer{width:min(92vw,490px)}.arc-status{display:none}.arc-window-controls button{width:32px}}
  `;document.head.appendChild(style);

  const computerIntent=t=>/^\s*use\s+computer\s+for\s*:/i.test(t)||/https?:\/\//i.test(t)&&/\b(open|visit|check|inspect|view|screenshot|capture|monitor|watch|click|type|fill|search|scroll|press|browse|navigate)\b/i.test(t)||/^\s*(click|type|fill|scroll|press|go back|back|forward|new tab|close tab|search for)\b/i.test(t)||/\b(show desktop|start (?:the )?computer|open (?:the )?terminal|file manager|computer files|computer tasks|computer notes)\b/i.test(t);
  let row=null,root=null,starting=null,stopped=false,frameObserver=null,lastDesktopUrl='',ownerKey=null,currentComputerState='STOPPED';

  function activeAgent(){const active=document.querySelector('#persistentAgentList .agent-row.active');if(!active)return null;const name=active.querySelector('.agent-copy strong')?.childNodes?.[0]?.textContent?.trim()||active.querySelector('.agent-copy strong')?.textContent?.trim();return (window.__agentieAgents||[]).find(a=>a.name===name)||null}
  function agentKey(){const a=activeAgent();return a?.id||`base:${agentType?.value||'general'}`}
  function computerOwnerName(){return activeAgent()?.name||'Agentie'}
  function syncComputerOwner(){if(!root)return;const title=root.querySelector('.arc-title');if(title)title.textContent=`${computerOwnerName()} Computer`;const frame=root.querySelector('.arc-frame');if(frame)frame.title=`${computerOwnerName()} Computer`}
  function makeComputer(){const r=document.createElement('div');r.className='assistant-row agentie-real-row';r.innerHTML=`<div class="agentie-real-computer"><div class="arc-head"><span class="arc-dot"></span><span class="arc-title">Agentie Computer</span><span class="arc-status"></span><span class="arc-window-controls"><button class="arc-minimize" type="button" title="Minimize" aria-label="Minimize">−</button><button class="arc-maximize" type="button" title="Maximize" aria-label="Maximize">□</button><button class="arc-close" type="button" title="Close computer" aria-label="Close">×</button></span></div><div class="arc-screen"><iframe class="arc-frame" title="Agentie Computer" allow="clipboard-read; clipboard-write; fullscreen" allowfullscreen tabindex="0"></iframe><div class="arc-overlay"><div><div class="arc-spinner"></div><strong>Starting Computer</strong></div></div></div><div class="arc-foot"><span class="arc-detail">Persistent Company Computer</span></div></div>`;return r}
  function fitFrame(){if(!root||root.classList.contains('arc-minimized'))return;const screen=root.querySelector('.arc-screen'),frame=root.querySelector('.arc-frame');if(!screen||!frame)return;const w=screen.clientWidth,h=screen.clientHeight;if(!w||!h)return;const scale=Math.min(w/1440,h/900);const fw=Math.round(1440*scale),fh=Math.round(900*scale);frame.style.transform=`scale(${scale})`;frame.style.left=`${Math.round((w-fw)/2)}px`;frame.style.top=`${Math.round((h-fh)/2)}px`}
  function place(){if(!row){row=makeComputer();root=row.querySelector('.agentie-real-computer');wire()}syncComputerOwner();messages.querySelectorAll('.agentie-real-row').forEach(x=>{if(x!==row)x.remove()});const users=messages.querySelectorAll('.user-row'),anchor=users.length?users[users.length-1]:null;if(anchor){if(row.previousElementSibling!==anchor)anchor.after(row)}else if(!row.isConnected)messages.appendChild(row);row.dataset.agentKey=ownerKey||agentKey();requestAnimationFrame(fitFrame);return root}
  async function agentCall(message){const a=activeAgent();const payload={message,agent_type:a?.base||agentType?.value||'general',...(a?{session_id:`${a.session_prefix}main`}:{})};const r=await fetch('/agent/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Computer request failed');return d}
  function friendlyState(state){return ({STARTING:'Starting Computer',READY:'Computer Ready',AGENT_CONTROL:'Agent Working',USER_REQUIRED:'User Action Required',USER_CONTROL:'User Control',IDLE:'Computer Ready',SUSPENDED:'Suspended',STOPPED:'Stopped',ERROR:'Error'})[state]||String(state||'Computer Ready').replaceAll('_',' ')}
  function setState(state,detail){place();currentComputerState=state||currentComputerState;const dot=root.querySelector('.arc-dot'),status=root.querySelector('.arc-status');const startingState=state==='STARTING'||state==='starting';root.classList.toggle('arc-starting',startingState);dot.classList.toggle('on',['READY','AGENT_CONTROL','USER_REQUIRED','USER_CONTROL','IDLE','on'].includes(state));dot.classList.toggle('error',state==='ERROR'||state==='error');status.textContent=friendlyState(state);if(detail)root.querySelector('.arc-detail').textContent=detail}
  function showOverlay(title,text,setup,withStart=false){place();root.classList.remove('arc-minimized');const o=root.querySelector('.arc-overlay');o.classList.remove('hidden');if(title==='Starting Computer'){o.innerHTML='<div><div class="arc-spinner"></div><strong>Starting Computer</strong></div>';return}o.innerHTML=`<div><div style="font-size:26px;margin-bottom:7px">${title==='Stopped'?'⏻':'⚠'}</div><strong>${esc(title)}</strong><p>${esc(text||'')}</p>${setup?`<div class="arc-setup">${esc(setup)}</div>`:''}${withStart?'<button class="arc-start" type="button">Start Computer</button>':''}</div>`;const b=o.querySelector('.arc-start');if(b)b.onclick=()=>ensureComputer(true)}
  function desktopSrc(url){return url+(url.includes('?')?'&':'?')+'t='+Date.now()}
  function connect(url,state='READY',forceReload=false){place();lastDesktopUrl=url;root.classList.remove('arc-minimized');const frame=root.querySelector('.arc-frame');frame.onload=()=>{requestAnimationFrame(()=>{fitFrame();try{frame.focus()}catch(_){}})};if(forceReload||!frame.src||frame.src==='about:blank'||!frame.src.startsWith(url))frame.src=desktopSrc(url);root.querySelector('.arc-overlay').classList.add('hidden');stopped=false;const detail=state==='AGENT_CONTROL'?'Agent is controlling the shared Company Computer':state==='USER_CONTROL'?'You control this same persistent Company Computer':'Persistent Company Computer';setState(state,detail);setTimeout(fitFrame,80)}
  function minimizeComputer(){place();root.classList.toggle('arc-minimized');if(!root.classList.contains('arc-minimized'))setTimeout(()=>{fitFrame();try{root.querySelector('.arc-frame').focus()}catch(_){}},80)}
  function maximizeComputer(){place();const screen=root.querySelector('.arc-screen');if(document.fullscreenElement===screen){document.exitFullscreen().catch(()=>{});return}if(screen.requestFullscreen)screen.requestFullscreen().catch(()=>{})}
  async function ensureComputer(force=false){ownerKey=agentKey();place();if(starting)return starting;if(!force&&!stopped&&root.querySelector('.arc-frame').src&&root.querySelector('.arc-overlay').classList.contains('hidden')){root.classList.remove('arc-minimized');setTimeout(fitFrame,50);return}setState('STARTING','');showOverlay('Starting Computer','');starting=(async()=>{try{const d=await agentCall('Desktop control: start'),c=d.card||{};if(c.mode==='qemu'&&c.running&&c.display_url){connect(c.display_url,c.state||'USER_CONTROL',true);return}throw new Error(c.error||d.message||'Agentie Computer did not start.')}catch(e){stopped=true;setState('ERROR',e.message);showOverlay('Computer could not start',e.message,null,true)}finally{starting=null}})();return starting}
  async function stopComputer(){place();setState('STARTING','');showOverlay('Starting Computer','');try{await agentCall('Desktop control: stop')}catch(_){}const frame=root.querySelector('.arc-frame');frame.src='about:blank';lastDesktopUrl='';stopped=true;root.classList.remove('arc-minimized');setState('STOPPED',`${computerOwnerName()} Computer is powered down`);showOverlay('Stopped','The persistent Company Computer is powered down.',null,true)}
  function wire(){const screen=root.querySelector('.arc-screen');root.querySelector('.arc-minimize').onclick=minimizeComputer;root.querySelector('.arc-maximize').onclick=maximizeComputer;root.querySelector('.arc-close').onclick=stopComputer;if('ResizeObserver'in window){frameObserver=new ResizeObserver(()=>requestAnimationFrame(fitFrame));frameObserver.observe(screen)}document.addEventListener('fullscreenchange',()=>setTimeout(fitFrame,80));window.addEventListener('resize',()=>requestAnimationFrame(fitFrame));document.addEventListener('visibilitychange',()=>{if(!document.hidden&&root&&!root.classList.contains('arc-minimized'))setTimeout(fitFrame,100)})}
  function esc(s){const d=document.createElement('div');d.textContent=String(s??'');return d.innerHTML}
  function prepare(text){if(!computerIntent(text))return;ownerKey=agentKey();setTimeout(()=>{place();setState('STARTING','');showOverlay('Starting Computer','');document.querySelector('.chat-shell')?.scrollTo({top:document.querySelector('.chat-shell').scrollHeight,behavior:'smooth'})},0)}
  send.addEventListener('click',()=>{const t=input.value.trim();if(t)prepare(t)},true);input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){const t=input.value.trim();if(t)prepare(t)}},true);
  function resend(text){if(!text)return;input.value=text;input.dispatchEvent(new Event('input',{bubbles:true}));send.click()}
  function hidden(){const x=document.createElement('span');x.style.display='none';return x}
  function renderTakeover(card,message){place();setState('USER_REQUIRED',card.reason||'User action required');const wrap=document.createElement('div');wrap.className='card-wrap computer-takeover-card';const el=document.createElement('div');el.className='result-card';wrap.appendChild(el);if(message){const top=document.createElement('div');top.className='card-topline';top.textContent=message;el.appendChild(top)}const title=document.createElement('div');title.className='card-title';title.textContent='🖥 User action required';el.appendChild(title);const reason=document.createElement('div');reason.className='computer-takeover-reason';reason.textContent=card.reason||'Complete the required action on the same Company Computer.';el.appendChild(reason);const actions=document.createElement('div');actions.className='computer-takeover-actions';const take=document.createElement('button'),cont=document.createElement('button');take.className='approve';take.textContent='Take Control';cont.textContent='Continue Agent';cont.disabled=true;actions.append(take,cont);el.appendChild(actions);take.onclick=async()=>{take.disabled=true;try{const d=await agentCall('Desktop control: take user control'),c=d.card||{};if(c.mode!=='qemu'||!c.display_url)throw new Error(d.message||'Could not enable user control');connect(c.display_url,'USER_CONTROL',true);title.textContent='🖥 User Control';take.remove();cont.disabled=false}catch(e){take.disabled=false;reason.textContent=e.message}};cont.onclick=async()=>{cont.disabled=true;try{const d=await agentCall('Desktop control: continue agent'),c=d.card||{};if(c.mode==='qemu'&&c.display_url)connect(c.display_url,'AGENT_CONTROL',true);title.textContent='✓ Control returned to agent';actions.remove();if(card.command)setTimeout(()=>resend(card.command),120)}catch(e){cont.disabled=false;reason.textContent=e.message}};return wrap}

  const previousRender=window.renderCard;if(typeof previousRender==='function')window.renderCard=function(card,message){
    if(card?.type==='desktop_view'){
      ownerKey=ownerKey||agentKey();place();
      if(card.mode==='qemu'){
        if(card.running&&card.display_url)connect(card.display_url,card.state||'READY',false);
        else if(card.state==='SUSPENDED'||card.app==='suspended'){stopped=false;root.querySelector('.arc-frame').src='about:blank';setState('SUSPENDED','Company Computer is suspended to save resources');showOverlay('Suspended','The Computer will resume when needed.',null,true)}
        else if(card.state==='STOPPED'||card.app==='stopped'){stopped=true;root.querySelector('.arc-frame').src='about:blank';lastDesktopUrl='';setState('STOPPED',`${computerOwnerName()} Computer stopped`);showOverlay('Stopped','The persistent Company Computer is powered down.',null,true)}
        else if(card.error||card.state==='ERROR'){stopped=true;const err=card.error||'Computer runtime error';setState('ERROR',err);showOverlay('Computer could not start',err,card.action||null,true)}
      }
      return hidden()
    }
    if(card?.type==='computer_takeover')return renderTakeover(card,message);
    if(!card||!['browser_actions','browser_approval','web_snapshot'].includes(card.type))return previousRender(card,message);
    if(card.type==='browser_approval'){
      place();const wrap=document.createElement('div');wrap.className='card-wrap browser-approval-card';const el=document.createElement('div');el.className='result-card';wrap.appendChild(el);if(message){const top=document.createElement('div');top.className='card-topline';top.textContent=message;el.appendChild(top)}const title=document.createElement('div');title.className='card-title';title.textContent='🛡 Browser approval';el.appendChild(title);const step=document.createElement('div');step.className='browser-approval-step';step.textContent=card.step||'Consequential browser action';el.appendChild(step);const actions=document.createElement('div');actions.className='browser-approval-actions';const a=document.createElement('button'),d=document.createElement('button');a.className='approve';a.textContent='Approve once';d.textContent='Deny';actions.append(a,d);el.appendChild(actions);async function resolve(ok){a.disabled=d.disabled=true;try{const r=await fetch(`/approvals/${card.approval.id}/resolve`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({approved:ok})});if(!r.ok)throw new Error('Could not resolve approval');title.textContent=ok?'✓ Browser action approved':'Browser action denied';actions.remove();if(ok)setTimeout(()=>resend(card.command),80)}catch(_){a.disabled=d.disabled=false}}a.onclick=()=>resolve(true);d.onclick=()=>resolve(false);return wrap
    }
    if(card.type==='browser_actions'){
      place();const wrap=document.createElement('div');wrap.className='card-wrap browser-actions-card';const el=document.createElement('div');el.className='result-card';wrap.appendChild(el);if(message){const top=document.createElement('div');top.className='card-topline';top.textContent=message;el.appendChild(top)}const title=document.createElement('div');title.className='card-title';title.textContent=`🖥 ${card.title||'Browser actions'}`;el.appendChild(title);const list=document.createElement('div');list.className='browser-actions-list';(card.actions||[]).forEach(x=>{const i=document.createElement('div');i.className='browser-action';i.textContent=x;list.appendChild(i)});el.appendChild(list);return wrap
    }
    const wrap=document.createElement('div');wrap.className='card-wrap web-snapshot-card';const el=document.createElement('div');el.className='result-card';wrap.appendChild(el);if(message){const top=document.createElement('div');top.className='card-topline';top.textContent=message;el.appendChild(top)}const title=document.createElement('div');title.className='card-title';title.textContent=`🌐 ${card.title||'Website snapshot'}`;el.appendChild(title);const img=document.createElement('img');img.src=card.image_url;img.alt='Website screenshot';el.appendChild(img);const u=document.createElement('div');u.className='web-snapshot-url';u.textContent=card.url||'';el.appendChild(u);if(card.excerpt){const ex=document.createElement('div');ex.className='web-snapshot-excerpt';ex.textContent=card.excerpt;el.appendChild(ex)}return wrap
  };
})();
}