(()=>{
  const messages=document.getElementById('messages'),input=document.getElementById('messageInput'),send=document.getElementById('sendButton'),agentType=document.getElementById('agentType');
  if(!messages||!input||!send||window.__agentieRealComputer)return;window.__agentieRealComputer=true;
  const NOVNC_URL='http://127.0.0.1:6080/vnc.html?host=127.0.0.1&port=6080&autoconnect=1&resize=remote&reconnect=1';

  const style=document.createElement('style');style.textContent=`
    .agentie-computer-row{display:flex;margin:10px 0 14px}.agentie-computer{width:min(900px,96vw);border:1px solid var(--border);border-radius:16px;background:var(--panel);overflow:hidden;box-shadow:0 10px 34px rgba(0,0,0,.10)}
    .agentie-computer-head{height:44px;display:flex;align-items:center;gap:8px;padding:0 10px;border-bottom:1px solid var(--border)}.computer-dot{width:8px;height:8px;border-radius:50%;background:#38a169;box-shadow:0 0 0 3px rgba(56,161,105,.14)}.computer-title{font-size:12px;font-weight:700;flex:1}.computer-status{font-size:10px;color:var(--muted);max-width:240px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.agentie-computer-head button{border:1px solid var(--border);background:transparent;color:var(--muted);border-radius:7px;padding:4px 8px;cursor:pointer;font-size:11px}.agentie-computer-head button:hover{background:var(--soft)}
    .computer-frame-wrap{height:min(620px,70vh);min-height:420px;background:#080b10;position:relative}.computer-frame{width:100%;height:100%;border:0;display:block;background:#080b10}.computer-placeholder{position:absolute;inset:0;display:grid;place-items:center;text-align:center;color:#d6dde8;background:linear-gradient(145deg,#101827,#1f3553)}.computer-placeholder-inner{max-width:520px;padding:24px}.computer-placeholder strong{display:block;font-size:18px;margin-bottom:8px}.computer-placeholder p{font-size:13px;color:#aeb8c6;line-height:1.45;margin:8px 0}.computer-placeholder code{font-size:12px;background:rgba(255,255,255,.1);padding:2px 5px;border-radius:5px}.computer-actions{display:flex;gap:7px;justify-content:center;flex-wrap:wrap;margin-top:13px}.computer-actions button{border:1px solid rgba(255,255,255,.18);background:rgba(255,255,255,.08);color:#fff;border-radius:9px;padding:8px 12px;cursor:pointer}.computer-foot{display:flex;gap:8px;align-items:center;padding:8px 10px;border-top:1px solid var(--border);font-size:10px;color:var(--muted)}.computer-foot span:first-child{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
    .web-snapshot-card,.browser-actions-card,.browser-approval-card{width:min(680px,92vw)}.web-snapshot-card img{display:block;width:100%;max-height:520px;object-fit:contain;border-radius:11px;border:1px solid var(--border);background:#111;margin-top:10px}.web-snapshot-url{font-size:10px;color:var(--muted);margin-top:7px;overflow-wrap:anywhere}.web-snapshot-excerpt{font-size:12px;line-height:1.45;margin-top:8px;color:var(--muted)}.browser-actions-list{display:grid;gap:6px;margin-top:10px}.browser-action{padding:8px 10px;border-radius:9px;background:var(--soft);font-size:12px}.browser-approval-step{margin-top:10px;padding:10px;border-radius:10px;background:var(--soft);font-size:12px}.browser-approval-actions{display:flex;gap:7px;margin-top:10px}.browser-approval-actions button{border:1px solid var(--border);border-radius:8px;padding:6px 10px;background:var(--panel);color:var(--text);cursor:pointer}.browser-approval-actions .approve{background:var(--accent);color:var(--accent-text);border-color:var(--accent)}
    @media(max-width:760px){.agentie-computer{width:min(100%,96vw)}.computer-frame-wrap{height:62vh;min-height:360px}}
  `;document.head.appendChild(style);

  const computerIntent=t=>/\b(computer|desktop|open (?:the )?terminal|file manager|open (?:my )?files|show (?:my )?files|open (?:my )?plugins|open (?:my )?notes|open (?:my )?tasks|browser|chrome|visit|open https?:\/\/|go to https?:\/\/|screenshot|monitor|watch|click|scroll|type|search for|go back|new tab|close tab)\b/i.test(t)||/https?:\/\//i.test(t);
  let row=null,iframe=null,statusEl=null,placeholder=null,lastShown=0;

  function makeComputer(){
    const r=document.createElement('div');r.className='assistant-row agentie-computer-row';
    r.innerHTML=`<div class="agentie-computer"><div class="agentie-computer-head"><span class="computer-dot"></span><span class="computer-title">Agentie Computer</span><span class="computer-status">Real WSL desktop</span><button data-act="reload">Reload</button><button data-act="pop">Open</button></div><div class="computer-frame-wrap"><iframe class="computer-frame" allow="clipboard-read; clipboard-write; fullscreen" referrerpolicy="no-referrer"></iframe><div class="computer-placeholder"><div class="computer-placeholder-inner"><strong>Agentie real computer</strong><p>This is the WSL Linux desktop through noVNC. Mouse, wheel and keyboard go directly into the desktop.</p><p>If it does not connect, start Agentie with <code>scripts\\start_agentie_with_wsl_computer.ps1</code>.</p><div class="computer-actions"><button data-act="load">Connect</button><button data-act="pop">Open desktop in new tab</button></div></div></div></div><div class="computer-foot"><span>${NOVNC_URL}</span><span>WSL · XFCE · Chrome · noVNC</span></div></div>`;
    return r;
  }
  function placeComputer(){
    if(!row){row=makeComputer();iframe=row.querySelector('.computer-frame');statusEl=row.querySelector('.computer-status');placeholder=row.querySelector('.computer-placeholder');row.querySelectorAll('[data-act]').forEach(btn=>btn.onclick=()=>act(btn.dataset.act));}
    const working=[...messages.querySelectorAll('.assistant-row')].reverse().find(x=>x.querySelector('.working'));if(working)messages.insertBefore(row,working);else messages.appendChild(row);window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'});return row;
  }
  function connect(){placeComputer();statusEl.textContent='Connecting to WSL desktop';placeholder.style.display='grid';iframe.onload=()=>{statusEl.textContent='Connected';setTimeout(()=>placeholder.style.display='none',550)};iframe.src=NOVNC_URL+(NOVNC_URL.includes('?')?'&':'?')+'t='+Date.now();lastShown=Date.now();}
  function act(name){if(name==='reload'||name==='load')connect();else if(name==='pop')window.open(NOVNC_URL,'agentie-wsl-computer');}
  function prepare(text){if(!computerIntent(text))return;placeComputer();if(!iframe.src||Date.now()-lastShown>15000)connect();}

  send.addEventListener('click',()=>{const text=input.value.trim();if(text)prepare(text)},true);input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){const text=input.value.trim();if(text)prepare(text)}},true);

  function esc(s){const d=document.createElement('div');d.textContent=String(s??'');return d.innerHTML}
  function resend(text){if(!text)return;input.value=text;input.dispatchEvent(new Event('input',{bubbles:true}));send.click()}
  const previousRender=window.renderCard;if(typeof previousRender==='function')window.renderCard=function(card,message){
    if(!card||!['web_snapshot','browser_actions','browser_approval','desktop_view'].includes(card.type))return previousRender(card,message);
    if(card.type==='desktop_view'){placeComputer();connect();const hidden=document.createElement('span');hidden.style.display='none';return hidden}
    if(card.type==='browser_approval'){placeComputer();const wrap=document.createElement('div');wrap.className='card-wrap browser-approval-card';const el=document.createElement('div');el.className='result-card';wrap.appendChild(el);if(message){const top=document.createElement('div');top.className='card-topline';top.textContent=message;el.appendChild(top)}const title=document.createElement('div');title.className='card-title';title.textContent='🛡 Browser approval';el.appendChild(title);const u=document.createElement('div');u.className='web-snapshot-url';u.textContent=card.url||'';el.appendChild(u);const step=document.createElement('div');step.className='browser-approval-step';step.textContent=card.step||'Consequential browser action';el.appendChild(step);const actions=document.createElement('div');actions.className='browser-approval-actions';const approve=document.createElement('button'),deny=document.createElement('button');approve.className='approve';approve.textContent='Approve once';deny.textContent='Deny';actions.append(approve,deny);el.appendChild(actions);async function resolve(allowed){approve.disabled=true;deny.disabled=true;try{const r=await fetch(`/approvals/${card.approval.id}/resolve`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({approved:allowed})});if(!r.ok)throw new Error('Could not resolve approval');title.textContent=allowed?'✓ Browser action approved':'Browser action denied';actions.remove();if(allowed)setTimeout(()=>resend(card.command),80)}catch(err){approve.disabled=false;deny.disabled=false}}approve.onclick=()=>resolve(true);deny.onclick=()=>resolve(false);return wrap}
    if(card.type==='browser_actions'){placeComputer();const wrap=document.createElement('div');wrap.className='card-wrap browser-actions-card';const el=document.createElement('div');el.className='result-card';wrap.appendChild(el);if(message){const top=document.createElement('div');top.className='card-topline';top.textContent=message;el.appendChild(top)}const title=document.createElement('div');title.className='card-title';title.textContent=`🖥 ${card.title||'Browser actions'}`;el.appendChild(title);const u=document.createElement('div');u.className='web-snapshot-url';u.textContent=card.url||'';el.appendChild(u);const list=document.createElement('div');list.className='browser-actions-list';(card.actions||[]).forEach(a=>{const item=document.createElement('div');item.className='browser-action';item.textContent=a;list.appendChild(item)});el.appendChild(list);return wrap}
    placeComputer();const wrap=document.createElement('div');wrap.className='card-wrap web-snapshot-card';const el=document.createElement('div');el.className='result-card';wrap.appendChild(el);if(message){const top=document.createElement('div');top.className='card-topline';top.textContent=message;el.appendChild(top)}const title=document.createElement('div');title.className='card-title';title.textContent=`🌐 ${card.title||'Website snapshot'}`;el.appendChild(title);const shot=document.createElement('img');shot.src=card.image_url;shot.alt=`Screenshot of ${card.title||card.url||'website'}`;el.appendChild(shot);const u=document.createElement('div');u.className='web-snapshot-url';u.textContent=card.url||'';el.appendChild(u);const meta=document.createElement('div');meta.className='card-meta';meta.textContent=`${card.changed?'Changed':'Snapshot'}${card.captured_at?' · '+new Date(card.captured_at).toLocaleString():''}`;el.appendChild(meta);if(card.excerpt){const ex=document.createElement('div');ex.className='web-snapshot-excerpt';ex.textContent=card.excerpt;el.appendChild(ex)}return wrap;
  };
})();
