(()=>{
  const messages=document.getElementById('messages'),input=document.getElementById('messageInput'),send=document.getElementById('sendButton'),agentType=document.getElementById('agentType');
  if(!messages||!input||!send||window.__agentieVirtualDesktop)return;window.__agentieVirtualDesktop=true;
  const style=document.createElement('style');style.textContent=`
  .agentie-desktop-row{display:flex;margin:10px 0 14px}.agentie-desktop{width:min(760px,94vw);border:1px solid var(--border);border-radius:16px;background:var(--panel);overflow:hidden;box-shadow:0 8px 28px rgba(0,0,0,.08)}
  .desktop-head{height:42px;display:flex;align-items:center;gap:8px;padding:0 10px;border-bottom:1px solid var(--border)}.desktop-dot{width:8px;height:8px;border-radius:50%;background:#8b8b8b}.desktop-dot.active{background:#38a169;box-shadow:0 0 0 3px rgba(56,161,105,.14)}.desktop-dot.error{background:#dc4c4c}.desktop-title{font-size:12px;font-weight:700;flex:1}.desktop-status{font-size:10px;color:var(--muted);max-width:170px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.desktop-head button{border:1px solid var(--border);background:transparent;color:var(--muted);border-radius:7px;padding:4px 7px;cursor:pointer;font-size:11px}.desktop-head button:hover{background:var(--soft)}
  .desktop-screen{position:relative;aspect-ratio:16/9;background:linear-gradient(135deg,#111827,#26374f);overflow:hidden}.desktop-home{position:absolute;inset:0;padding:24px;display:grid;grid-template-columns:repeat(4,minmax(80px,1fr));align-content:start;gap:16px;background:radial-gradient(circle at 15% 10%,rgba(255,255,255,.08),transparent 28%),linear-gradient(145deg,#172235,#213d5c 60%,#1b2c45);color:white}.desktop-icon{border:0;background:transparent;color:white;display:flex;flex-direction:column;align-items:center;gap:7px;cursor:pointer;padding:8px;border-radius:12px}.desktop-icon:hover{background:rgba(255,255,255,.1)}.desktop-icon .ico{width:48px;height:48px;border-radius:13px;display:grid;place-items:center;background:rgba(255,255,255,.13);font-size:23px;backdrop-filter:blur(8px)}.desktop-icon span:last-child{font-size:11px}.desktop-clock{position:absolute;right:18px;bottom:14px;color:rgba(255,255,255,.82);font-size:11px;text-align:right}
  .desktop-app{position:absolute;inset:0;background:var(--panel);display:none;flex-direction:column}.desktop-app.visible{display:flex}.app-bar{height:38px;display:flex;align-items:center;gap:7px;border-bottom:1px solid var(--border);padding:0 9px}.app-bar strong{font-size:12px;flex:1}.app-bar button{border:1px solid var(--border);background:transparent;color:var(--text);border-radius:7px;padding:4px 7px;cursor:pointer;font-size:11px}.app-body{flex:1;min-height:0;overflow:auto;padding:12px}
  .browser-app .app-body{padding:0;background:#111;position:relative;overflow:hidden}.browser-frame{width:100%;height:100%;display:block;object-fit:contain;background:#111;user-select:none;-webkit-user-drag:none;cursor:crosshair}.browser-placeholder{position:absolute;inset:0;display:grid;place-items:center;color:#aaa;font-size:12px;text-align:center;padding:20px;pointer-events:none}.browser-click-dot{position:absolute;width:14px;height:14px;border:2px solid #fff;border-radius:50%;transform:translate(-50%,-50%);box-shadow:0 0 0 2px rgba(0,0,0,.5);pointer-events:none;animation:dotfade .65s forwards}@keyframes dotfade{to{opacity:0;transform:translate(-50%,-50%) scale(1.8)}}
  .browser-controls{display:flex;gap:5px;padding:7px;border-top:1px solid var(--border);align-items:center}.browser-controls button{border:1px solid var(--border);background:var(--panel);color:var(--text);border-radius:7px;padding:5px 8px;cursor:pointer;font-size:11px}.browser-controls input{flex:1;min-width:0;border:1px solid var(--border);border-radius:8px;background:var(--panel);color:var(--text);padding:6px 8px;font-size:11px;outline:none}
  .file-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(118px,1fr));gap:8px}.file-item{border:1px solid var(--border);background:var(--panel);color:var(--text);border-radius:10px;padding:10px;text-align:left;cursor:pointer;min-height:72px}.file-item:hover{background:var(--soft)}.file-item strong{display:block;font-size:12px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.file-item small{display:block;color:var(--muted);font-size:10px;margin-top:5px}.text-viewer{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;line-height:1.5;white-space:pre-wrap;word-break:break-word;margin:0}.desktop-list{display:grid;gap:7px}.desktop-list-item{border:1px solid var(--border);border-radius:9px;padding:9px;font-size:12px}.desktop-list-item small{display:block;color:var(--muted);margin-top:4px}.terminal-output{margin:0;background:#0b0d10;color:#d7e0ea;border-radius:9px;padding:11px;font:11px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;white-space:pre-wrap;min-height:210px}.terminal-line{display:flex;gap:6px;margin-top:8px}.terminal-line input{flex:1;border:1px solid var(--border);background:var(--panel);color:var(--text);border-radius:8px;padding:7px 9px;font:11px ui-monospace,SFMono-Regular,Menlo,monospace}.terminal-line button{border:1px solid var(--border);background:var(--panel);color:var(--text);border-radius:8px;padding:6px 10px;cursor:pointer}.desktop-foot{padding:7px 10px;border-top:1px solid var(--border);font-size:10px;color:var(--muted);display:flex;gap:8px}.desktop-foot .url{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1}
  .web-snapshot-card,.browser-actions-card,.browser-approval-card{width:min(680px,92vw)}.web-snapshot-card img{display:block;width:100%;max-height:520px;object-fit:contain;border-radius:11px;border:1px solid var(--border);background:#111;margin-top:10px}.web-snapshot-url{font-size:10px;color:var(--muted);margin-top:7px;overflow-wrap:anywhere}.web-snapshot-excerpt{font-size:12px;line-height:1.45;margin-top:8px;color:var(--muted)}.browser-actions-list{display:grid;gap:6px;margin-top:10px}.browser-action{padding:8px 10px;border-radius:9px;background:var(--soft);font-size:12px}.browser-approval-step{margin-top:10px;padding:10px;border-radius:10px;background:var(--soft);font-size:12px}.browser-approval-actions{display:flex;gap:7px;margin-top:10px}.browser-approval-actions button{border:1px solid var(--border);border-radius:8px;padding:6px 10px;background:var(--panel);color:var(--text);cursor:pointer}.browser-approval-actions .approve{background:var(--accent);color:var(--accent-text);border-color:var(--accent)}
  @media(max-width:760px){.agentie-desktop{width:min(100%,94vw)}.desktop-home{grid-template-columns:repeat(3,1fr);padding:16px}}
  `;document.head.appendChild(style);

  const browserIntent=t=>/https?:\/\//i.test(t)&&/\b(open|visit|check|inspect|look at|view|screenshot|snapshot|capture|monitor|watch|click|type|fill|search|scroll|press|browse|navigate)\b/i.test(t);
  const browserContinuation=t=>/^\s*(click|type|fill|scroll|press|go back|back|forward|new tab|close tab|screenshot|take a screenshot|search for)\b/i.test(t);
  const desktopIntent=t=>/\b(desktop|computer home|open (?:the )?terminal|show (?:my )?files|open (?:my )?files|file manager|open (?:my )?notes|show (?:my )?notes|open (?:my )?tasks|show (?:my )?tasks|open (?:my )?plugins|show (?:my )?plugins|run .+ (?:in|using) (?:the )?terminal)\b/i.test(t);
  let currentRow=null,currentRoot=null,currentApp='home',pollTimer=null,lastVersion=-1;

  function makeDesktop(){
    const row=document.createElement('div');row.className='assistant-row agentie-desktop-row';row.innerHTML=`<div class="agentie-desktop"><div class="desktop-head"><span class="desktop-dot"></span><button class="desktop-home-btn" title="Home">⌂</button><span class="desktop-title">Agentie Computer</span><span class="desktop-status">Ready</span><button class="desktop-stop">Stop</button></div><div class="desktop-screen"><div class="desktop-home"></div><div class="desktop-app browser-app"><div class="app-bar"><strong>Browser</strong><button data-browser="back">←</button><button data-browser="forward">→</button><button data-browser="reload">↻</button></div><div class="app-body"><img class="browser-frame" alt="Agentie browser" style="display:none"><div class="browser-placeholder">Browser is ready. Ask Agentie to open a site.</div></div><div class="browser-controls"><input class="browser-type" placeholder="Type into the focused field…"><button data-key="Enter">Enter</button><button data-key="Tab">Tab</button><button data-key="Escape">Esc</button></div></div><div class="desktop-app generic-app"><div class="app-bar"><strong class="generic-title">App</strong><button class="generic-home">⌂</button></div><div class="app-body generic-body"></div></div></div><div class="desktop-foot"><span class="url"></span><span class="detail">Agentie virtual desktop</span></div></div>`;
    return row;
  }

  function renderHome(root){
    const home=root.querySelector('.desktop-home');home.innerHTML='';const apps=[['browser','🌐','Browser'],['files','📁','Files'],['terminal','⌨️','Terminal'],['notes','📝','Notes'],['tasks','✅','Tasks'],['plugins','🔌','Plugins']];
    apps.forEach(([id,ico,label])=>{const b=document.createElement('button');b.className='desktop-icon';b.innerHTML=`<span class="ico">${ico}</span><span>${label}</span>`;b.onclick=()=>openApp(id);home.appendChild(b)});const clock=document.createElement('div');clock.className='desktop-clock';clock.innerHTML=`<strong>${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</strong><br>${new Date().toLocaleDateString()}`;home.appendChild(clock)
  }

  function placeDesktop(){
    if(!currentRow){currentRow=makeDesktop();currentRoot=currentRow.querySelector('.agentie-desktop');renderHome(currentRoot);wireDesktop(currentRoot)}
    const working=[...messages.querySelectorAll('.assistant-row')].reverse().find(x=>x.querySelector('.working'));if(working)messages.insertBefore(currentRow,working);else messages.appendChild(currentRow);window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'});return currentRoot
  }

  function showApp(name){
    if(!currentRoot)return;currentApp=name;const home=currentRoot.querySelector('.desktop-home'),browser=currentRoot.querySelector('.browser-app'),generic=currentRoot.querySelector('.generic-app');home.style.display=name==='home'?'grid':'none';browser.classList.toggle('visible',name==='browser');generic.classList.toggle('visible',!['home','browser'].includes(name));if(!['home','browser'].includes(name))currentRoot.querySelector('.generic-title').textContent=name[0].toUpperCase()+name.slice(1)
  }

  async function agentCall(message){const r=await fetch('/agent/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,agent_type:agentType?.value||'general'})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Request failed');return d}
  async function browserControl(command){try{const d=await agentCall(`Browser control: ${command}`);if(d.card?.type==='browser_approval')window.addAssistant?.(d.message||'',d.card);return d}catch(err){currentRoot.querySelector('.detail').textContent=err.message}}

  async function desktopControl(command){
    placeDesktop();try{const d=await agentCall(`Desktop control: ${command}`);if(d.card?.type==='desktop_view')applyDesktopCard(d.card);return d}catch(err){showApp('error');currentRoot.querySelector('.generic-body').textContent=err.message}
  }

  function applyDesktopCard(card){
    const app=card.app||'home';showApp(app==='file'?'file':app);const body=currentRoot.querySelector('.generic-body');if(app==='home')return;
    if(app==='files'){body.innerHTML='<div class="file-grid"></div>';const grid=body.firstChild;(card.items||[]).forEach(item=>{const b=document.createElement('button');b.className='file-item';b.innerHTML=`<strong>${item.kind==='folder'?'📁':'📄'} ${escapeHtml(item.name)}</strong><small>${item.kind==='folder'?'Folder':Math.max(1,Math.round((item.size_bytes||0)/1024))+' KB'}</small>`;if(item.kind==='file')b.onclick=()=>desktopControl(`open file ${item.name}`);grid.appendChild(b)})}
    else if(app==='file'){const f=card.file||{};body.innerHTML=f.binary?`<div class="desktop-list-item"><strong>${escapeHtml(f.name||'File')}</strong><small>Binary file · ${f.size_bytes||0} bytes</small></div>`:`<pre class="text-viewer">${escapeHtml(f.content||'')}</pre>`}
    else if(app==='terminal'){const t=card.terminal||{};body.innerHTML=`<pre class="terminal-output"></pre><div class="terminal-line"><input placeholder="Type a command…"><button>Run</button></div>`;const out=body.querySelector('.terminal-output'),ti=body.querySelector('input'),run=body.querySelector('button');out.textContent=(t.command?`$ ${t.command}\n`:'')+(t.output||'');const exec=()=>{const q=ti.value.trim();if(q){ti.value='';desktopControl(`terminal ${q}`)}};run.onclick=exec;ti.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();exec()}};setTimeout(()=>ti.focus(),0)}
    else if(app==='notes'||app==='tasks'||app==='plugins'){body.innerHTML='<div class="desktop-list"></div>';const list=body.firstChild;(card.items||[]).forEach(item=>{const el=document.createElement('div');el.className='desktop-list-item';const title=item.title||item.name||item.key||item.text||item.id||'Item',sub=item.status||item.value||item.transport||item.content||'';el.innerHTML=`<strong>${escapeHtml(title)}</strong>${sub?`<small>${escapeHtml(String(sub))}</small>`:''}`;list.appendChild(el)});if(!(card.items||[]).length)body.innerHTML='<div class="desktop-list-item">Nothing here yet.</div>'}
    else {body.textContent=card.error||'Desktop app error.'}
  }

  function escapeHtml(s){const d=document.createElement('div');d.textContent=String(s??'');return d.innerHTML}
  function openApp(id){placeDesktop();if(id==='browser'){showApp('browser');startPolling();return}desktopControl(id)}

  function showClick(stage,x,y){const dot=document.createElement('span');dot.className='browser-click-dot';dot.style.left=x+'px';dot.style.top=y+'px';stage.appendChild(dot);setTimeout(()=>dot.remove(),700)}
  function wireDesktop(root){
    root.querySelector('.desktop-home-btn').onclick=()=>showApp('home');root.querySelector('.generic-home').onclick=()=>showApp('home');root.querySelector('.desktop-stop').onclick=()=>fetch('/browser/live/stop',{method:'POST'});
    root.querySelectorAll('[data-browser]').forEach(b=>b.onclick=()=>browserControl(b.dataset.browser));root.querySelectorAll('[data-key]').forEach(b=>b.onclick=()=>browserControl(`key ${b.dataset.key}`));const type=root.querySelector('.browser-type');type.onkeydown=e=>{if(e.key==='Enter'&&type.value){e.preventDefault();const v=type.value;type.value='';browserControl(`type focused: ${v}`)}};
    const img=root.querySelector('.browser-frame'),stage=root.querySelector('.browser-app .app-body');stage.addEventListener('click',e=>{if(img.style.display==='none'||!img.naturalWidth||!img.naturalHeight)return;const rect=img.getBoundingClientRect(),rawX=e.clientX-rect.left,rawY=e.clientY-rect.top,scale=Math.min(rect.width/img.naturalWidth,rect.height/img.naturalHeight),drawW=img.naturalWidth*scale,drawH=img.naturalHeight*scale,offX=(rect.width-drawW)/2,offY=(rect.height-drawH)/2,x=rawX-offX,y=rawY-offY;if(x<0||y<0||x>drawW||y>drawH)return;showClick(stage,e.clientX-stage.getBoundingClientRect().left,e.clientY-stage.getBoundingClientRect().top);browserControl(`click at ${(x/drawW*1440).toFixed(1)},${(y/drawH*900).toFixed(1)}`)});stage.addEventListener('wheel',e=>{if(img.style.display==='none')return;e.preventDefault();browserControl(`scroll ${Math.max(-1400,Math.min(1400,e.deltaY*2)).toFixed(0)}`)},{passive:false})
  }

  async function pollBrowser(){if(!currentRoot)return;try{const r=await fetch('/browser/live/state',{cache:'no-store'});if(!r.ok)return;const s=await r.json(),dot=currentRoot.querySelector('.desktop-dot'),status=currentRoot.querySelector('.desktop-status'),url=currentRoot.querySelector('.url'),detail=currentRoot.querySelector('.detail'),img=currentRoot.querySelector('.browser-frame'),ph=currentRoot.querySelector('.browser-placeholder'),version=Number(s.frame_version||0);dot.classList.toggle('active',!!s.active);dot.classList.toggle('error',s.status==='error');status.textContent=s.active?(s.status||'Working'):(s.status==='error'?'Error':s.status==='paused'?'Paused':'Ready');url.textContent=s.url||'';detail.textContent=s.error||s.detail||'Agentie virtual desktop';if(version>0&&version!==lastVersion){lastVersion=version;img.src=`/browser/live/frame?v=${version}&t=${Date.now()}`;img.style.display='block';ph.style.display='none'}}catch(_){}}
  function startPolling(){if(!pollTimer)pollTimer=setInterval(pollBrowser,450);pollBrowser()}

  function prepareForPrompt(text){
    if(!(browserIntent(text)||browserContinuation(text)||desktopIntent(text)))return;placeDesktop();if(browserIntent(text)||browserContinuation(text)){showApp('browser');startPolling()}
  }
  send.addEventListener('click',()=>{const text=input.value.trim();if(text)prepareForPrompt(text)},true);input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){const text=input.value.trim();if(text)prepareForPrompt(text)}},true);

  function resend(text){if(!text)return;input.value=text;input.dispatchEvent(new Event('input',{bubbles:true}));send.click()}
  const previousRender=window.renderCard;if(typeof previousRender==='function')window.renderCard=function(card,message){
    if(card?.type==='desktop_view'){placeDesktop();applyDesktopCard(card);const hidden=document.createElement('span');hidden.style.display='none';return hidden}
    if(!card||!['web_snapshot','browser_actions','browser_approval'].includes(card.type))return previousRender(card,message);
    if(card.type==='browser_approval'){const wrap=document.createElement('div');wrap.className='card-wrap browser-approval-card';const el=document.createElement('div');el.className='result-card';wrap.appendChild(el);if(message){const top=document.createElement('div');top.className='card-topline';top.textContent=message;el.appendChild(top)}const title=document.createElement('div');title.className='card-title';title.textContent='🛡 Browser approval';el.appendChild(title);const u=document.createElement('div');u.className='web-snapshot-url';u.textContent=card.url||'';el.appendChild(u);const step=document.createElement('div');step.className='browser-approval-step';step.textContent=card.step||'Consequential browser action';el.appendChild(step);const actions=document.createElement('div');actions.className='browser-approval-actions';const approve=document.createElement('button'),deny=document.createElement('button');approve.className='approve';approve.textContent='Approve once';deny.textContent='Deny';actions.append(approve,deny);el.appendChild(actions);async function resolve(allowed){approve.disabled=true;deny.disabled=true;try{const r=await fetch(`/approvals/${card.approval.id}/resolve`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({approved:allowed})});if(!r.ok)throw new Error('Could not resolve approval');title.textContent=allowed?'✓ Browser action approved':'Browser action denied';actions.remove();if(allowed)setTimeout(()=>resend(card.command),80)}catch(err){approve.disabled=false;deny.disabled=false}}approve.onclick=()=>resolve(true);deny.onclick=()=>resolve(false);return wrap}
    if(card.type==='browser_actions'){placeDesktop();showApp('browser');startPolling();const wrap=document.createElement('div');wrap.className='card-wrap browser-actions-card';const el=document.createElement('div');el.className='result-card';wrap.appendChild(el);if(message){const top=document.createElement('div');top.className='card-topline';top.textContent=message;el.appendChild(top)}const title=document.createElement('div');title.className='card-title';title.textContent=`🖥 ${card.title||'Browser actions'}`;el.appendChild(title);const u=document.createElement('div');u.className='web-snapshot-url';u.textContent=card.url||'';el.appendChild(u);const list=document.createElement('div');list.className='browser-actions-list';(card.actions||[]).forEach(a=>{const row=document.createElement('div');row.className='browser-action';row.textContent=a;list.appendChild(row)});el.appendChild(list);return wrap}
    placeDesktop();showApp('browser');startPolling();const wrap=document.createElement('div');wrap.className='card-wrap web-snapshot-card';const el=document.createElement('div');el.className='result-card';wrap.appendChild(el);if(message){const top=document.createElement('div');top.className='card-topline';top.textContent=message;el.appendChild(top)}const title=document.createElement('div');title.className='card-title';title.textContent=`🌐 ${card.title||'Website snapshot'}`;el.appendChild(title);const shot=document.createElement('img');shot.src=card.image_url;shot.alt=`Screenshot of ${card.title||card.url||'website'}`;el.appendChild(shot);const u=document.createElement('div');u.className='web-snapshot-url';u.textContent=card.url||'';el.appendChild(u);const meta=document.createElement('div');meta.className='card-meta';meta.textContent=`${card.changed?'Changed':'Snapshot'}${card.captured_at?' · '+new Date(card.captured_at).toLocaleString():''}`;el.appendChild(meta);if(card.excerpt){const ex=document.createElement('div');ex.className='web-snapshot-excerpt';ex.textContent=card.excerpt;el.appendChild(ex)}return wrap
  };
})();