(() => {
  const originalRenderCard = window.renderCard;
  const style = document.createElement('style');
  style.textContent = `.card-topline{font-size:11px;color:var(--muted);margin-bottom:8px;line-height:1.35}.multi-card-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;width:min(720px,calc(100vw - 300px));margin-top:6px}.multi-card-grid .card-wrap{width:100%;margin-top:0}.multi-card-grid .result-card{height:100%;min-height:135px}.multi-card-grid .card-value{font-size:25px;margin:9px 0 5px}.multi-card-grid .card-title{font-size:13px}@media(max-width:900px){.multi-card-grid{width:min(650px,92vw)}}@media(max-width:620px){.multi-card-grid{grid-template-columns:1fr;width:min(330px,92vw)}}`;
  document.head.appendChild(style);
  const addTitle=(el,text)=>{const x=document.createElement('div');x.className='card-title';x.textContent=text;el.appendChild(x)};
  const addMeta=(el,text)=>{const x=document.createElement('div');x.className='card-meta';x.textContent=text;el.appendChild(x);return x};
  const listContainer=el=>{const x=document.createElement('div');x.style.display='grid';x.style.gap='6px';x.style.marginTop='10px';el.appendChild(x);return x};
  const row=(text,sub)=>{const x=document.createElement('div');x.className='metric';const m=document.createElement('div');m.className='metric-value';m.style.fontSize='13px';m.textContent=text;x.appendChild(m);if(sub){const s=document.createElement('div');s.className='metric-label';s.style.marginTop='3px';s.style.fontSize='10px';s.textContent=sub;x.appendChild(s)}return x};
  function renderCalculation(el,c){addTitle(el,'🧮 Calculator');const v=document.createElement('div');v.className='card-value';v.textContent=String(c.result);el.appendChild(v);addMeta(el,c.expression||'Calculation')}
  function renderConversion(el,c){addTitle(el,'↔ Unit conversion');const v=document.createElement('div');v.className='card-value';v.textContent=`${Number(c.result).toLocaleString(undefined,{maximumFractionDigits:6})} ${c.to_unit||''}`;el.appendChild(v);addMeta(el,`${c.value} ${c.from_unit||''} → ${c.to_unit||''}`)}
  function renderDateTime(el,c){addTitle(el,'🕒 Local time');const d=new Date(c.datetime),v=document.createElement('div');v.className='card-value';v.textContent=d.toLocaleTimeString();el.appendChild(v);addMeta(el,`${d.toLocaleDateString()} · ${c.timezone||'local'}`)}
  function renderReminder(el,c){addTitle(el,c.repeat_minutes>0?'🔁 Recurring reminder':'🔔 Reminder');const v=document.createElement('div');v.className='card-value';v.style.fontSize='18px';v.textContent=c.text||'Reminder';el.appendChild(v);const due=c.due_at?new Date(c.due_at).toLocaleString():'—';addMeta(el,c.repeat_minutes>0?`Next ${due} · every ${c.repeat_minutes} min`:`Due ${due}`)}
  function renderReminders(el,c){addTitle(el,'🔔 Reminders');const list=listContainer(el);(c.items||[]).forEach(i=>list.appendChild(row(i.text||'Reminder',`${i.status||''} · ${i.due_at?new Date(i.due_at).toLocaleString():''}`)));if(!(c.items||[]).length)addMeta(el,'No reminders yet.')}
  function renderTasks(el,c){addTitle(el,'✅ Tasks');const list=listContainer(el);(c.items||[]).forEach(i=>{const done=(i.steps||[]).filter(s=>s.done).length;list.appendChild(row(i.title||i.id,`${i.status||'pending'} · ${done}/${(i.steps||[]).length} steps`))});if(!(c.items||[]).length)addMeta(el,'No tasks yet.')}
  function renderFiles(el,c){addTitle(el,'📄 Workspace files');const list=listContainer(el);(c.items||[]).forEach(i=>list.appendChild(row(i.name,`${Math.max(1,Math.round((i.size_bytes||0)/1024))} KB · ${i.suffix||'file'}`)));if(!(c.items||[]).length)addMeta(el,'Workspace is empty.')}
  function renderApprovals(el,c){addTitle(el,'🛡 Approvals');const list=listContainer(el);(c.items||[]).forEach(i=>list.appendChild(row(i.action||i.id,i.reason||i.status)));if(!(c.items||[]).length)addMeta(el,'No approval requests.')}
  function renderSystem(el,c){addTitle(el,'💻 System status');const g=document.createElement('div');g.className='grid';g.innerHTML=`<div class="metric"><small>CPU</small>${c.cpu_percent??'—'}%</div><div class="metric"><small>Memory</small>${c.memory_percent??'—'}%</div><div class="metric"><small>Disk</small>${c.disk_free_gb??'—'} GB</div>`;el.appendChild(g);addMeta(el,c.hostname||'Local runtime')}
  function renderNote(el,c){addTitle(el,`📝 ${c.title||'Note'}`);const b=document.createElement('div');b.style.marginTop='9px';b.style.whiteSpace='pre-wrap';b.style.fontSize='13px';b.textContent=c.content||'';el.appendChild(b)}
  function renderRoutine(el,c){addTitle(el,`🔁 ${c.name||'Routine'}`);const v=document.createElement('div');v.style.fontSize='13px';v.style.marginTop='9px';v.textContent=c.action||'';el.appendChild(v);addMeta(el,`${c.trigger||'unscheduled'} · ${c.status||'active'} · role: ${c.agent_role||'auto'}`);if(c.duplicate_prevented)addMeta(el,'Duplicate prevented — existing routine reused.')}
  function renderRoutines(el,c){addTitle(el,'🔁 Routines');const list=listContainer(el);(c.items||[]).forEach(i=>list.appendChild(row(i.name||i.id,`${i.trigger||''} · ${i.status||''} · ${i.agent_role||'auto'}`)));if(!(c.items||[]).length)addMeta(el,'No routines yet.')}
  function renderRole(el,c){addTitle(el,`🎭 ${c.agent||'Agent'} role`);const v=document.createElement('div');v.className='card-value';v.style.fontSize='20px';v.textContent=c.name||c.base||'general';el.appendChild(v);addMeta(el,`Tool base: ${c.base||'general'}`)}
  function renderRoles(el,c){addTitle(el,'🎭 Agent roles');const list=listContainer(el);const a=c.assignments||{};Object.keys(a).forEach(k=>list.appendChild(row(k,a[k])));if(!Object.keys(a).length)addMeta(el,'All agents are using default roles.');addMeta(el,`Available: ${(c.available||[]).join(', ')}`)}
  function renderStandardExtra(card,message){const wrap=document.createElement('div');wrap.className='card-wrap';const el=document.createElement('div');el.className='result-card';wrap.appendChild(el);if(message){const t=document.createElement('div');t.className='card-topline';t.textContent=message;el.appendChild(t)}if(card.type==='calculation')renderCalculation(el,card);else if(card.type==='unit_conversion')renderConversion(el,card);else if(card.type==='datetime')renderDateTime(el,card);else if(card.type==='reminder')renderReminder(el,card);else if(card.type==='reminders')renderReminders(el,card);else if(card.type==='tasks')renderTasks(el,card);else if(card.type==='files')renderFiles(el,card);else if(card.type==='approvals')renderApprovals(el,card);else if(card.type==='system')renderSystem(el,card);else if(card.type==='note')renderNote(el,card);else if(card.type==='routine')renderRoutine(el,card);else if(card.type==='routines')renderRoutines(el,card);else if(card.type==='agent_role')renderRole(el,card);else if(card.type==='agent_roles')renderRoles(el,card);return wrap}
  window.renderCard=function(card,message){if(card.type==='multi'){const g=document.createElement('div');g.className='multi-card-grid';(card.items||[]).forEach(i=>{if(i.card)g.appendChild(window.renderCard(i.card,i.message||''))});return g}const extra=new Set(['calculation','unit_conversion','datetime','reminder','reminders','tasks','files','approvals','system','note','routine','routines','agent_role','agent_roles']);if(!extra.has(card.type))return originalRenderCard(card,message);return renderStandardExtra(card,message)};
})();
