(() => {
  const originalRenderCard = window.renderCard;
  const style = document.createElement('style');
  style.textContent = `.card-topline{font-size:11px;color:var(--muted);margin-bottom:8px;line-height:1.35}.multi-card-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;width:min(720px,calc(100vw - 300px));margin-top:6px}.multi-card-grid .card-wrap{width:100%;margin-top:0}.multi-card-grid .result-card{height:100%;min-height:135px}.multi-card-grid .card-value{font-size:25px;margin:9px 0 5px}.multi-card-grid .card-title{font-size:13px}.rag-hit,.trace-event,.memory-hit{padding:8px;border-radius:9px;background:var(--soft);font-size:12px;line-height:1.4}.rag-hit strong,.trace-event strong,.memory-hit strong{display:block;margin-bottom:4px}.rag-hit small,.trace-event small,.memory-hit small{display:block;color:var(--muted);margin-bottom:5px}.trace-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px;margin-top:9px}.trace-grid .metric{min-width:0}.browser-approval-step{margin-top:10px;padding:10px;border-radius:10px;background:var(--soft);font-size:12px}.browser-approval-actions{display:flex;gap:7px;margin-top:10px}.browser-approval-actions button{border:1px solid var(--border);border-radius:8px;padding:6px 10px;background:var(--panel);color:var(--text);cursor:pointer}.browser-approval-actions .approve{background:var(--accent);color:var(--accent-text);border-color:var(--accent)}@media(max-width:900px){.multi-card-grid{width:min(650px,92vw)}}@media(max-width:620px){.multi-card-grid{grid-template-columns:1fr;width:min(330px,92vw)}.trace-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}`;
  document.head.appendChild(style);
  const addTitle=(el,text)=>{const x=document.createElement('div');x.className='card-title';x.textContent=text;el.appendChild(x)};
  const addMeta=(el,text)=>{const x=document.createElement('div');x.className='card-meta';x.textContent=text;el.appendChild(x);return x};
  const listContainer=el=>{const x=document.createElement('div');x.style.display='grid';x.style.gap='6px';x.style.marginTop='10px';el.appendChild(x);return x};
  const row=(text,sub)=>{const x=document.createElement('div');x.className='metric';const m=document.createElement('div');m.className='metric-value';m.style.fontSize='13px';m.textContent=text;x.appendChild(m);if(sub){const s=document.createElement('div');s.className='metric-label';s.style.marginTop='3px';s.style.fontSize='10px';s.textContent=sub;x.appendChild(s)}return x};
  const metric=(label,value)=>`<div class="metric"><small>${label}</small>${value}</div>`;
  function renderCalculation(el,c){addTitle(el,'🧮 Calculator');const v=document.createElement('div');v.className='card-value';v.textContent=String(c.result);el.appendChild(v);addMeta(el,c.expression||'Calculation')}
  function renderConversion(el,c){addTitle(el,'↔ Unit conversion');const v=document.createElement('div');v.className='card-value';v.textContent=`${Number(c.result).toLocaleString(undefined,{maximumFractionDigits:6})} ${c.to_unit||''}`;el.appendChild(v);addMeta(el,`${c.value} ${c.from_unit||''} → ${c.to_unit||''}`)}
  function renderDateTime(el,c){addTitle(el,'🕒 Local time');const d=new Date(c.datetime),v=document.createElement('div');v.className='card-value';v.textContent=d.toLocaleTimeString();el.appendChild(v);addMeta(el,`${d.toLocaleDateString()} · ${c.timezone||'local'}`)}
  function renderReminder(el,c){addTitle(el,c.repeat_minutes>0?'🔁 Recurring reminder':'🔔 Reminder');const v=document.createElement('div');v.className='card-value';v.style.fontSize='18px';v.textContent=c.text||'Reminder';el.appendChild(v);const due=c.due_at?new Date(c.due_at).toLocaleString():'—';addMeta(el,c.repeat_minutes>0?`Next ${due} · every ${c.repeat_minutes} min`:`Due ${due}`)}
  function renderReminders(el,c){addTitle(el,'🔔 Reminders');const list=listContainer(el);(c.items||[]).forEach(i=>list.appendChild(row(i.text||'Reminder',`${i.status||''} · ${i.due_at?new Date(i.due_at).toLocaleString():''}`)));if(!(c.items||[]).length)addMeta(el,'No reminders yet.')}
  function renderTasks(el,c){addTitle(el,'✅ Tasks');const list=listContainer(el);(c.items||[]).forEach(i=>{const done=(i.steps||[]).filter(s=>s.done).length;list.appendChild(row(i.title||i.id,`${i.status||'pending'} · ${done}/${(i.steps||[]).length} steps`))});if(!(c.items||[]).length)addMeta(el,'No tasks yet.')}
  function renderFiles(el,c){addTitle(el,'📄 Workspace files');const list=listContainer(el);(c.items||[]).forEach(i=>list.appendChild(row(i.name,`${Math.max(1,Math.round((i.size_bytes||0)/1024))} KB · ${i.suffix||'file'}`)));if(!(c.items||[]).length)addMeta(el,'Workspace is empty.')}
  function renderApprovals(el,c){
    addTitle(el,'🛡 Approval');
    (c.items||[]).forEach((i,index)=>{
      if(index>0){const divider=document.createElement('div');divider.style.height='1px';divider.style.background='var(--border)';divider.style.margin='12px 0';el.appendChild(divider)}
      const step=document.createElement('div');step.className='browser-approval-step';step.textContent=i.reason||i.action||'Consequential action';el.appendChild(step);
      if(i.status==='pending'){
        const actions=document.createElement('div');actions.className='browser-approval-actions';
        const approve=document.createElement('button');approve.type='button';approve.className='approve';approve.textContent='Approve once';approve.dataset.approvalId=i.id;
        const deny=document.createElement('button');deny.type='button';deny.textContent='Deny';deny.dataset.denialId=i.id;
        const resolve=async approved=>{approve.disabled=deny.disabled=true;try{const r=await fetch(`/approvals/${encodeURIComponent(i.id)}/resolve`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({approved})});if(!r.ok)throw new Error('Could not resolve approval');step.textContent=approved?'✓ Approved':'Denied';actions.remove();if(approved&&i.metadata?.kind==='agent_delete'&&typeof window.loadPersistentAgents==='function')setTimeout(()=>window.loadPersistentAgents(),80)}catch(_){approve.disabled=deny.disabled=false}};
        approve.onclick=()=>resolve(true);deny.onclick=()=>resolve(false);actions.append(approve,deny);el.appendChild(actions)
      }else addMeta(el,i.status||'resolved')
    });
    if(!(c.items||[]).length)addMeta(el,'No approval requests.')
  }
  function renderSystem(el,c){addTitle(el,'💻 System status');const g=document.createElement('div');g.className='grid';g.innerHTML=metric('CPU',`${c.cpu_percent??'—'}%`)+metric('Memory',`${c.memory_percent??'—'}%`)+metric('Disk',`${c.disk_free_gb??'—'} GB`);el.appendChild(g);addMeta(el,c.hostname||'Local runtime')}
  function renderNote(el,c){addTitle(el,`📝 ${c.title||'Note'}`);const b=document.createElement('div');b.style.marginTop='9px';b.style.whiteSpace='pre-wrap';b.style.fontSize='13px';b.textContent=c.content||'';el.appendChild(b)}
  function renderMemory(el,c){addTitle(el,`🧠 ${c.key||'Memory'}`);const b=document.createElement('div');b.style.marginTop='9px';b.style.whiteSpace='pre-wrap';b.style.fontSize='13px';b.textContent=c.value||'';el.appendChild(b);addMeta(el,c.scope||'persistent')}
  function renderMemories(el,c){addTitle(el,'🧠 Persistent memory');const list=listContainer(el);(c.items||[]).forEach(i=>list.appendChild(row(i.key||'memory',i.value||'')));if(!(c.items||[]).length)addMeta(el,'No saved memories.')}
  function renderSemanticMemory(el,c){addTitle(el,'🧠 Memory search');addMeta(el,`${c.query||''} · ${c.backend||'local'} embeddings`);const list=listContainer(el);(c.hits||[]).forEach((h,i)=>{const x=document.createElement('div');x.className='memory-hit';const strong=document.createElement('strong');strong.textContent=`M${i+1} · ${h.kind||'memory'}`;const small=document.createElement('small');small.textContent=`score ${h.score??'—'} · semantic ${h.semantic_score??'—'}`;const body=document.createElement('div');body.textContent=(h.text||'').slice(0,650);x.append(strong,small,body);list.appendChild(x)});if(!(c.hits||[]).length)addMeta(el,'No relevant memory found.')}
  function renderRoutine(el,c){addTitle(el,`🔁 ${c.name||'Routine'}`);const v=document.createElement('div');v.style.fontSize='13px';v.style.marginTop='9px';v.textContent=c.action||'';el.appendChild(v);addMeta(el,`${c.trigger||'unscheduled'} · ${c.status||'active'} · role: ${c.agent_role||'auto'}`);if(c.duplicate_prevented)addMeta(el,'Duplicate prevented — existing routine reused.')}
  function renderRoutines(el,c){addTitle(el,'🔁 Routines');const list=listContainer(el);(c.items||[]).forEach(i=>list.appendChild(row(i.name||i.id,`${i.trigger||''} · ${i.status||''} · ${i.agent_role||'auto'}`)));if(!(c.items||[]).length)addMeta(el,'No routines yet.')}
  function renderRole(el,c){addTitle(el,`🎭 ${c.agent||'Agent'} role`);const v=document.createElement('div');v.className='card-value';v.style.fontSize='20px';v.textContent=c.name||c.base||'general';el.appendChild(v);addMeta(el,`Tool base: ${c.base||'general'}`)}
  function renderRoles(el,c){addTitle(el,'🎭 Agent roles');const list=listContainer(el);const a=c.assignments||{};Object.keys(a).forEach(k=>list.appendChild(row(k,a[k])));if(!Object.keys(a).length)addMeta(el,'All agents are using default roles.');addMeta(el,`Available: ${(c.available||[]).join(', ')}`)}
  function renderCollection(el,c){addTitle(el,`📚 ${c.name||c.collection||'Collection'}`);addMeta(el,c.description||`${c.chunks||0} chunks · ${c.filename||''}`);if(c.embedding_backend)addMeta(el,`Embeddings: ${c.embedding_backend}`);if(c.duplicate_prevented)addMeta(el,'Existing collection reused.')}
  function renderCollections(el,c){addTitle(el,'📚 Collections');const list=listContainer(el);(c.items||[]).forEach(i=>list.appendChild(row(i.name||i.id,`${i.document_count||0} document(s)`)));if(!(c.items||[]).length)addMeta(el,'No collections yet.')}
  function renderCollectionSearch(el,c){addTitle(el,`🔎 ${c.collection?.name||'Collection search'}`);addMeta(el,`${c.query||''} · ${c.retrieval||'hybrid'} · ${c.embedding_backend||'local'}`);const list=listContainer(el);(c.hits||[]).forEach(h=>{const x=document.createElement('div');x.className='rag-hit';const strong=document.createElement('strong');strong.textContent=`${h.id} · ${h.filename}`;const small=document.createElement('small');small.textContent=`score ${h.score} · semantic ${h.semantic_score??'—'} · lexical ${h.lexical_score??'—'}`;const body=document.createElement('div');body.textContent=(h.text||'').slice(0,700);x.append(strong,small,body);list.appendChild(x)});if(!(c.hits||[]).length)addMeta(el,'No relevant passages found.')}
  function renderSkills(el,c){addTitle(el,'🧩 Skills');const list=listContainer(el);(c.items||[]).forEach(i=>list.appendChild(row(`${i.enabled?'✓':'○'} ${i.name||i.id}`,`${(i.agents||[]).join(', ')} · ${(i.capabilities||[]).join(', ')}`)));if(!(c.items||[]).length)addMeta(el,'No registered skills.')}
  function renderSkill(el,c){addTitle(el,`🧩 ${c.name||c.id}`);addMeta(el,`${c.enabled?'enabled':'disabled'} · agents: ${(c.agents||[]).join(', ')}`);addMeta(el,(c.capabilities||[]).join(', '))}
  function costText(v){return v===null||v===undefined?'price not configured':`$${Number(v).toFixed(6)}`}
  function renderObservability(el,c){addTitle(el,`🔬 Trace ${c.id||''}`);addMeta(el,`${c.routed_by||'unrouted'} · ${c.agent_type||'general'} · ${c.status||''}`);const g=document.createElement('div');g.className='trace-grid';g.innerHTML=metric('Latency',c.latency_ms==null?'—':`${Math.round(c.latency_ms)} ms`)+metric('Provider calls',c.provider_calls||0)+metric('Tokens',c.total_tokens||0)+metric('Input',c.input_tokens||0)+metric('Output',c.output_tokens||0)+metric('Cost',costText(c.estimated_cost_usd));el.appendChild(g);if(c.error)addMeta(el,`Error: ${c.error}`);const events=c.events||[];if(events.length){const list=listContainer(el);events.forEach(e=>{const x=document.createElement('div');x.className='trace-event';const strong=document.createElement('strong');strong.textContent=`${e.kind} · ${e.name||''}`;const small=document.createElement('small');small.textContent=`${e.status||'ok'}${e.latency_ms!=null?` · ${Math.round(e.latency_ms)} ms`:''}`;const body=document.createElement('div');const m=e.metadata||{};body.textContent=m.total_tokens!=null?`${m.total_tokens} tokens${m.estimated_cost_usd!=null?` · $${Number(m.estimated_cost_usd).toFixed(6)}`:''}`:(m.card_type||m.item_type||m.error||'');x.append(strong,small,body);list.appendChild(x)})}}
  function renderObservabilitySummary(el,c){addTitle(el,'📊 Agentie usage');const g=document.createElement('div');g.className='trace-grid';g.innerHTML=metric('Requests',c.requests||0)+metric('Provider calls',c.provider_calls||0)+metric('Tokens',c.tokens||0)+metric('Known cost',`$${Number(c.known_cost_usd||0).toFixed(6)}`)+metric('Unknown priced',c.unknown_cost_requests||0);el.appendChild(g);const list=listContainer(el);(c.items||[]).slice(0,10).forEach(i=>list.appendChild(row(`${i.routed_by||'unrouted'} · ${i.id}`,`${Math.round(i.latency_ms||0)} ms · ${i.provider_calls||0} provider · ${i.total_tokens||0} tokens`)))}
  function renderStandardExtra(card,message){const wrap=document.createElement('div');wrap.className='card-wrap';const el=document.createElement('div');el.className='result-card';wrap.appendChild(el);if(message){const t=document.createElement('div');t.className='card-topline';t.textContent=message;el.appendChild(t)}const map={calculation:renderCalculation,unit_conversion:renderConversion,datetime:renderDateTime,reminder:renderReminder,reminders:renderReminders,tasks:renderTasks,files:renderFiles,approvals:renderApprovals,system:renderSystem,note:renderNote,memory:renderMemory,memories:renderMemories,semantic_memory:renderSemanticMemory,routine:renderRoutine,routines:renderRoutines,agent_role:renderRole,agent_roles:renderRoles,collection:renderCollection,collection_index:renderCollection,collections:renderCollections,collection_search:renderCollectionSearch,skills:renderSkills,skill:renderSkill,observability:renderObservability,observability_summary:renderObservabilitySummary};(map[card.type]||(()=>{}))(el,card);return wrap}
  window.renderCard=function(card,message){if(card.type==='multi'){const g=document.createElement('div');g.className='multi-card-grid';(card.items||[]).forEach(i=>{if(i.card)g.appendChild(window.renderCard(i.card,i.message||''))});return g}const extra=new Set(['calculation','unit_conversion','datetime','reminder','reminders','tasks','files','approvals','system','note','memory','memories','semantic_memory','routine','routines','agent_role','agent_roles','collection','collection_index','collections','collection_search','skills','skill','observability','observability_summary']);if(!extra.has(card.type))return originalRenderCard(card,message);return renderStandardExtra(card,message)};
})();