(()=>{
  if(window.__agentieModelRouterUI)return;window.__agentieModelRouterUI=true;
  const css=document.createElement('style');css.textContent=`
  .model-router-control{margin-top:8px;border:1px solid var(--border);border-radius:11px;background:var(--soft);padding:10px}
  .model-router-head{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:7px;font-size:10px;color:var(--muted)}.model-router-head b{font-size:11px;color:var(--text)}
  .model-router-modes{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.model-router-mode{border:1px solid var(--border);border-radius:8px;background:var(--panel);color:var(--text);padding:7px 4px;font-size:10px;cursor:pointer}.model-router-mode.active{background:#0b84ff;color:#fff;border-color:#0b84ff}.model-router-mode:disabled{opacity:.55;cursor:default}.model-router-detail{font-size:9px;color:var(--muted);line-height:1.4;margin-top:7px;white-space:normal}
  .agentie-profile-wrap{position:relative;margin-top:7px}.agentie-profile-button{width:100%;display:flex;align-items:center;gap:9px;border:1px solid var(--border);background:transparent;color:var(--text);border-radius:10px;padding:7px 9px;cursor:pointer;text-align:left}.agentie-profile-button:hover{background:var(--soft)}.agentie-profile-icon{width:27px;height:27px;border-radius:50%;display:grid;place-items:center;background:var(--soft);border:1px solid var(--border);flex:none}.agentie-profile-icon svg{width:15px;height:15px;stroke:currentColor}.agentie-profile-copy{min-width:0;flex:1}.agentie-profile-copy strong,.agentie-profile-copy small{display:block}.agentie-profile-copy strong{font-size:11px}.agentie-profile-copy small{font-size:9px;color:var(--muted);margin-top:1px}.agentie-profile-menu{position:absolute;left:0;right:0;bottom:calc(100% + 6px);z-index:13050;border:1px solid var(--border);border-radius:11px;background:var(--panel);padding:5px;box-shadow:0 16px 42px rgba(0,0,0,.24);display:none}.agentie-profile-menu.open{display:grid}.agentie-profile-menu button{border:0;background:transparent;color:var(--text);border-radius:8px;text-align:left;padding:8px 9px;font-size:10px;cursor:pointer}.agentie-profile-menu button:hover{background:var(--soft)}
  .agentie-settings-overlay,.agentie-groups-overlay{position:fixed;inset:0;z-index:16000;background:rgba(0,0,0,.46);display:grid;place-items:center;padding:18px}.agentie-settings-panel,.agentie-groups-panel{width:min(460px,100%);max-height:88vh;overflow:auto;border:1px solid var(--border);border-radius:16px;background:var(--panel);padding:16px;box-shadow:0 22px 70px rgba(0,0,0,.3)}.agentie-settings-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.agentie-settings-head h3{margin:0;font-size:16px}.agentie-settings-close{border:0;background:transparent;color:var(--muted);font-size:22px;cursor:pointer}.agentie-settings-section{margin-top:14px;padding-top:12px;border-top:1px solid var(--border)}.agentie-settings-label{font-size:10px;text-transform:uppercase;letter-spacing:.06em;color:var(--muted);margin-bottom:7px}
  .sidebar-group-row{grid-template-columns:38px minmax(0,1fr)!important}.sidebar-group-row.active{background:var(--soft)}.group-avatar-stack{position:relative;width:38px;height:34px;flex:none}.group-avatar-head{position:absolute;width:24px;height:24px;border-radius:50%;border:2px solid var(--panel);display:grid;place-items:center;font-size:7px;font-weight:800;color:#111;box-shadow:0 1px 4px rgba(0,0,0,.18)}.group-avatar-head:nth-child(1){left:0;top:5px}.group-avatar-head:nth-child(2){left:10px;top:0}.group-avatar-head:nth-child(3){left:14px;top:10px}.group-list-label{font-size:9px;color:var(--muted);padding:9px 5px 3px;text-transform:uppercase;letter-spacing:.05em}
  .group-main-head{display:flex;align-items:center;gap:10px;margin:2px 0 18px;padding-bottom:13px;border-bottom:1px solid var(--border)}.group-main-copy strong,.group-main-copy small{display:block}.group-main-copy strong{font-size:14px}.group-main-copy small{font-size:10px;color:var(--muted);margin-top:2px}.group-msg-wrap{max-width:min(680px,88%)}.group-msg-author{font-size:10px;font-weight:700;color:var(--muted);margin:0 0 3px 2px}.group-msg-time{font-size:9px;color:var(--muted);font-weight:400;margin-left:5px}.group-main-presence{display:flex;gap:4px;flex-wrap:wrap;margin-top:4px}.group-presence-dot{width:6px;height:6px;border-radius:50%;background:#9ca3af;display:inline-block;margin-right:3px}.group-presence-dot.working{background:#22c55e}.group-presence-dot.queued{background:#f59e0b}.group-presence-chip{font-size:8px;color:var(--muted)}
  .agentie-at-menu{position:fixed;z-index:17000;width:min(340px,calc(100vw - 24px));max-height:330px;overflow:auto;border:1px solid var(--border);border-radius:12px;background:var(--panel);box-shadow:0 18px 55px rgba(0,0,0,.28);padding:6px;display:none}.agentie-at-menu.open{display:block}.agentie-at-section{font-size:8px;text-transform:uppercase;letter-spacing:.06em;color:var(--muted);padding:7px 8px 4px}.agentie-at-item{width:100%;display:flex;align-items:center;gap:8px;border:0;background:transparent;color:var(--text);border-radius:8px;padding:7px 8px;text-align:left;cursor:pointer}.agentie-at-item:hover,.agentie-at-item.selected{background:var(--soft)}.agentie-at-orb{width:24px;height:24px;border-radius:50%;display:grid;place-items:center;font-size:7px;font-weight:800;color:#111;flex:none}.agentie-at-copy{min-width:0;flex:1}.agentie-at-copy strong,.agentie-at-copy small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.agentie-at-copy strong{font-size:10px}.agentie-at-copy small{font-size:8px;color:var(--muted);margin-top:1px}.agentie-at-nav-icon{width:24px;height:24px;border-radius:7px;background:var(--soft);display:grid;place-items:center;flex:none;font-size:12px}
  .agentie-new-group{display:grid;gap:9px}.agentie-new-group input[type=text]{width:100%;border:1px solid var(--border);border-radius:9px;background:var(--soft);color:var(--text);padding:9px}.agentie-new-group-picks{display:grid;gap:5px;max-height:260px;overflow:auto}.agentie-new-group-pick{display:flex;align-items:center;gap:7px;padding:7px;border:1px solid var(--border);border-radius:9px;background:var(--soft);font-size:10px}.agentie-new-group-actions{display:flex;justify-content:flex-end;gap:7px;margin-top:5px}.agentie-new-group-actions button{border:1px solid var(--border);border-radius:8px;background:var(--panel);color:var(--text);padding:7px 10px;cursor:pointer}.agentie-new-group-actions .primary{background:#0b84ff;color:#fff;border-color:#0b84ff}
  `;document.head.appendChild(css);

  const COLORS=['#ff6b6b','#ffd166','#06d6a0','#4cc9f0','#5e60ce','#c77dff','#f72585','#fb8500'];
  const esc=v=>{const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML};
  const initials=n=>String(n||'A').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
  const colorFor=v=>{let n=0;for(const ch of String(v||''))n=(n*31+ch.charCodeAt(0))>>>0;return COLORS[n%COLORS.length]};
  async function api(url,options={}){const r=await fetch(url,options),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||d.message||'Request failed');return d}

  function label(mode){return mode==='local'?'Local':mode==='powerful'?'Powerful':'Auto'}
  function detailText(state){const local=state.local||{},cloud=state.powerful||{};const localState=local.available===true?'local ready':local.available===false?'local offline':'local not checked';const cloudState=cloud.configured?`${cloud.provider||'cloud'} ready`:`${cloud.provider||'cloud'} not configured`;if(state.mode==='local')return `${local.model||'local model'} · ${localState} · cloud fallback off`;if(state.mode==='powerful')return `${cloud.provider||'powerful'} · ${cloudState}`;return `${local.model||'local model'} first · ${localState} · escalates when needed`}
  async function refresh(control,verify=false){try{const state=await api(`/platform/model-routing/status?verify=${verify?'true':'false'}`,{cache:'no-store'});control.dataset.mode=state.mode||'auto';for(const b of control.querySelectorAll('.model-router-mode'))b.classList.toggle('active',b.dataset.mode===state.mode);control.querySelector('[data-current]').textContent=label(state.mode||'auto');control.querySelector('.model-router-detail').textContent=detailText(state);return state}catch(e){control.querySelector('.model-router-detail').textContent=e.message;return null}}
  async function setMode(control,mode){for(const b of control.querySelectorAll('.model-router-mode'))b.disabled=true;try{await api('/platform/model-routing/mode',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode})});await refresh(control,true)}catch(e){control.querySelector('.model-router-detail').textContent=e.message}finally{for(const b of control.querySelectorAll('.model-router-mode'))b.disabled=false}}
  function createModelControl(){const control=document.createElement('div');control.className='model-router-control';control.innerHTML=`<div class="model-router-head"><b>AI model</b><span data-current>Auto</span></div><div class="model-router-modes">${['local','auto','powerful'].map(m=>`<button type="button" class="model-router-mode" data-mode="${m}">${label(m)}</button>`).join('')}</div><div class="model-router-detail">Checking model routing…</div>`;for(const b of control.querySelectorAll('.model-router-mode'))b.onclick=()=>setMode(control,b.dataset.mode);refresh(control,true);return control}
  window.__agentieMountModelRouter=container=>{if(!container)return null;let control=container.querySelector('.model-router-control');if(!control){control=createModelControl();container.appendChild(control)}return control};

  function clickSidebarAction(name){const target=[...document.querySelectorAll('.sidebar button,.sidebar [role=button]')].find(x=>String(x.textContent||'').trim().toLowerCase()===name.toLowerCase()||String(x.textContent||'').trim().toLowerCase().startsWith(name.toLowerCase()));if(target){target.click();return true}return false}
  function hideOldLaunchers(){for(const el of document.querySelectorAll('.sidebar .n4-launch,.sidebar .platform-chats-launch,.sidebar .platform-activity-launch,.sidebar .pa-automation-launch')){const t=String(el.textContent||'').trim().toLowerCase();if(t.includes('agent chat')||t==='activity'||t==='automation')el.style.display='none'}document.querySelector('.sidebar .model-router-control')?.remove()}
  function profileSvg(){return '<svg viewBox="0 0 24 24" fill="none" stroke-width="1.8"><circle cx="12" cy="8" r="3.5"></circle><path d="M5.5 19c.7-3.4 3.1-5.2 6.5-5.2s5.8 1.8 6.5 5.2"></path></svg>'}
  function openSettings(){document.querySelector('.agentie-settings-overlay')?.remove();const o=document.createElement('div');o.className='agentie-settings-overlay';const p=document.createElement('div');p.className='agentie-settings-panel';p.innerHTML='<div class="agentie-settings-head"><h3>Settings</h3><button class="agentie-settings-close" type="button">×</button></div><div class="agentie-settings-section"><div class="agentie-settings-label">AI model</div><div data-model-slot></div></div>';o.appendChild(p);document.body.appendChild(o);const close=()=>o.remove();p.querySelector('.agentie-settings-close').onclick=close;o.onclick=e=>{if(e.target===o)close()};window.__agentieMountModelRouter?.(p.querySelector('[data-model-slot]'))}
  function installProfile(){const sidebar=document.querySelector('.sidebar');if(!sidebar)return;let wrap=sidebar.querySelector('.agentie-profile-wrap');if(wrap)return;const plugin=document.getElementById('agentiePluginsButton')||[...sidebar.querySelectorAll('button')].find(x=>String(x.textContent||'').trim().toLowerCase().startsWith('plugins'));if(!plugin)return;wrap=document.createElement('div');wrap.className='agentie-profile-wrap';wrap.innerHTML=`<button class="agentie-profile-button" type="button"><span class="agentie-profile-icon">${profileSvg()}</span><span class="agentie-profile-copy"><strong>Profile</strong><small>Settings & activity</small></span></button><div class="agentie-profile-menu"><button type="button" data-profile-action="settings">⚙ Settings</button><button type="button" data-profile-action="activity">◷ Activity</button><button type="button" data-profile-action="automation">↻ Automation</button></div>`;plugin.insertAdjacentElement('afterend',wrap);const btn=wrap.querySelector('.agentie-profile-button'),menu=wrap.querySelector('.agentie-profile-menu');btn.onclick=e=>{e.stopPropagation();menu.classList.toggle('open')};wrap.querySelector('[data-profile-action=settings]').onclick=()=>{menu.classList.remove('open');openSettings()};wrap.querySelector('[data-profile-action=activity]').onclick=()=>{menu.classList.remove('open');clickSidebarAction('Activity')};wrap.querySelector('[data-profile-action=automation]').onclick=()=>{menu.classList.remove('open');clickSidebarAction('Automation')};document.addEventListener('click',e=>{if(!wrap.contains(e.target))menu.classList.remove('open')})}

  let groups=[];let activeGroup=null;let groupLoading=false;
  function avatarStack(names,ids=[]){const stack=document.createElement('div');stack.className='group-avatar-stack';(names||[]).slice(0,3).forEach((name,i)=>{const h=document.createElement('span');h.className='group-avatar-head';h.style.background=colorFor(ids[i]||name);h.textContent=initials(name).slice(0,1);stack.appendChild(h)});return stack}
  async function loadGroups(){try{const d=await api('/platform/agent-chats',{cache:'no-store'});groups=d.items||[];renderGroups();return groups}catch(_){return groups}}
  function renderGroups(){const list=document.getElementById('persistentAgentList');if(!list)return;list.querySelectorAll('.sidebar-group-row,.group-list-label').forEach(x=>x.remove());if(!groups.length)return;const label=document.createElement('div');label.className='group-list-label';label.textContent='Group chats';label.style.order='20000';list.appendChild(label);let order=20001;for(const g of groups){const row=document.createElement('div');row.className='agent-row sidebar-group-row'+(activeGroup?.id===g.id?' active':'');row.dataset.groupId=g.id;row.style.order=String(order++);row.appendChild(avatarStack(g.participants||[],g.participant_ids||[]));const copy=document.createElement('div');copy.className='agent-copy';copy.innerHTML=`<strong>${esc(g.name)}</strong><small>${esc((g.participants||[]).join(' · '))}</small>`;row.appendChild(copy);row.onclick=()=>openGroupChat(g.id);list.appendChild(row)}}
  function exitGroupMode(){activeGroup=null;window.__agentieActiveGroupChat=null;const input=document.getElementById('messageInput');if(input)input.placeholder='Message Agentie...';renderGroups()}
  document.addEventListener('click',e=>{if(e.target.closest?.('#persistentAgentList .agent-row:not(.sidebar-group-row)'))exitGroupMode()},true);
  function compactMarkdown(text){let v=String(text||'');v=v.replace(/^\s*#{1,6}\s+/gm,'').replace(/\*\*([^*]+)\*\*/g,'$1').replace(/__([^_]+)__/g,'$1').replace(/`([^`]+)`/g,'$1').replace(/^\s*[-*+]\s+/gm,'• ');return v.trim()}
  function groupHeader(d){const head=document.createElement('div');head.className='group-main-head';head.appendChild(avatarStack(d.participants||[],d.participant_ids||[]));const copy=document.createElement('div');copy.className='group-main-copy';const strong=document.createElement('strong');strong.textContent=d.name||'Group chat';const small=document.createElement('small');small.textContent=(d.participants||[]).join(' · ');copy.append(strong,small);if((d.presence||[]).length){const ps=document.createElement('div');ps.className='group-main-presence';for(const x of d.presence){const chip=document.createElement('span');chip.className='group-presence-chip';chip.innerHTML=`<span class="group-presence-dot ${esc(x.status||'')}"></span>${esc(x.agent_name||'Agent')} ${esc(x.status||'idle')}`;ps.appendChild(chip)}copy.appendChild(ps)}head.appendChild(copy);return head}
  function renderGroupMain(d){if(!activeGroup||activeGroup.id!==d.id)return;activeGroup=d;window.__agentieActiveGroupChat=d;const box=document.getElementById('messages');if(!box)return;const nearBottom=(document.documentElement.scrollHeight-window.scrollY-window.innerHeight)<180;box.replaceChildren();box.appendChild(groupHeader(d));for(const m of d.messages||[]){const isUser=String(m.sender_type||'')==='user';const row=document.createElement('div');row.className=isUser?'user-row':'assistant-row';const wrap=document.createElement('div');wrap.className='group-msg-wrap';if(!isUser){const meta=document.createElement('div');meta.className='group-msg-author';meta.textContent=m.sender_name||'Agent';if(m.at){const time=document.createElement('span');time.className='group-msg-time';time.textContent=String(m.at).replace('T',' ').slice(0,19);meta.appendChild(time)}wrap.appendChild(meta)}const bubble=document.createElement('div');bubble.className='bubble '+(isUser?'user':'assistant');bubble.textContent=isUser?String(m.message||''):compactMarkdown(m.message||'');wrap.appendChild(bubble);row.appendChild(wrap);box.appendChild(row)}if(nearBottom)window.scrollTo({top:document.body.scrollHeight,behavior:'auto'})}
  async function refreshActiveGroup(){if(!activeGroup||groupLoading)return;groupLoading=true;try{const d=await api(`/platform/agent-chats/${encodeURIComponent(activeGroup.id)}`,{cache:'no-store'});renderGroupMain(d)}catch(_){ }finally{groupLoading=false}}
  async function openGroupChat(id){try{window.selectPersistentAgent?.(null)}catch(_){ }const d=await api(`/platform/agent-chats/${encodeURIComponent(id)}`,{cache:'no-store'});activeGroup=d;window.__agentieActiveGroupChat=d;renderGroups();renderGroupMain(d);const input=document.getElementById('messageInput');if(input){input.placeholder=`Message ${d.name}...`;input.focus()}}
  window.__agentieOpenGroupChat=openGroupChat;
  async function sendGroupMessage(){if(!activeGroup)return false;const input=document.getElementById('messageInput');const value=input?.value.trim();if(!value)return true;input.value='';input.dispatchEvent(new Event('input',{bubbles:true}));await api(`/platform/agent-chats/${encodeURIComponent(activeGroup.id)}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:value})});await refreshActiveGroup();return true}
  document.addEventListener('click',e=>{if(!activeGroup)return;const b=e.target.closest?.('#sendButton');if(!b)return;e.preventDefault();e.stopImmediatePropagation();sendGroupMessage()},true);
  document.addEventListener('keydown',e=>{if(!activeGroup||e.target?.id!=='messageInput')return;if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();e.stopImmediatePropagation();sendGroupMessage()}},true);

  function modalBase(cls,title){const o=document.createElement('div');o.className=cls;const p=document.createElement('div');p.className=cls==='agentie-groups-overlay'?'agentie-groups-panel':'agentie-settings-panel';p.innerHTML=`<div class="agentie-settings-head"><h3>${esc(title)}</h3><button type="button" class="agentie-settings-close">×</button></div>`;o.appendChild(p);document.body.appendChild(o);const close=()=>o.remove();p.querySelector('.agentie-settings-close').onclick=close;o.onclick=e=>{if(e.target===o)close()};return{overlay:o,panel:p,close}}
  async function newGroupDialog(){const agents=(await api('/platform/agents',{cache:'no-store'})).items||[];const {panel,close}=modalBase('agentie-groups-overlay','New group chat');const form=document.createElement('div');form.className='agentie-new-group';form.innerHTML='<input type="text" data-name placeholder="Group name"><div class="agentie-new-group-picks"></div><div class="agentie-new-group-actions"><button type="button" data-cancel>Cancel</button><button type="button" class="primary" data-create>Create</button></div><div class="model-router-detail" data-status></div>';panel.appendChild(form);const picks=form.querySelector('.agentie-new-group-picks');for(const a of agents){const l=document.createElement('label');l.className='agentie-new-group-pick';l.innerHTML=`<input type="checkbox" value="${esc(a.id)}"><span class="agentie-at-orb" style="background:${colorFor(a.id)}">${esc(initials(a.name))}</span><span>${esc(a.name)} · ${esc(a.job||'')}</span>`;picks.appendChild(l)}form.querySelector('[data-cancel]').onclick=close;form.querySelector('[data-create]').onclick=async()=>{const name=form.querySelector('[data-name]').value.trim(),selected=[...picks.querySelectorAll('input:checked')].map(x=>x.value),status=form.querySelector('[data-status]');if(!name){status.textContent='Give the group a name.';return}if(selected.length<2){status.textContent='Select at least two agents.';return}try{const d=await api('/platform/agent-chats',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,participants:selected})});close();await loadGroups();await openGroupChat(d.id)}catch(e){status.textContent=e.message}}}
  async function openGroupDirectory(){await loadGroups();const {panel,close}=modalBase('agentie-groups-overlay','Agent chats');const actions=document.createElement('div');actions.className='agentie-new-group-actions';const add=document.createElement('button');add.type='button';add.className='primary';add.textContent='New group chat';add.onclick=()=>{close();newGroupDialog()};actions.appendChild(add);panel.appendChild(actions);const list=document.createElement('div');list.style.marginTop='10px';for(const g of groups){const b=document.createElement('button');b.type='button';b.className='agentie-at-item';b.appendChild(avatarStack(g.participants||[],g.participant_ids||[]));const c=document.createElement('span');c.className='agentie-at-copy';c.innerHTML=`<strong>${esc(g.name)}</strong><small>${esc((g.participants||[]).join(' · '))}</small>`;b.appendChild(c);b.onclick=()=>{close();openGroupChat(g.id)};list.appendChild(b)}if(!groups.length){const empty=document.createElement('div');empty.className='model-router-detail';empty.textContent='No group chats yet.';list.appendChild(empty)}panel.appendChild(list)}

  let atMenu=null,atItems=[],atIndex=0;
  function ensureAtMenu(){if(atMenu)return atMenu;atMenu=document.createElement('div');atMenu.className='agentie-at-menu';document.body.appendChild(atMenu);return atMenu}
  function closeAt(){if(atMenu)atMenu.classList.remove('open');atItems=[];atIndex=0}
  function atToken(input){const before=input.value.slice(0,input.selectionStart);const m=before.match(/(^|\s)@([^\s@]*)$/);return m?{query:m[2]||'',start:before.length-(m[2]||'').length-1,end:input.selectionStart}:null}
  function replaceAt(input,value){const t=atToken(input);if(!t)return;input.setRangeText(value,t.start,t.end,'end');input.dispatchEvent(new Event('input',{bubbles:true}));input.focus()}
  function navItem(icon,name,sub,action){return{type:'nav',icon,name,sub,action}}
  async function showAt(){const input=document.getElementById('messageInput');if(!input)return;const tok=atToken(input);if(!tok){closeAt();return}const q=tok.query.toLowerCase();if(!groups.length)await loadGroups();let agents=window.__agentieAgents||[];if(!agents.length){try{agents=(await api('/platform/agents',{cache:'no-store'})).items||[]}catch(_){ }}const menu=ensureAtMenu();menu.replaceChildren();atItems=[];function heading(s){const h=document.createElement('div');h.className='agentie-at-section';h.textContent=s;menu.appendChild(h)}function add(item){const b=document.createElement('button');b.type='button';b.className='agentie-at-item';if(item.type==='agent'){const orb=document.createElement('span');orb.className='agentie-at-orb';orb.style.background=colorFor(item.agent.id);orb.textContent=initials(item.agent.name);b.appendChild(orb)}else{const i=document.createElement('span');i.className='agentie-at-nav-icon';i.textContent=item.icon||'•';b.appendChild(i)}const c=document.createElement('span');c.className='agentie-at-copy';const strong=document.createElement('strong');strong.textContent=item.name;const small=document.createElement('small');small.textContent=item.sub||'';c.append(strong,small);b.appendChild(c);b.onclick=()=>{closeAt();if(item.type==='agent')replaceAt(input,`@${item.agent.name} `);else{replaceAt(input,'');item.action?.()}};menu.appendChild(b);atItems.push(b)}const filtered=agents.filter(a=>!q||String(a.name||'').toLowerCase().includes(q)||String(a.job||a.role||'').toLowerCase().includes(q)).slice(0,10);if(filtered.length){heading('Agents');for(const a of filtered)add({type:'agent',name:a.name,sub:a.job||a.role||'',agent:a})}const nav=[navItem('◈','Plugins','Connect tools and MCPs',()=>document.getElementById('agentiePluginsButton')?.click()),navItem('◷','Activity','Open activity timeline',()=>clickSidebarAction('Activity')),navItem('💬','Agent chats','Open or create group chats',openGroupDirectory),navItem('↻','Automation','Open routines and automation',()=>clickSidebarAction('Automation'))].filter(x=>!q||x.name.toLowerCase().includes(q)||x.sub.toLowerCase().includes(q));if(nav.length){heading('Navigate');nav.forEach(add)}const matchingGroups=groups.filter(g=>!q||String(g.name||'').toLowerCase().includes(q));if(matchingGroups.length){heading('Group chats');for(const g of matchingGroups.slice(0,8))add(navItem('👥',g.name,(g.participants||[]).join(' · '),()=>openGroupChat(g.id)))}if(!atItems.length){closeAt();return}const rect=input.getBoundingClientRect();menu.classList.add('open');const width=menu.getBoundingClientRect().width||340;menu.style.left=`${Math.max(8,Math.min(rect.left,window.innerWidth-width-8))}px`;menu.style.bottom=`${Math.max(8,window.innerHeight-rect.top+8)}px`;atIndex=0;atItems[0]?.classList.add('selected')}
  document.addEventListener('input',e=>{if(e.target?.id==='messageInput')showAt()});document.addEventListener('keydown',e=>{if(e.target?.id!=='messageInput'||!atMenu?.classList.contains('open'))return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();atItems[atIndex]?.classList.remove('selected');atIndex=(atIndex+(e.key==='ArrowDown'?1:-1)+atItems.length)%atItems.length;atItems[atIndex]?.classList.add('selected');atItems[atIndex]?.scrollIntoView({block:'nearest'})}else if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.stopImmediatePropagation();atItems[atIndex]?.click()}else if(e.key==='Escape'){e.preventDefault();closeAt()}},true);document.addEventListener('click',e=>{if(atMenu&&!atMenu.contains(e.target)&&e.target?.id!=='messageInput')closeAt()},true);

  function install(){hideOldLaunchers();installProfile();renderGroups()}
  let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;install()})}).observe(document.body,{childList:true,subtree:true});setTimeout(()=>{install();loadGroups()},180);setInterval(()=>{hideOldLaunchers();installProfile();loadGroups();refreshActiveGroup()},2200);
})();
