(()=>{
  if(window.__agentieModelRouterUI)return;window.__agentieModelRouterUI=true;
  const css=document.createElement('style');css.textContent=`
    .model-router-control{margin-top:8px;border:1px solid var(--border);border-radius:11px;background:var(--soft);padding:10px}
    .model-router-head{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:7px;font-size:10px;color:var(--muted)}.model-router-head b{font-size:11px;color:var(--text)}
    .model-router-modes{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.model-router-mode{border:1px solid var(--border);border-radius:8px;background:var(--panel);color:var(--text);padding:7px 4px;font-size:10px;cursor:pointer}.model-router-mode.active{background:#0b84ff;color:#fff;border-color:#0b84ff}.model-router-mode:disabled{opacity:.55;cursor:default}.model-router-detail{font-size:9px;color:var(--muted);line-height:1.4;margin-top:7px;white-space:normal}
    .agentie-settings-overlay{position:fixed;inset:0;z-index:16000;background:rgba(0,0,0,.46);display:grid;place-items:center;padding:18px}.agentie-settings-panel{width:min(460px,100%);max-height:88vh;overflow:auto;border:1px solid var(--border);border-radius:16px;background:var(--panel);padding:16px;box-shadow:0 22px 70px rgba(0,0,0,.3)}.agentie-settings-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.agentie-settings-head h3{margin:0;font-size:16px}.agentie-settings-close{border:0;background:transparent;color:var(--muted);font-size:22px;cursor:pointer}.agentie-settings-section{margin-top:14px;padding-top:12px;border-top:1px solid var(--border)}.agentie-settings-label{font-size:10px;text-transform:uppercase;letter-spacing:.06em;color:var(--muted);margin-bottom:7px}
  `;document.head.appendChild(css);

  async function api(url,options={}){const r=await fetch(url,options),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||d.message||'Request failed');return d}
  function label(mode){return mode==='local'?'Local':mode==='powerful'?'Powerful':'Auto'}
  function detailText(state){const local=state.local||{},cloud=state.powerful||{};const localState=local.available===true?'local ready':local.available===false?'local offline':'local not checked';const cloudState=cloud.configured?`${cloud.provider||'cloud'} ready`:`${cloud.provider||'cloud'} not configured`;if(state.mode==='local')return `${local.model||'local model'} · ${localState} · cloud fallback off`;if(state.mode==='powerful')return `${cloud.provider||'powerful'} · ${cloudState}`;return `${local.model||'local model'} first · ${localState} · escalates when needed`}
  async function refresh(control,verify=false){try{const state=await api(`/platform/model-routing/status?verify=${verify?'true':'false'}`,{cache:'no-store'});control.dataset.mode=state.mode||'auto';for(const b of control.querySelectorAll('.model-router-mode'))b.classList.toggle('active',b.dataset.mode===state.mode);control.querySelector('[data-current]').textContent=label(state.mode||'auto');control.querySelector('.model-router-detail').textContent=detailText(state);return state}catch(e){control.querySelector('.model-router-detail').textContent=e.message;return null}}
  async function setMode(control,mode){for(const b of control.querySelectorAll('.model-router-mode'))b.disabled=true;try{await api('/platform/model-routing/mode',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode})});await refresh(control,true)}catch(e){control.querySelector('.model-router-detail').textContent=e.message}finally{for(const b of control.querySelectorAll('.model-router-mode'))b.disabled=false}}
  function createModelControl(){const control=document.createElement('div');control.className='model-router-control';control.innerHTML=`<div class="model-router-head"><b>AI model</b><span data-current>Auto</span></div><div class="model-router-modes">${['local','auto','powerful'].map(m=>`<button type="button" class="model-router-mode" data-mode="${m}">${label(m)}</button>`).join('')}</div><div class="model-router-detail">Checking model routing…</div>`;for(const b of control.querySelectorAll('.model-router-mode'))b.onclick=()=>setMode(control,b.dataset.mode);refresh(control,true);return control}
  window.__agentieMountModelRouter=container=>{if(!container)return null;let control=container.querySelector('.model-router-control');if(!control){control=createModelControl();container.appendChild(control)}return control};
})();
