(()=>{
  if(window.__agentieNavigationConnect)return;window.__agentieNavigationConnect=true;

  const css=document.createElement('style');css.textContent=`
    .plugins-launch{bottom:58px!important}
    .agentie-connected-profile{position:absolute;left:18px;right:18px;bottom:12px;z-index:90}.agentie-connected-profile-button{width:100%;display:flex;align-items:center;gap:9px;border:1px solid transparent;background:transparent;color:var(--text);border-radius:10px;padding:8px 10px;cursor:pointer;text-align:left}.agentie-connected-profile-button:hover{background:var(--soft);border-color:var(--border)}.agentie-connected-profile-icon{width:25px;height:25px;border-radius:50%;display:grid;place-items:center;background:var(--soft);border:1px solid var(--border);font-size:12px}.agentie-connected-profile-menu{position:absolute;left:0;right:0;bottom:calc(100% + 6px);display:none;z-index:18000;border:1px solid var(--border);border-radius:11px;background:var(--panel);padding:5px;box-shadow:0 16px 42px rgba(0,0,0,.26)}.agentie-connected-profile-menu.open{display:grid}.agentie-connected-profile-menu button{border:0;background:transparent;color:var(--text);border-radius:8px;text-align:left;padding:8px 9px;font-size:10px;cursor:pointer}.agentie-connected-profile-menu button:hover{background:var(--soft)}
    .agentie-connected-plugin-tools{display:grid;grid-template-columns:1fr 1fr;gap:7px;padding:10px 16px;border-bottom:1px solid var(--border);background:var(--panel)}.agentie-connected-plugin-tools-title{grid-column:1/-1;font-size:9px;text-transform:uppercase;letter-spacing:.06em;color:var(--muted)}.agentie-connected-plugin-tools button{border:1px solid var(--border);border-radius:9px;background:var(--soft);color:var(--text);padding:8px 9px;font-size:10px;text-align:left;cursor:pointer}.agentie-connected-plugin-tools button:hover{background:var(--panel)}
    .sidebar>.platform-activity-launch,.sidebar>.platform-skills-launch,.sidebar>.pa-automation-launch,.sidebar>.n4-auto,.sidebar>.n4-market,.sidebar>.n4-chats,.sidebar>.platform-chats-launch{display:none!important}
    .sidebar-group-row{grid-template-columns:38px minmax(0,1fr)!important}.sidebar-group-row.active{background:var(--soft)}.group-list-label{font-size:9px;color:var(--muted);padding:9px 5px 3px;text-transform:uppercase;letter-spacing:.05em}.agentie-connected-sidebar-stack{position:relative;width:38px;height:34px;flex:none}.agentie-connected-sidebar-dot{position:absolute;width:24px;height:24px;border-radius:50%;border:2px solid var(--panel);display:grid;place-items:center;font-size:7px;font-weight:800;color:#111;box-shadow:0 1px 4px rgba(0,0,0,.18)}.agentie-connected-sidebar-dot:nth-child(1){left:0;top:5px}.agentie-connected-sidebar-dot:nth-child(2){left:10px;top:0}.agentie-connected-sidebar-dot:nth-child(3){left:14px;top:10px}
    .agentie-connected-group-head{display:flex;align-items:center;gap:10px;margin:2px 0 18px;padding-bottom:13px;border-bottom:1px solid var(--border)}.agentie-connected-group-stack{position:relative;width:42px;height:34px;flex:none}.agentie-connected-group-dot{position:absolute;width:25px;height:25px;border-radius:50%;border:2px solid var(--panel);display:grid;place-items:center;font-size:7px;font-weight:800;color:#111;box-shadow:0 1px 4px rgba(0,0,0,.16)}.agentie-connected-group-dot:nth-child(1){left:0;top:5px}.agentie-connected-group-dot:nth-child(2){left:11px;top:0}.agentie-connected-group-dot:nth-child(3){left:17px;top:9px}.agentie-connected-group-copy strong,.agentie-connected-group-copy small{display:block}.agentie-connected-group-copy strong{font-size:14px}.agentie-connected-group-copy small{font-size:10px;color:var(--muted);margin-top:2px}.agentie-connected-group-author{font-size:10px;font-weight:700;color:var(--muted);margin:0 0 3px 2px}.agentie-connected-group-error{font-size:11px;color:#ef4444;margin:10px 0}.agentie-connected-group-opening{display:flex;align-items:center;gap:8px;color:var(--muted);font-size:12px;margin:18px 0}
    .assistant-row.agentie-connected-group-agent-row{align-items:flex-start;gap:10px}.assistant-row.agentie-connected-group-agent-row::before{display:none!important;content:none!important}.agentie-connected-group-message-orb{width:36px;height:36px;border-radius:50%;display:grid;place-items:center;flex:none;color:#111;font-size:9px;font-weight:800;box-shadow:inset 0 -5px 10px rgba(0,0,0,.12)}
    .agentie-connected-group-typing{display:flex;align-items:center;gap:8px;margin:12px 0 8px 2px;color:var(--muted);font-size:10px;min-height:34px}.agentie-connected-group-typing-copy{display:flex;align-items:center;gap:7px;min-width:0}.agentie-connected-group-typing-label{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:360px}.agentie-connected-group-typing-dots{display:inline-flex;align-items:center;gap:3px}.agentie-connected-group-typing-dots i{display:block;width:5px;height:5px;border-radius:50%;background:currentColor;opacity:.3;animation:agentie-group-dot 1.05s infinite ease-in-out}.agentie-connected-group-typing-dots i:nth-child(2){animation-delay:.14s}.agentie-connected-group-typing-dots i:nth-child(3){animation-delay:.28s}@keyframes agentie-group-dot{0%,60%,100%{transform:translateY(0);opacity:.28}30%{transform:translateY(-4px);opacity:1}}
    .agentie-connected-top-group{display:flex;align-items:center;gap:9px;min-width:0}.agentie-connected-top-group-copy{min-width:0}.agentie-connected-top-group-copy strong{display:block;font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.agentie-connected-top-participants{display:flex;gap:4px;flex-wrap:wrap;margin-top:3px}.agentie-connected-top-participants span{font-size:8px;color:var(--muted);border:1px solid var(--border);border-radius:999px;padding:2px 5px;background:var(--soft)}
    .agentie-at-menu{position:fixed;z-index:19000;width:min(340px,calc(100vw - 24px));max-height:330px;overflow:auto;border:1px solid var(--border);border-radius:12px;background:var(--panel);box-shadow:0 18px 55px rgba(0,0,0,.28);padding:6px;display:none}.agentie-at-menu.open{display:block}.agentie-at-section{font-size:8px;text-transform:uppercase;letter-spacing:.06em;color:var(--muted);padding:7px 8px 4px}.agentie-at-item{width:100%;display:flex;align-items:center;gap:8px;border:0;background:transparent;color:var(--text);border-radius:8px;padding:7px 8px;text-align:left;cursor:pointer}.agentie-at-item:hover,.agentie-at-item.selected{background:var(--soft)}.agentie-at-orb{width:24px;height:24px;border-radius:50%;display:grid;place-items:center;font-size:7px;font-weight:800;color:#111;flex:none}.agentie-at-copy{min-width:0;flex:1}.agentie-at-copy strong,.agentie-at-copy small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.agentie-at-copy strong{font-size:10px}.agentie-at-copy small{font-size:8px;color:var(--muted);margin-top:1px}.agentie-at-nav-icon{width:24px;height:24px;border-radius:7px;background:var(--soft);display:grid;place-items:center;flex:none;font-size:12px}
  `;document.head.appendChild(css);

  const state={group:null,groups:[],poll:null,loading:false,openToken:0,followBottom:true,restoringScroll:false,lastPointerGroup:'',lastPointerAt:0,lastSignature:'',atMenu:null,atItems:[],atIndex:0};
  const COLORS=['#ff6b6b','#ffd166','#06d6a0','#4cc9f0','#5e60ce','#c77dff','#f72585','#fb8500'];
  const initials=name=>String(name||'A').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
  const colorFor=value=>{let n=0;for(const ch of String(value||''))n=(n*31+ch.charCodeAt(0))>>>0;return COLORS[n%COLORS.length]};
  const esc=value=>{const d=document.createElement('div');d.textContent=String(value??'');return d.innerHTML};
  async function api(url,options={}){const r=await fetch(url,options),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||d.message||'Request failed');return d}
  function clean(text){return String(text||'').replace(/^\s*#{1,6}\s+/gm,'').replace(/\*\*([^*]+)\*\*/g,'$1').replace(/__([^_]+)__/g,'$1').replace(/`([^`]+)`/g,'$1').replace(/^\s*[-*+]\s+/gm,'• ').trim()}

  function nativeLauncher(kind){const selectors={activity:'.platform-activity-launch',automation:'.n4-auto,.pa-automation-launch',skills:'.platform-skills-launch',marketplace:'.n4-market',chats:'.n4-chats,.platform-chats-launch'};const list=[...document.querySelectorAll(selectors[kind]||'')];return list.find(el=>!el.closest('.agentie-connected-profile,.agentie-connected-plugin-tools'))||list[0]||null}
  function invokeNative(kind){const el=nativeLauncher(kind);if(!el)return false;el.click();return true}
  window.__agentieInvokeNativeNavigation=invokeNative;

  function openSettings(){document.querySelector('.agentie-settings-overlay')?.remove();const overlay=document.createElement('div');overlay.className='agentie-settings-overlay';const panel=document.createElement('div');panel.className='agentie-settings-panel';panel.innerHTML='<div class="agentie-settings-head"><h3>Settings</h3><button class="agentie-settings-close" type="button">×</button></div><div class="agentie-settings-section"><div class="agentie-settings-label">AI model</div><div data-model-slot></div></div>';overlay.appendChild(panel);document.body.appendChild(overlay);const close=()=>overlay.remove();panel.querySelector('.agentie-settings-close').onclick=close;overlay.onclick=e=>{if(e.target===overlay)close()};window.__agentieMountModelRouter?.(panel.querySelector('[data-model-slot]'))}
  function installProfile(){const sidebar=document.querySelector('.sidebar'),plugin=document.getElementById('agentiePluginsButton');if(!sidebar||!plugin)return;sidebar.querySelectorAll('.agentie-profile-wrap:not(.agentie-connected-profile)').forEach(x=>x.remove());let wrap=sidebar.querySelector('.agentie-connected-profile');if(wrap)return;wrap=document.createElement('div');wrap.className='agentie-profile-wrap agentie-connected-profile';wrap.innerHTML='<button class="agentie-connected-profile-button" type="button"><span class="agentie-connected-profile-icon">👤</span><span>Profile</span></button><div class="agentie-connected-profile-menu"><button type="button" data-connected-profile="settings">⚙ Settings</button><button type="button" data-connected-profile="activity">◷ Activity</button><button type="button" data-connected-profile="automation">↻ Automation</button></div>';sidebar.appendChild(wrap);const button=wrap.querySelector('.agentie-connected-profile-button'),menu=wrap.querySelector('.agentie-connected-profile-menu');button.onclick=e=>{e.preventDefault();e.stopPropagation();menu.classList.toggle('open')};wrap.querySelector('[data-connected-profile="settings"]').onclick=()=>{menu.classList.remove('open');openSettings()};wrap.querySelector('[data-connected-profile="activity"]').onclick=()=>{menu.classList.remove('open');invokeNative('activity')};wrap.querySelector('[data-connected-profile="automation"]').onclick=()=>{menu.classList.remove('open');invokeNative('automation')}}
  function installPluginTools(){const panel=document.getElementById('agentiePluginsPanel'),head=panel?.querySelector('.plugins-head');if(!panel||!head)return;let tools=panel.querySelector('.agentie-connected-plugin-tools');if(tools)return;tools=document.createElement('div');tools.className='agentie-connected-plugin-tools';tools.innerHTML='<div class="agentie-connected-plugin-tools-title">Skills & Marketplace</div><button type="button" data-plugin-tool="skills">⚡ Skills</button><button type="button" data-plugin-tool="marketplace">🧩 Marketplace</button>';head.insertAdjacentElement('afterend',tools);tools.querySelector('[data-plugin-tool="skills"]').onclick=()=>{panel.classList.remove('open');invokeNative('skills')};tools.querySelector('[data-plugin-tool="marketplace"]').onclick=()=>{panel.classList.remove('open');invokeNative('marketplace')}}

  function groupStack(d){const stack=document.createElement('div');stack.className='agentie-connected-group-stack';(d.participants||[]).slice(0,3).forEach((name,i)=>{const dot=document.createElement('span');dot.className='agentie-connected-group-dot';dot.style.background=colorFor((d.participant_ids||[])[i]||name);dot.textContent=initials(name).slice(0,1);stack.appendChild(dot)});return stack}
  function sidebarStack(d){const stack=document.createElement('div');stack.className='agentie-connected-sidebar-stack';(d.participants||[]).slice(0,3).forEach((name,i)=>{const dot=document.createElement('span');dot.className='agentie-connected-sidebar-dot';dot.style.background=colorFor((d.participant_ids||[])[i]||name);dot.textContent=initials(name).slice(0,1);stack.appendChild(dot)});return stack}
  function messageOrb(message){const orb=document.createElement('span');const name=String(message?.sender_name||'Agent');const id=String(message?.sender_id||name);orb.className='agentie-connected-group-message-orb';orb.dataset.agentId=String(message?.sender_id||'');orb.style.background=colorFor(id);orb.textContent=initials(name).slice(0,2);return orb}
  function renderGroupRows(){const list=document.getElementById('persistentAgentList');if(!list)return;list.querySelectorAll('.sidebar-group-row,.group-list-label').forEach(x=>x.remove());if(!state.groups.length)return;const label=document.createElement('div');label.className='group-list-label';label.textContent='Group chats';label.style.order='20000';list.appendChild(label);let order=20001;for(const g of state.groups){const row=document.createElement('div');row.className='agent-row sidebar-group-row'+(state.group?.id===g.id?' active':'');row.dataset.groupId=g.id;row.style.order=String(order++);row.appendChild(sidebarStack(g));const copy=document.createElement('div');copy.className='agent-copy';copy.innerHTML=`<strong>${esc(g.name)}</strong><small>${esc((g.participants||[]).join(' · '))}</small>`;row.appendChild(copy);list.appendChild(row)}}
  function markActiveRows(){document.querySelectorAll('#persistentAgentList .sidebar-group-row').forEach(row=>row.classList.toggle('active',!!state.group&&row.dataset.groupId===state.group.id))}
  async function loadGroups(){try{const d=await api('/platform/agent-chats',{cache:'no-store'});state.groups=d.items||[];renderGroupRows();return state.groups}catch(_){return state.groups}}

  function scrollHost(){const shell=document.querySelector('.chat-shell');if(shell){const css=getComputedStyle(shell),overflow=String(css.overflowY||css.overflow||'');if(/auto|scroll|overlay/.test(overflow))return shell}return document.scrollingElement||document.documentElement||document.body}
  window.__agentieGroupScrollRoot=scrollHost;
  function isNearBottom(host,threshold=120){return !host||host.scrollHeight-host.scrollTop-host.clientHeight<=threshold}
  function setHostScroll(host,value){if(!host)return;state.restoringScroll=true;host.scrollTop=value;requestAnimationFrame(()=>{state.restoringScroll=false})}
  function threadSignature(d){return [d.id,d.updated_at,(d.messages||[]).map(m=>`${m.id}:${m.message}:${m.job?.status||''}`).join('|'),(d.presence||[]).map(p=>`${p.agent_id}:${p.status}:${p.outstanding_tasks||0}`).join('|')].join('::')}
  function syncTopbar(d=state.group){const top=document.querySelector('.workspace-topbar .top-agent');if(!top)return;const orb=top.querySelector(':scope > .top-agent-orb'),copy=top.querySelector(':scope > .top-agent-copy');let group=top.querySelector(':scope > .agentie-connected-top-group');if(!d){group?.remove();orb?.style.removeProperty('display');copy?.style.removeProperty('display');return}if(orb)orb.style.setProperty('display','none','important');if(copy)copy.style.setProperty('display','none','important');if(!group){group=document.createElement('div');group.className='agentie-connected-top-group';top.appendChild(group)}group.replaceChildren();group.appendChild(groupStack(d));const info=document.createElement('div');info.className='agentie-connected-top-group-copy';const title=document.createElement('strong');title.textContent=d.name||'Group chat';const tags=document.createElement('div');tags.className='agentie-connected-top-participants';for(const name of d.participants||[]){const tag=document.createElement('span');tag.textContent=name;tags.appendChild(tag)}info.append(title,tags);group.appendChild(info)}
  function busyPresence(d){return (d.presence||[]).filter(p=>p.status==='working'||p.status==='queued')}
  function renderTyping(d,box){const busy=busyPresence(d);if(!busy.length||!box)return;const row=document.createElement('div');row.className='agentie-connected-group-typing';row.appendChild(groupStack({participants:busy.map(x=>x.agent_name||'Agent'),participant_ids:busy.map(x=>x.agent_id||'')}));const copy=document.createElement('div');copy.className='agentie-connected-group-typing-copy';const label=document.createElement('span');label.className='agentie-connected-group-typing-label';const names=busy.map(x=>x.agent_name||'Agent');label.textContent=names.length===1?`${names[0]} is replying`:`${names.slice(0,3).join(' · ')} are replying`;const dots=document.createElement('span');dots.className='agentie-connected-group-typing-dots';dots.innerHTML='<i></i><i></i><i></i>';copy.append(label,dots);row.appendChild(copy);box.appendChild(row)}
  function renderThread(d,{forceBottom=false}={}){if(!state.group||String(state.group.id)!==String(d.id))return;state.group=d;window.__agentieActiveGroupChat=d;syncTopbar(d);const signature=threadSignature(d);if(!forceBottom&&signature===state.lastSignature){markActiveRows();return}state.lastSignature=signature;const box=document.getElementById('messages');if(!box)return;const host=scrollHost(),oldTop=host?.scrollTop||0,shouldFollow=forceBottom||state.followBottom||isNearBottom(host);box.replaceChildren();const head=document.createElement('div');head.className='agentie-connected-group-head';head.appendChild(groupStack(d));const copy=document.createElement('div');copy.className='agentie-connected-group-copy';const strong=document.createElement('strong');strong.textContent=d.name||'Group chat';const small=document.createElement('small');small.textContent=(d.participants||[]).join(' · ');copy.append(strong,small);head.appendChild(copy);box.appendChild(head);for(const m of d.messages||[]){const isUser=String(m.sender_type||'')==='user';const row=document.createElement('div');row.className=isUser?'user-row':'assistant-row agentie-connected-group-agent-row';const wrap=document.createElement('div');if(!isUser){row.appendChild(messageOrb(m));const author=document.createElement('div');author.className='agentie-connected-group-author';author.textContent=m.sender_name||'Agent';wrap.appendChild(author)}const bubble=document.createElement('div');bubble.className='bubble '+(isUser?'user':'assistant');bubble.textContent=isUser?String(m.message||''):clean(m.message||'');wrap.appendChild(bubble);row.appendChild(wrap);box.appendChild(row)}renderTyping(d,box);markActiveRows();requestAnimationFrame(()=>{if(!host)return;if(shouldFollow){state.followBottom=true;setHostScroll(host,host.scrollHeight)}else setHostScroll(host,oldTop)})}
  function showOpeningGroup(id){const box=document.getElementById('messages');if(!box)return;const known=state.groups.find(x=>String(x.id)===String(id));box.replaceChildren();if(known){syncTopbar(known);const head=document.createElement('div');head.className='agentie-connected-group-head';head.appendChild(groupStack(known));const copy=document.createElement('div');copy.className='agentie-connected-group-copy';const strong=document.createElement('strong');strong.textContent=known.name||'Group chat';const small=document.createElement('small');small.textContent=(known.participants||[]).join(' · ');copy.append(strong,small);head.appendChild(copy);box.appendChild(head)}const opening=document.createElement('div');opening.className='agentie-connected-group-opening';opening.textContent='Opening group chat…';box.appendChild(opening)}
  function showGroupError(message){const box=document.getElementById('messages');if(!box)return;box.querySelector('.agentie-connected-group-opening')?.remove();const row=document.createElement('div');row.className='agentie-connected-group-error';row.textContent=`Could not open group chat: ${message}`;box.appendChild(row)}
  function restoreNormalSurface(){try{if(typeof window.restoreChatView==='function'){window.restoreChatView(null);return}}catch(_){ }const box=document.getElementById('messages');if(box)box.innerHTML='<div class="assistant-row"><div class="bubble assistant">What would you like Agentie to do?</div></div>'}
  function leaveGroup(){if(state.poll){clearInterval(state.poll);state.poll=null}state.openToken++;state.group=null;state.followBottom=true;state.lastSignature='';window.__agentieActiveGroupChat=null;syncTopbar(null);const input=document.getElementById('messageInput');if(input)input.placeholder='Message Agentie...';restoreNormalSurface();markActiveRows()}
  async function refreshGroup(){const current=state.group;if(!current||state.loading)return;const id=String(current.id),token=state.openToken;state.loading=true;try{const d=await api(`/platform/agent-chats/${encodeURIComponent(id)}`,{cache:'no-store'});if(token!==state.openToken||!state.group||String(state.group.id)!==id)return;renderThread(d)}catch(e){if(token===state.openToken)showGroupError(e.message)}finally{state.loading=false}}
  async function openGroup(id){if(!id)return;const nextId=String(id),token=++state.openToken;if(state.poll){clearInterval(state.poll);state.poll=null}state.loading=false;state.lastSignature='';state.followBottom=true;const known=state.groups.find(x=>String(x.id)===nextId)||{id:nextId,name:'Group chat',participants:[],participant_ids:[]};state.group=known;window.__agentieActiveGroupChat=known;try{window.selectPersistentAgent?.(null)}catch(_){ }showOpeningGroup(nextId);try{const d=await api(`/platform/agent-chats/${encodeURIComponent(nextId)}`,{cache:'no-store'});if(token!==state.openToken||!state.group||String(state.group.id)!==nextId)return;state.group=d;window.__agentieActiveGroupChat=d;syncTopbar(d);renderThread(d,{forceBottom:true});const input=document.getElementById('messageInput');if(input){input.placeholder=`Message ${d.name}...`;input.focus()}state.poll=setInterval(refreshGroup,1200)}catch(e){if(token===state.openToken)showGroupError(e.message)}}
  async function sendGroup(){if(!state.group)return false;const id=String(state.group.id),input=document.getElementById('messageInput'),send=document.getElementById('sendButton'),value=String(input?.value||'').trim();if(!value)return true;if(input)input.value='';if(send)send.disabled=true;state.followBottom=true;try{const d=await api(`/platform/agent-chats/${encodeURIComponent(id)}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:value})});if(!state.group||String(state.group.id)!==id)return true;renderThread(d,{forceBottom:true})}catch(e){showGroupError(e.message)}finally{if(send)send.disabled=false;if(input)input.focus()}return true}
  window.__agentieOpenGroupChat=openGroup;window.__agentieSendActiveGroupMessage=sendGroup;

  function ensureAtMenu(){if(state.atMenu)return state.atMenu;const menu=document.createElement('div');menu.className='agentie-at-menu';document.body.appendChild(menu);state.atMenu=menu;return menu}
  function closeAt(){state.atMenu?.classList.remove('open');state.atItems=[];state.atIndex=0}
  function atToken(input){const before=input.value.slice(0,input.selectionStart);const m=before.match(/(^|\s)@([^\s@]*)$/);return m?{query:m[2]||'',start:before.length-(m[2]||'').length-1,end:input.selectionStart}:null}
  function replaceAt(input,value){const t=atToken(input);if(!t)return;input.setRangeText(value,t.start,t.end,'end');input.dispatchEvent(new Event('input',{bubbles:true}));input.focus()}
  async function showAt(){const input=document.getElementById('messageInput');if(!input)return;const tok=atToken(input);if(!tok){closeAt();return}const q=tok.query.toLowerCase();if(!state.groups.length)await loadGroups();let agents=window.__agentieAgents||[];if(!agents.length){try{agents=(await api('/platform/agents',{cache:'no-store'})).items||[]}catch(_){ }}if(state.group){const allowed=new Set((state.group.participant_ids||[]).map(String));agents=agents.filter(a=>allowed.has(String(a.id)))}const menu=ensureAtMenu();menu.replaceChildren();state.atItems=[];const heading=text=>{const h=document.createElement('div');h.className='agentie-at-section';h.textContent=text;menu.appendChild(h)};const add=(icon,name,sub,action,agent=null)=>{const b=document.createElement('button');b.type='button';b.className='agentie-at-item';if(agent){const orb=document.createElement('span');orb.className='agentie-at-orb';orb.style.background=colorFor(agent.id);orb.textContent=initials(agent.name);b.appendChild(orb)}else{const i=document.createElement('span');i.className='agentie-at-nav-icon';i.textContent=icon;b.appendChild(i)}const c=document.createElement('span');c.className='agentie-at-copy';c.innerHTML=`<strong>${esc(name)}</strong><small>${esc(sub||'')}</small>`;b.appendChild(c);b.onclick=()=>{closeAt();if(agent)replaceAt(input,`@${agent.name} `);else{replaceAt(input,'');action?.()}};menu.appendChild(b);state.atItems.push(b)};const filtered=agents.filter(a=>!q||String(a.name||'').toLowerCase().includes(q)||String(a.job||a.role||'').toLowerCase().includes(q)).slice(0,10);if(filtered.length){heading('Agents');for(const a of filtered)add('',a.name,a.job||a.role||'',null,a)}const nav=[['◈','Plugins','Connect tools and MCPs',()=>document.getElementById('agentiePluginsButton')?.click()],['◷','Activity','Open activity timeline',()=>invokeNative('activity')],['💬','Agent chats','Open or create group chats',()=>invokeNative('chats')],['↻','Automation','Open routines and automation',()=>invokeNative('automation')]].filter(x=>!q||x[1].toLowerCase().includes(q)||x[2].toLowerCase().includes(q));if(nav.length){heading('Navigate');for(const x of nav)add(...x)}const groups=state.groups.filter(g=>!q||String(g.name||'').toLowerCase().includes(q));if(groups.length){heading('Group chats');for(const g of groups.slice(0,8))add('👥',g.name,(g.participants||[]).join(' · '),()=>openGroup(g.id))}if(!state.atItems.length){closeAt();return}const rect=input.getBoundingClientRect();menu.classList.add('open');const width=menu.getBoundingClientRect().width||340;menu.style.left=`${Math.max(8,Math.min(rect.left,window.innerWidth-width-8))}px`;menu.style.bottom=`${Math.max(8,window.innerHeight-rect.top+8)}px`;state.atIndex=0;state.atItems[0]?.classList.add('selected')}

  document.addEventListener('pointerdown',e=>{const groupRow=e.target.closest?.('#persistentAgentList .sidebar-group-row');if(!groupRow)return;const id=groupRow.dataset.groupId;if(!id)return;e.preventDefault();e.stopImmediatePropagation();state.lastPointerGroup=id;state.lastPointerAt=Date.now();openGroup(id)},true);
  document.addEventListener('click',e=>{const groupRow=e.target.closest?.('#persistentAgentList .sidebar-group-row');if(groupRow){e.preventDefault();e.stopImmediatePropagation();const id=groupRow.dataset.groupId;if(id&&!(state.lastPointerGroup===id&&Date.now()-state.lastPointerAt<800))openGroup(id);return}const normal=e.target.closest?.('#persistentAgentList .agent-row:not(.sidebar-group-row)');if(normal&&state.group)leaveGroup();if(!e.target.closest?.('.agentie-connected-profile'))document.querySelector('.agentie-connected-profile-menu')?.classList.remove('open');if(state.atMenu&&!state.atMenu.contains(e.target)&&e.target?.id!=='messageInput')closeAt()},true);
  document.addEventListener('input',e=>{if(e.target?.id==='messageInput')showAt()});
  document.addEventListener('keydown',e=>{if(e.target?.id==='messageInput'&&state.atMenu?.classList.contains('open')){if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();state.atItems[state.atIndex]?.classList.remove('selected');state.atIndex=(state.atIndex+(e.key==='ArrowDown'?1:-1)+state.atItems.length)%state.atItems.length;state.atItems[state.atIndex]?.classList.add('selected');state.atItems[state.atIndex]?.scrollIntoView({block:'nearest'});return}if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.stopImmediatePropagation();state.atItems[state.atIndex]?.click();return}if(e.key==='Escape'){e.preventDefault();closeAt();return}}if(!state.group||e.target?.id!=='messageInput')return;if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();e.stopImmediatePropagation();sendGroup()}},true);
  function wireComposer(){const send=document.getElementById('sendButton');if(send&&!send.dataset.agentieGroupConnected){send.dataset.agentieGroupConnected='1';send.addEventListener('click',e=>{if(!state.group)return;e.preventDefault();e.stopImmediatePropagation();sendGroup()},true)}}
  function wireScroll(){const host=scrollHost();if(!host||host.dataset.agentieGroupScroll==='1')return;host.dataset.agentieGroupScroll='1';host.addEventListener('scroll',()=>{if(!state.group||state.restoringScroll)return;state.followBottom=isNearBottom(host,120)},{passive:true})}
  function install(){installProfile();installPluginTools();wireComposer();wireScroll();renderGroupRows();if(state.group)syncTopbar(state.group)}
  let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;install()})}).observe(document.body,{childList:true,subtree:true});
  setTimeout(()=>{install();loadGroups()},280);setInterval(()=>{install();loadGroups()},2200);
})();
