(()=>{
  if(window.__agentiePluginAccessUI)return;window.__agentiePluginAccessUI=true;
  const style=document.createElement('style');style.textContent=`
    .agent-access-box{margin:0 0 18px;padding:11px;border:1px solid var(--border);border-radius:12px;background:var(--soft)}.agent-access-head{display:flex;align-items:center;gap:8px;margin-bottom:5px}.agent-access-head strong{font-size:12px;flex:1}.agent-access-select{max-width:180px;border:1px solid var(--border);border-radius:8px;background:var(--panel);color:var(--text);padding:5px 7px;font-size:11px}.agent-access-help{font-size:10px;color:var(--muted);line-height:1.35;margin-bottom:9px}.agent-access-sub{font-size:10px;color:var(--muted);margin:9px 0 4px;text-transform:uppercase;letter-spacing:.05em}.agent-access-row{display:flex;align-items:center;gap:7px;padding:7px 0;border-top:1px solid var(--border)}.agent-access-copy{min-width:0;flex:1}.agent-access-name{font-size:11px;font-weight:650}.agent-access-meta{font-size:9px;color:var(--muted);margin-top:2px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.agent-access-mode{border:1px solid var(--border);border-radius:7px;background:var(--panel);color:var(--text);padding:4px 6px;font-size:10px}.global-access-btn{border:1px solid var(--border);border-radius:999px;background:var(--panel);color:var(--muted);padding:4px 7px;font-size:9px;cursor:pointer;white-space:nowrap}.global-access-btn.on{background:var(--accent);color:var(--accent-text);border-color:var(--accent)}
    .agent-capability-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.agent-capability-actions button{border:1px solid var(--border);border-radius:8px;padding:6px 10px;background:var(--panel);color:var(--text);cursor:pointer}.agent-capability-actions .allow-once{background:var(--accent);color:var(--accent-text);border-color:var(--accent)}.agent-capability-actions .allow-all{font-weight:650}.skill-runtime-badge{font-size:9px;margin-top:3px}.skill-runtime-badge.ready{color:#2f9e67}.skill-runtime-badge.not-ready{color:#d48719}
    .last30-card{width:min(610px,88vw)}.last30-title{font-size:15px;font-weight:750}.last30-meta{font-size:11px;color:var(--muted);margin-top:4px}.last30-coverage{display:flex;gap:5px;flex-wrap:wrap;margin:10px 0}.last30-chip{font-size:9px;padding:3px 7px;border:1px solid var(--border);border-radius:999px;color:var(--muted);background:var(--soft)}.last30-answer{margin-top:12px;font-size:13px;line-height:1.58}.last30-answer h4{font-size:13px;margin:15px 0 6px}.last30-answer p{margin:0 0 9px}.last30-answer ul{margin:4px 0 11px;padding-left:18px}.last30-answer li{margin:5px 0}.last30-answer .cite{font-size:10px;color:var(--muted);font-weight:650}.last30-source-details{margin-top:12px;border-top:1px solid var(--border);padding-top:9px}.last30-source-details summary{font-size:11px;color:var(--muted);cursor:pointer}.last30-sources{display:grid;gap:6px;margin-top:9px}.last30-source{display:block;text-decoration:none;color:var(--text);padding:8px 9px;border-radius:9px;background:var(--soft);font-size:10.5px;line-height:1.35}.last30-source small{display:block;color:var(--muted);margin-top:3px}
    .collab-strip{width:min(900px,100%);margin:0 auto 7px;min-height:22px;display:none;align-items:center;padding-left:8px}.collab-strip.show{display:flex}.collab-orbs{display:flex;align-items:center}.collab-orb{width:20px;height:20px;border-radius:50%;border:2px solid var(--panel);margin-left:-4px;display:grid;place-items:center;font-size:6px;font-weight:850;color:#111;cursor:pointer;box-shadow:0 1px 4px rgba(0,0,0,.18);transition:transform .12s}.collab-orb:first-child{margin-left:0}.collab-orb:hover{transform:translateY(-2px) scale(1.12);z-index:2}.collab-pulse{width:5px;height:5px;border-radius:50%;background:#22c55e;margin-left:7px;box-shadow:0 0 0 3px color-mix(in srgb,#22c55e 15%,transparent)}
  `;document.head.appendChild(style);
  const esc=value=>{const d=document.createElement('div');d.textContent=String(value??'');return d.innerHTML};
  const COLORS=['#ff6b6b','#ffd166','#06d6a0','#4cc9f0','#5e60ce','#c77dff','#f72585','#fb8500'];
  const initials=n=>String(n||'A').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
  const color=a=>{let n=0;for(const ch of String(a?.id||a?.name||''))n=(n*31+ch.charCodeAt(0))>>>0;return COLORS[n%COLORS.length]};
  function resend(text){const input=document.getElementById('messageInput'),send=document.getElementById('sendButton');if(!input||!send||!text)return;input.value=text;input.dispatchEvent(new Event('input',{bubbles:true}));send.click()}
  async function json(url,options){const r=await fetch(url,options);const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.detail||data.message||'Request failed');return data}
  async function runForAgent(agent,text){if(!agent)throw new Error('Agent not found');return json('/agent/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,agent_type:agent.base||'general',session_id:`${agent.session_prefix}main`})})}
  function currentAgent(){const row=document.querySelector('#persistentAgentList .agent-row.active');if(!row)return null;const name=row.querySelector('.agent-copy strong')?.textContent?.trim();return (window.__agentieAgents||[]).find(a=>a.name===name)||null}
  async function renderAccess(){
    const body=document.querySelector('#agentiePluginsPanel .plugins-body');if(!body||body.querySelector('.agent-access-box'))return;
    try{
      const state=await json('/plugins/state',{cache:'no-store'}),agents=Array.isArray(state.agents)?state.agents:[];if(!agents.length)return;const byId=Object.fromEntries(agents.map(a=>[a.id,a]));const box=document.createElement('div');box.className='agent-access-box';body.prepend(box);box.innerHTML=`<div class="agent-access-head"><strong>Tool access</strong><select class="agent-access-select">${agents.map(a=>`<option value="${esc(a.id)}">${esc(a.name)} · ${esc(a.role||a.base)}</option>`).join('')}</select></div><div class="agent-access-help">Global access applies to existing and future agents. Use <b>Block</b> for an individual agent that should not use a capability.</div><div class="agent-access-content"><div class="plugin-empty">Loading permissions…</div></div>`;const select=box.querySelector('.agent-access-select'),content=box.querySelector('.agent-access-content');
      async function setGlobal(kind,id,allowed){const agent=byId[select.value];await runForAgent(agent,`${allowed?'Always allow':'Revoke'} ${kind} ${id} ${allowed?'for':'from'} all agents`);await loadAgent()}
      async function loadAgent(){
        content.innerHTML='<div class="plugin-empty">Loading permissions…</div>';const data=await json(`/plugins/agent-access/${encodeURIComponent(select.value)}`,{cache:'no-store'});const skills=Array.isArray(data.skills)?data.skills:[],servers=Array.isArray(data.mcp_servers)?data.mcp_servers:[];
        const skillRows=skills.map(s=>{const rt=s.runtime;const runtime=rt?`<div class="skill-runtime-badge ${rt.ready?'ready':'not-ready'}">${rt.ready?`${esc(rt.engine||'Runtime')} ready`:rt.installed?'Installed · runtime missing':'Not installed'}</div>`:'';return `<div class="agent-access-row"><div class="agent-access-copy"><div class="agent-access-name">${esc(s.name)}</div><div class="agent-access-meta">${esc((s.capabilities||[]).slice(0,4).join(' · '))}${s.inherited?' · role default':''}</div>${runtime}</div><button class="global-access-btn ${s.global_allowed?'on':''}" type="button" data-global-skill="${esc(s.id)}" data-global="${s.global_allowed?'1':'0'}">${s.global_allowed?'All agents':'Allow all'}</button><select class="agent-access-mode" data-skill="${esc(s.id)}"><option value="inherit" ${s.mode==='inherit'?'selected':''}>Inherit</option><option value="allow" ${s.mode==='allow'?'selected':''}>Allow</option><option value="block" ${s.mode==='block'?'selected':''}>Block</option></select></div>`}).join('');
        const mcpRows=servers.length?servers.map(s=>`<div class="agent-access-row"><div class="agent-access-copy"><div class="agent-access-name">${esc(s.name)}</div><div class="agent-access-meta">${esc(s.transport||'MCP')} · connected server</div></div><button class="global-access-btn ${s.global_allowed?'on':''}" type="button" data-global-mcp="${esc(s.name)}" data-global="${s.global_allowed?'1':'0'}">${s.global_allowed?'All agents':'Allow all'}</button><select class="agent-access-mode" data-mcp-access="${esc(s.name)}"><option value="allow" ${s.mode!=='block'?'selected':''}>Allowed</option><option value="block" ${s.mode==='block'?'selected':''}>Block</option></select></div>`).join(''):'<div class="plugin-empty">Install/connect an MCP before granting it to agents.</div>';
        content.innerHTML=`<div class="agent-access-sub">Skills</div>${skillRows}<div class="agent-access-sub">Connected MCPs</div>${mcpRows}`;
        content.querySelectorAll('[data-skill]').forEach(el=>el.onchange=async()=>{el.disabled=true;try{await json(`/plugins/agent-access/${encodeURIComponent(select.value)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'skill',capability_id:el.dataset.skill,mode:el.value})})}finally{el.disabled=false}});content.querySelectorAll('[data-mcp-access]').forEach(el=>el.onchange=async()=>{el.disabled=true;try{await json(`/plugins/agent-access/${encodeURIComponent(select.value)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'mcp',capability_id:el.dataset.mcpAccess,allowed:el.value==='allow'})})}finally{el.disabled=false}});content.querySelectorAll('[data-global-skill]').forEach(btn=>btn.onclick=async()=>{btn.disabled=true;try{await setGlobal('skill',btn.dataset.globalSkill,btn.dataset.global!=='1')}finally{btn.disabled=false}});content.querySelectorAll('[data-global-mcp]').forEach(btn=>btn.onclick=async()=>{btn.disabled=true;try{await setGlobal('MCP',btn.dataset.globalMcp,btn.dataset.global!=='1')}finally{btn.disabled=false}})
      }
      select.onchange=loadAgent;await loadAgent()
    }catch(_){ }
  }
  const panel=document.getElementById('agentiePluginsPanel');if(panel)new MutationObserver(()=>{if(panel.classList.contains('open'))setTimeout(renderAccess,0)}).observe(panel,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});document.getElementById('agentiePluginsButton')?.addEventListener('click',()=>setTimeout(renderAccess,120));

  function inline(text){const f=document.createDocumentFragment();const parts=String(text||'').split(/(\[L\d+(?:\]\[L\d+)*\])/g);parts.forEach(p=>{if(/^\[L\d+/.test(p)){const s=document.createElement('span');s.className='cite';s.textContent=p;f.appendChild(s)}else f.appendChild(document.createTextNode(p))});return f}
  function renderAnswer(container,answer){let list=null;String(answer||'').split(/\n/).forEach(raw=>{const line=raw.trim();if(!line){list=null;return}if(line.startsWith('• ')){if(!list){list=document.createElement('ul');container.appendChild(list)}const li=document.createElement('li');li.appendChild(inline(line.slice(2)));list.appendChild(li);return}list=null;const clean=line.replace(/^\d+[.)]\s*/,m=>m);if(clean.length<72&&!/[.!?]$/.test(clean)){const h=document.createElement('h4');h.appendChild(inline(clean));container.appendChild(h)}else{const p=document.createElement('p');p.appendChild(inline(clean));container.appendChild(p)}})}
  function renderLast30(card){const wrap=document.createElement('div');wrap.className='card-wrap last30-card';const el=document.createElement('div');el.className='result-card';wrap.appendChild(el);const title=document.createElement('div');title.className='last30-title';title.textContent='🌐 Last30Days';el.appendChild(title);const meta=document.createElement('div');meta.className='last30-meta';meta.textContent=`${card.topic||'Recent research'} · ${card.window_days||30} days · ${card.engine||'native'}`;el.appendChild(meta);const coverage=document.createElement('div');coverage.className='last30-coverage';Object.entries(card.source_counts||{}).forEach(([name,count])=>{const chip=document.createElement('span');chip.className='last30-chip';chip.textContent=`${name} ${count}`;coverage.appendChild(chip)});el.appendChild(coverage);const answer=document.createElement('div');answer.className='last30-answer';renderAnswer(answer,card.answer||'');el.appendChild(answer);const details=document.createElement('details');details.className='last30-source-details';const summary=document.createElement('summary');summary.textContent=`Sources (${(card.sources||[]).length})`;details.appendChild(summary);const sources=document.createElement('div');sources.className='last30-sources';(card.sources||[]).slice(0,12).forEach(s=>{const a=document.createElement('a');a.className='last30-source';a.href=s.url||'#';a.target='_blank';a.rel='noopener noreferrer';a.textContent=s.title||s.url||'Source';const sm=document.createElement('small');sm.textContent=`${s.id||''} · ${s.source||'web'} · ${s.domain||''}`;a.appendChild(sm);sources.appendChild(a)});details.appendChild(sources);el.appendChild(details);return wrap}

  const composerWrap=document.querySelector('.composer-wrap');let collab=null;if(composerWrap){collab=document.createElement('div');collab.className='collab-strip';collab.innerHTML='<div class="collab-orbs"></div><span class="collab-pulse"></span>';composerWrap.prepend(collab)}
  function chatKey(){return currentAgent()?.id||'base'}function ownerJobs(){try{return JSON.parse(localStorage.getItem(`agentie.collab.${chatKey()}`)||'[]')}catch(_){return[]}}function rememberTeam(card){if(!card?.id||!['queued','working'].includes(card.status))return;const key=`agentie.collab.${chatKey()}`;let ids=[];try{ids=JSON.parse(localStorage.getItem(key)||'[]')}catch(_){};ids=[card.id,...ids.filter(x=>x!==card.id)].slice(0,12);localStorage.setItem(key,JSON.stringify(ids))}
  function goAgent(name){const agent=(window.__agentieAgents||[]).find(a=>a.name===name);if(!agent)return;const rows=[...document.querySelectorAll('#persistentAgentList .agent-row')];const row=rows.find(r=>r.querySelector('.agent-copy strong')?.textContent?.trim()===agent.name);row?.click()}
  async function refreshCollab(){if(!collab)return;try{const data=await json('/agent/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Show team jobs',agent_type:'general',session_id:'ui:collaboration-strip'})});const jobs=data.card?.type==='team_jobs'?(data.card.items||[]):[];const active=jobs.filter(j=>['queued','working'].includes(j.status));const current=currentAgent();const owned=new Set(ownerJobs());const relevant=active.filter(j=>owned.has(j.id)||(current&&(j.agents||[]).includes(current.name)));const names=[];relevant.forEach(j=>(j.handoffs||[]).filter(h=>['queued','working'].includes(h.status)).forEach(h=>{if(h.agent&&!names.includes(h.agent))names.push(h.agent)}));const agents=names.map(n=>(window.__agentieAgents||[]).find(a=>a.name===n)).filter(Boolean);const box=collab.querySelector('.collab-orbs');box.replaceChildren();if(agents.length<2){collab.classList.remove('show');return}agents.forEach(a=>{const b=document.createElement('button');b.type='button';b.className='collab-orb';b.style.background=color(a);b.textContent=initials(a.name);b.title=a.name;b.setAttribute('aria-label',`Open ${a.name} chat`);b.onclick=()=>goAgent(a.name);box.appendChild(b)});collab.title=`Working together: ${agents.map(a=>a.name).join(', ')}`;collab.classList.add('show')}catch(_){collab.classList.remove('show')}}
  setInterval(refreshCollab,1600);setTimeout(refreshCollab,500);

  const previous=window.renderCard;if(typeof previous==='function')window.renderCard=function(card,message){
    if(card?.type==='team_job'){rememberTeam(card);setTimeout(refreshCollab,80)}
    if(card?.type==='last30days')return renderLast30(card);
    if(!card||card.type!=='agent_capability_approval')return previous(card,message);
    const wrap=document.createElement('div');wrap.className='card-wrap';const el=document.createElement('div');el.className='result-card';wrap.appendChild(el);const title=document.createElement('div');title.className='card-title';title.textContent=`Permission for ${card.agent_name||'agent'}`;el.appendChild(title);const detail=document.createElement('div');detail.className='mcp-approval-detail';detail.textContent=`Use ${card.capability_kind||'capability'}: ${card.capability_id||''}`;el.appendChild(detail);const actions=document.createElement('div');actions.className='agent-capability-actions';const once=document.createElement('button'),all=document.createElement('button'),deny=document.createElement('button');once.className='allow-once';once.textContent='Allow once';all.className='allow-all';all.textContent='Always allow for all agents';deny.textContent='Deny';actions.append(once,all,deny);el.appendChild(actions);
    async function resolve(mode){once.disabled=all.disabled=deny.disabled=true;try{await json(`/approvals/${card.approval.id}/resolve`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({approved:mode!=='deny'})});if(mode==='all'){const agent=(window.__agentieAgents||[]).find(a=>a.id===card.agent_id);await runForAgent(agent,`Always allow ${card.capability_kind==='mcp'?'MCP':'skill'} ${card.capability_id} for all agents`)}title.textContent=mode==='all'?'✓ Allowed for all agents':mode==='once'?'✓ Allowed once':'Permission denied';actions.remove();if(mode!=='deny'&&card.command)setTimeout(()=>resend(card.command),100)}catch(e){once.disabled=all.disabled=deny.disabled=false;detail.textContent=e.message||'Could not update permission.'}}
    once.onclick=()=>resolve('once');all.onclick=()=>resolve('all');deny.onclick=()=>resolve('deny');return wrap
  };
})();
