(()=>{
  if(window.__agentiePluginAccessUI)return;window.__agentiePluginAccessUI=true;
  const style=document.createElement('style');style.textContent=`
    .agent-access-box{margin:0 0 18px;padding:11px;border:1px solid var(--border);border-radius:12px;background:var(--soft)}
    .agent-access-head{display:flex;align-items:center;gap:8px;margin-bottom:5px}.agent-access-head strong{font-size:12px;flex:1}.agent-access-select{max-width:180px;border:1px solid var(--border);border-radius:8px;background:var(--panel);color:var(--text);padding:5px 7px;font-size:11px}.agent-access-help{font-size:10px;color:var(--muted);line-height:1.35;margin-bottom:9px}
    .agent-access-sub{font-size:10px;color:var(--muted);margin:9px 0 4px;text-transform:uppercase;letter-spacing:.05em}.agent-access-row{display:flex;align-items:center;gap:7px;padding:7px 0;border-top:1px solid var(--border)}.agent-access-row:first-of-type{border-top:0}.agent-access-copy{min-width:0;flex:1}.agent-access-name{font-size:11px;font-weight:650}.agent-access-meta{font-size:9px;color:var(--muted);margin-top:2px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.agent-access-mode{border:1px solid var(--border);border-radius:7px;background:var(--panel);color:var(--text);padding:4px 6px;font-size:10px}.global-access-btn{border:1px solid var(--border);border-radius:999px;background:var(--panel);color:var(--muted);padding:4px 7px;font-size:9px;cursor:pointer;white-space:nowrap}.global-access-btn.on{background:var(--accent);color:var(--accent-text);border-color:var(--accent)}
    .agent-capability-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.agent-capability-actions button{border:1px solid var(--border);border-radius:8px;padding:6px 10px;background:var(--panel);color:var(--text);cursor:pointer}.agent-capability-actions .allow-once{background:var(--accent);color:var(--accent-text);border-color:var(--accent)}.agent-capability-actions .allow-all{font-weight:650}.skill-runtime-badge{font-size:9px;margin-top:3px}.skill-runtime-badge.ready{color:#2f9e67}.skill-runtime-badge.not-ready{color:#d48719}
  `;document.head.appendChild(style);
  const esc=value=>{const d=document.createElement('div');d.textContent=String(value??'');return d.innerHTML};
  function resend(text){const input=document.getElementById('messageInput'),send=document.getElementById('sendButton');if(!input||!send||!text)return;input.value=text;input.dispatchEvent(new Event('input',{bubbles:true}));send.click()}
  async function json(url,options){const r=await fetch(url,options);const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.detail||data.message||'Request failed');return data}
  async function runForAgent(agent,text){if(!agent)throw new Error('Agent not found');return json('/agent/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,agent_type:agent.base||'general',session_id:`${agent.session_prefix}main`})})}
  async function renderAccess(){
    const body=document.querySelector('#agentiePluginsPanel .plugins-body');if(!body||body.querySelector('.agent-access-box'))return;
    try{
      const state=await json('/plugins/state',{cache:'no-store'}),agents=Array.isArray(state.agents)?state.agents:[];if(!agents.length)return;const byId=Object.fromEntries(agents.map(a=>[a.id,a]));
      const box=document.createElement('div');box.className='agent-access-box';body.prepend(box);
      box.innerHTML=`<div class="agent-access-head"><strong>Tool access</strong><select class="agent-access-select">${agents.map(a=>`<option value="${esc(a.id)}">${esc(a.name)} · ${esc(a.role||a.base)}</option>`).join('')}</select></div><div class="agent-access-help">Allowing a skill or MCP globally makes it available to every agent by default, including future agents. Use <b>Block</b> on an individual agent when it should not have that capability.</div><div class="agent-access-content"><div class="plugin-empty">Loading permissions…</div></div>`;
      const select=box.querySelector('.agent-access-select'),content=box.querySelector('.agent-access-content');
      async function setGlobal(kind,id,allowed){const agent=byId[select.value];const cmd=`${allowed?'Always allow':'Revoke'} ${kind} ${id} ${allowed?'for':'from'} all agents`;await runForAgent(agent,cmd);await loadAgent()}
      async function loadAgent(){
        content.innerHTML='<div class="plugin-empty">Loading permissions…</div>';const data=await json(`/plugins/agent-access/${encodeURIComponent(select.value)}`,{cache:'no-store'});const skills=Array.isArray(data.skills)?data.skills:[],servers=Array.isArray(data.mcp_servers)?data.mcp_servers:[];
        const skillRows=skills.map(s=>{const rt=s.runtime;const runtime=rt?`<div class="skill-runtime-badge ${rt.ready?'ready':'not-ready'}">${rt.ready?'Runtime ready':rt.installed?'Installed · needs Python 3.12+':'Not installed'}</div>`:'';return `<div class="agent-access-row"><div class="agent-access-copy"><div class="agent-access-name">${esc(s.name)}</div><div class="agent-access-meta">${esc((s.capabilities||[]).slice(0,4).join(' · '))}${s.inherited?' · role default':''}</div>${runtime}</div><button class="global-access-btn ${s.global_allowed?'on':''}" type="button" data-global-skill="${esc(s.id)}" data-global="${s.global_allowed?'1':'0'}">${s.global_allowed?'All agents':'Allow all'}</button><select class="agent-access-mode" data-skill="${esc(s.id)}"><option value="inherit" ${s.mode==='inherit'?'selected':''}>Inherit</option><option value="allow" ${s.mode==='allow'?'selected':''}>Allow</option><option value="block" ${s.mode==='block'?'selected':''}>Block</option></select></div>`}).join('');
        const mcpRows=servers.length?servers.map(s=>`<div class="agent-access-row"><div class="agent-access-copy"><div class="agent-access-name">${esc(s.name)}</div><div class="agent-access-meta">${esc(s.transport||'MCP')} · real connected server${s.mode==='inherit'?' · inherited':''}</div></div><button class="global-access-btn ${s.global_allowed?'on':''}" type="button" data-global-mcp="${esc(s.name)}" data-global="${s.global_allowed?'1':'0'}">${s.global_allowed?'All agents':'Allow all'}</button><select class="agent-access-mode" data-mcp-access="${esc(s.name)}"><option value="allow" ${s.mode!=='block'?'selected':''}>Allowed</option><option value="block" ${s.mode==='block'?'selected':''}>Block</option></select></div>`).join(''):'<div class="plugin-empty">Install/connect an MCP before granting it to agents.</div>';
        content.innerHTML=`<div class="agent-access-sub">Skills</div>${skillRows}<div class="agent-access-sub">Connected MCPs</div>${mcpRows}`;
        content.querySelectorAll('[data-skill]').forEach(el=>el.onchange=async()=>{el.disabled=true;try{await json(`/plugins/agent-access/${encodeURIComponent(select.value)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'skill',capability_id:el.dataset.skill,mode:el.value})})}finally{el.disabled=false}});
        content.querySelectorAll('[data-mcp-access]').forEach(el=>el.onchange=async()=>{el.disabled=true;try{await json(`/plugins/agent-access/${encodeURIComponent(select.value)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:'mcp',capability_id:el.dataset.mcpAccess,allowed:el.value==='allow'})})}finally{el.disabled=false}});
        content.querySelectorAll('[data-global-skill]').forEach(btn=>btn.onclick=async()=>{btn.disabled=true;try{await setGlobal('skill',btn.dataset.globalSkill,btn.dataset.global!=='1')}finally{btn.disabled=false}});
        content.querySelectorAll('[data-global-mcp]').forEach(btn=>btn.onclick=async()=>{btn.disabled=true;try{await setGlobal('MCP',btn.dataset.globalMcp,btn.dataset.global!=='1')}finally{btn.disabled=false}})
      }
      select.onchange=loadAgent;await loadAgent();
    }catch(_){ }
  }
  const panel=document.getElementById('agentiePluginsPanel');if(panel){new MutationObserver(()=>{if(panel.classList.contains('open'))setTimeout(renderAccess,0)}).observe(panel,{subtree:true,childList:true,attributes:true,attributeFilter:['class']})}
  document.getElementById('agentiePluginsButton')?.addEventListener('click',()=>setTimeout(renderAccess,120));
  const previous=window.renderCard;if(typeof previous==='function')window.renderCard=function(card,message){
    if(!card||card.type!=='agent_capability_approval')return previous(card,message);
    const wrap=document.createElement('div');wrap.className='card-wrap';const el=document.createElement('div');el.className='result-card';wrap.appendChild(el);const title=document.createElement('div');title.className='card-title';title.textContent=`Permission for ${card.agent_name||'agent'}`;el.appendChild(title);const detail=document.createElement('div');detail.className='mcp-approval-detail';detail.textContent=`Use ${card.capability_kind||'capability'}: ${card.capability_id||''}`;el.appendChild(detail);const actions=document.createElement('div');actions.className='agent-capability-actions';const once=document.createElement('button'),all=document.createElement('button'),deny=document.createElement('button');once.className='allow-once';once.textContent='Allow once';all.className='allow-all';all.textContent='Always allow for all agents';deny.textContent='Deny';actions.append(once,all,deny);el.appendChild(actions);
    async function resolve(mode){once.disabled=all.disabled=deny.disabled=true;try{await json(`/approvals/${card.approval.id}/resolve`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({approved:mode!=='deny'})});if(mode==='all'){const agent=(window.__agentieAgents||[]).find(a=>a.id===card.agent_id);await runForAgent(agent,`Always allow ${card.capability_kind==='mcp'?'MCP':'skill'} ${card.capability_id} for all agents`)}title.textContent=mode==='all'?'✓ Allowed for all agents':mode==='once'?'✓ Allowed once':'Permission denied';actions.remove();if(mode!=='deny'&&card.command)setTimeout(()=>resend(card.command),100)}catch(e){once.disabled=all.disabled=deny.disabled=false;detail.textContent=e.message||'Could not update permission.'}}
    once.onclick=()=>resolve('once');all.onclick=()=>resolve('all');deny.onclick=()=>resolve('deny');return wrap
  };
})();
