(()=>{
  if(window.__agentiePluginSetupWired)return;window.__agentiePluginSetupWired=true;
  const style=document.createElement('style');style.textContent=`
    .mcp-setup-card{display:grid;gap:10px}.mcp-setup-status{font-size:11px;color:var(--muted)}.mcp-setup-connected{color:#22c55e;font-weight:650}.mcp-setup-error{padding:9px;border-radius:9px;background:color-mix(in srgb,#ef4444 10%,var(--soft));color:#ef4444;font-size:11px;line-height:1.4;word-break:break-word}.mcp-setup-field{display:grid;gap:5px}.mcp-setup-field label{font-size:11px;font-weight:650}.mcp-setup-field input{box-sizing:border-box;width:100%;border:1px solid var(--border);border-radius:9px;background:var(--soft);color:var(--text);padding:9px 10px;outline:0}.mcp-setup-field input:focus{border-color:#0b84ff;box-shadow:0 0 0 2px color-mix(in srgb,#0b84ff 18%,transparent)}.mcp-setup-help{font-size:10px;color:var(--muted);line-height:1.4}.mcp-required{font-size:9px;color:var(--muted);font-weight:500}.mcp-setup-actions{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.mcp-setup-actions button,.mcp-setup-actions a{border:1px solid var(--border);border-radius:9px;padding:7px 10px;background:var(--panel);color:var(--text);font-size:11px;text-decoration:none;cursor:pointer}.mcp-setup-actions .primary{background:#0b84ff;color:#fff;border-color:#0b84ff}.mcp-setup-actions .oauth{background:#0b84ff;color:#fff;border-color:#0b84ff;font-weight:650}.mcp-setup-actions .danger{color:#ef4444}.mcp-setup-note{font-size:10px;color:var(--muted);line-height:1.4}.mcp-configure{border:1px solid var(--border);background:var(--panel);color:var(--text);padding:5px 8px;border-radius:8px;font-size:11px;cursor:pointer;flex:none}.mcp-configure:hover{background:var(--soft)}.mcp-setup-modal{position:fixed;inset:0;z-index:10050;background:rgba(0,0,0,.44);display:grid;place-items:center;padding:18px}.mcp-setup-panel{width:min(520px,100%);max-height:86vh;overflow:auto;background:var(--panel);border:1px solid var(--border);border-radius:16px;padding:16px;box-shadow:0 20px 60px rgba(0,0,0,.28)}.mcp-setup-head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:12px}.mcp-setup-head strong{font-size:15px}.mcp-setup-close{border:0;background:transparent;color:var(--muted);font-size:20px;cursor:pointer}.mcp-configured-badge{font-size:9px;border:1px solid var(--border);border-radius:999px;padding:2px 6px;color:var(--muted);margin-left:5px}.mcp-oauth-note,.mcp-webhook{padding:9px 10px;border:1px solid var(--border);border-radius:10px;background:var(--soft);font-size:11px;line-height:1.45;color:var(--muted)}.mcp-webhook strong{display:block;color:var(--text);margin-bottom:5px}.mcp-webhook code{display:block;overflow-wrap:anywhere;color:var(--text);font-size:10px;margin:5px 0 7px}.mcp-webhook button{border:1px solid var(--border);border-radius:8px;background:var(--panel);color:var(--text);padding:5px 8px;font-size:10px;cursor:pointer}
    .mcp-confirm{position:fixed;inset:0;z-index:10100;background:rgba(0,0,0,.48);display:grid;place-items:center;padding:18px}.mcp-confirm-box{width:min(390px,100%);background:var(--panel);border:1px solid var(--border);border-radius:14px;padding:16px;box-shadow:0 18px 55px rgba(0,0,0,.28)}.mcp-confirm-title{font-size:14px;font-weight:700;margin-bottom:7px}.mcp-confirm-text{font-size:11px;color:var(--muted);line-height:1.5}.mcp-confirm-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:14px}.mcp-confirm-actions button{border:1px solid var(--border);border-radius:9px;padding:7px 11px;background:var(--panel);color:var(--text);cursor:pointer}.mcp-confirm-actions .danger{background:#ef4444;color:#fff;border-color:#ef4444}
  `;document.head.appendChild(style);

  const esc=v=>{const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML};
  function sendChat(text){const input=document.getElementById('messageInput'),send=document.getElementById('sendButton');if(!input||!send||!text)return;input.value=text;input.dispatchEvent(new Event('input',{bubbles:true}));send.click()}
  function setupLinks(setup){const links=[];if(setup.get_key_url)links.push(`<a href="${esc(setup.get_key_url)}" target="_blank" rel="noopener noreferrer">${setup.auth_mode?'OAuth credentials':'Get API key'}</a>`);if(setup.connect_url&&setup.connect_url!==setup.get_key_url)links.push(`<a href="${esc(setup.connect_url)}" target="_blank" rel="noopener noreferrer">Provider page</a>`);if(setup.docs_url)links.push(`<a href="${esc(setup.docs_url)}" target="_blank" rel="noopener noreferrer">Setup guide</a>`);return links.join('')}
  function formMarkup(setup){
    const fields=(setup.fields||[]).map(f=>`<div class="mcp-setup-field"><label>${esc(f.label||f.env)}${f.required===false?'':' <span class="mcp-required">required</span>'}${f.configured?' <span class="mcp-configured-badge">Saved</span>':''}</label><input type="${f.secret===false?'text':'password'}" autocomplete="off" data-setup-env="${esc(f.env||f.id)}" placeholder="${esc(f.configured?'Saved — enter a new value to replace it':(f.placeholder||''))}">${f.help?`<div class="mcp-setup-help">${esc(f.help)}</div>`:''}</div>`).join('');
    const custom=setup.custom_env_supported?`<details><summary style="font-size:11px;color:var(--muted);cursor:pointer">Custom environment credential</summary><div class="mcp-setup-field" style="margin-top:8px"><label>Environment variable</label><input type="text" autocomplete="off" data-custom-env-name placeholder="EXAMPLE_API_KEY"></div><div class="mcp-setup-field" style="margin-top:8px"><label>Secret / API key</label><input type="password" autocomplete="off" data-custom-env-value placeholder="Paste secret"></div></details>`:'';
    return `${fields}${custom}`;
  }
  function webhookMarkup(setup){if(!setup.webhook_path)return'';const url=`${location.origin}${setup.webhook_path}`;return `<div class="mcp-webhook"><strong>Webhook callback</strong><code data-webhook-url>${esc(url)}</code><button type="button" data-copy-webhook>Copy callback URL</button><div style="margin-top:6px">${esc(setup.webhook_help||'Configure this callback URL with the provider.')}</div></div>`}
  function collectValues(root){const values={};root.querySelectorAll('[data-setup-env]').forEach(input=>{if(input.value.trim())values[input.dataset.setupEnv]=input.value.trim()});const name=root.querySelector('[data-custom-env-name]')?.value.trim(),value=root.querySelector('[data-custom-env-value]')?.value.trim();if(name&&value)values[name]=value;return values}
  function setStatus(root,text,ok=false){const status=root.querySelector('[data-setup-status]');if(!status)return;status.textContent=text||'';status.classList.toggle('mcp-setup-connected',!!ok)}

  async function saveAndTest(server,root,retry){const button=root.querySelector('[data-save-setup]');if(button)button.disabled=true;setStatus(root,'Saving credentials…');try{const values=collectValues(root);if(!Object.keys(values).length)throw new Error('Enter an API key or credential first.');const r=await fetch(`/plugins/setup/${encodeURIComponent(server)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({values})});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Could not save credential.');if(data.oauth_required){const next={...(data.setup||{}),server,error:null};buildSetup(root,next,retry);setStatus(root,data.message||'Credentials saved. Connect your account to finish setup.');return}if(data.connected){const nextSetup={...(data.setup||{}),server,error:null,connected:true};buildSetup(root,nextSetup,retry);setStatus(root,'Connected successfully.',true);if(retry)setTimeout(()=>sendChat(retry),180)}else{const next={...(data.setup||{}),server,error:data.error||null};buildSetup(root,next,retry);setStatus(root,data.message||'Credential saved, but connection failed.')}setTimeout(augmentPluginRows,250)}catch(error){setStatus(root,error.message||'Setup failed.')}finally{if(button&&button.isConnected)button.disabled=false}}

  async function connectAccount(server,root){const button=root.querySelector('[data-connect-setup]');if(button)button.disabled=true;setStatus(root,'Opening provider approval page…');try{const r=await fetch(`/plugins/connect/${encodeURIComponent(server)}`,{method:'POST'});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Could not start account connection.');setStatus(root,data.message||'Approval page opened. Finish sign-in in your browser, then test the connection.')}catch(error){setStatus(root,error.message||'Could not start account connection.')}finally{if(button)button.disabled=false}}

  async function testConnection(server,root,retry){const button=root.querySelector('[data-test-setup]');if(button)button.disabled=true;setStatus(root,'Testing connection…');try{const r=await fetch(`/plugins/test/${encodeURIComponent(server)}`,{method:'POST'});const data=await r.json();if(!r.ok)throw new Error(data.detail||data.error||'Connection test failed.');if(data.connected){const next={...(data.setup||{}),server,error:null,connected:true};buildSetup(root,next,retry);setStatus(root,'Connected successfully.',true);if(retry)setTimeout(()=>sendChat(retry),180)}else{const next={...(data.setup||{}),server,error:data.error||null};buildSetup(root,next,retry);setStatus(root,data.message||'Connection test failed.')}}catch(error){setStatus(root,error.message||'Connection test failed.')}finally{if(button&&button.isConnected)button.disabled=false}}

  function confirmClearSetup(server){return new Promise(resolve=>{const overlay=document.createElement('div');overlay.className='mcp-confirm';overlay.innerHTML=`<div class="mcp-confirm-box" role="dialog" aria-modal="true" aria-label="Clear saved secret"><div class="mcp-confirm-title">Clear saved secret?</div><div class="mcp-confirm-text">This removes the locally saved credentials for <strong>${esc(server)}</strong>. The MCP may stop working until it is configured again.</div><div class="mcp-confirm-actions"><button type="button" data-cancel-clear>Cancel</button><button type="button" class="danger" data-confirm-clear>Clear secret</button></div></div>`;document.body.appendChild(overlay);const done=value=>{overlay.remove();resolve(value)};overlay.querySelector('[data-cancel-clear]').onclick=()=>done(false);overlay.querySelector('[data-confirm-clear]').onclick=()=>done(true);overlay.onclick=e=>{if(e.target===overlay)done(false)};document.addEventListener('keydown',function escape(e){if(e.key==='Escape'){document.removeEventListener('keydown',escape);done(false)}},{once:true})})}
  async function clearSetup(server,root,retry){if(!(await confirmClearSetup(server)))return;setStatus(root,'Clearing saved credentials…');try{const r=await fetch(`/plugins/setup/${encodeURIComponent(server)}`,{method:'DELETE'});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Could not clear credentials.');buildSetup(root,{...(data.setup||{}),server},retry);setStatus(root,'Saved credentials cleared.')}catch(error){setStatus(root,error.message||'Could not clear credentials.')}}

  function buildSetup(root,setup,retry){
    root.classList.add('mcp-setup-card');
    const initial=setup.connected?'Connected':setup.configured?'Credentials saved':setup.oauth_supported&&!setup.requires_credentials?'Account not connected':'Not configured';
    const oauthNote=setup.oauth_supported?`<div class="mcp-oauth-note">Account access uses the provider’s OAuth approval page. Agentie does not ask you to paste your account password.</div>`:'';
    const saveButton=((setup.fields||[]).length||setup.custom_env_supported)?'<button class="primary" type="button" data-save-setup>Save credentials</button>':'';
    const connectButton=setup.oauth_supported?`<button class="oauth" type="button" data-connect-setup>${esc(setup.connect_label||'Connect account')}</button>`:'';
    const testButton='<button type="button" data-test-setup>Test connection</button>';
    const clearButton=setup.has_saved_credentials?'<button class="danger" type="button" data-clear-setup>Clear saved secret</button>':'';
    root.innerHTML=`<div class="mcp-setup-status${setup.connected?' mcp-setup-connected':''}">${initial}</div>${setup.description?`<div class="card-meta">${esc(setup.description)}</div>`:''}${setup.error?`<div class="mcp-setup-error">${esc(setup.error)}</div>`:''}${oauthNote}${formMarkup(setup)}${webhookMarkup(setup)}<div class="mcp-setup-actions">${saveButton}${connectButton}${testButton}${setupLinks(setup)}${clearButton}</div><div class="mcp-setup-note">Secrets stay in Agentie's local workspace and are never displayed back in chat. Each MCP receives only its own saved environment credentials.</div><div class="mcp-setup-status" data-setup-status></div>`;
    root.querySelector('[data-save-setup]')?.addEventListener('click',()=>saveAndTest(setup.server,root,retry));root.querySelector('[data-connect-setup]')?.addEventListener('click',()=>connectAccount(setup.server,root));root.querySelector('[data-test-setup]')?.addEventListener('click',()=>testConnection(setup.server,root,retry));root.querySelector('[data-clear-setup]')?.addEventListener('click',()=>clearSetup(setup.server,root,retry));root.querySelector('[data-copy-webhook]')?.addEventListener('click',async()=>{const value=root.querySelector('[data-webhook-url]')?.textContent||'';try{await navigator.clipboard.writeText(value);setStatus(root,'Webhook callback copied.')}catch{setStatus(root,'Could not copy automatically. Select the callback URL above.') }})
  }
  function renderSetupCard(card,message){const wrap=document.createElement('div');wrap.className='card-wrap';const el=document.createElement('div');el.className='result-card';wrap.appendChild(el);const title=document.createElement('div');title.className='card-title';title.textContent='🔌 '+String(card.title||`${card.server} setup`);el.appendChild(title);if(message){const meta=document.createElement('div');meta.className='card-meta';meta.textContent=message;el.appendChild(meta)}const form=document.createElement('div');form.style.marginTop='10px';el.appendChild(form);buildSetup(form,card,card.retry_command||'');return wrap}

  const previousRender=window.renderCard;if(typeof previousRender==='function')window.renderCard=function(card,message){if(card&&card.type==='mcp_setup')return renderSetupCard(card,message);return previousRender(card,message)};

  async function openSetup(server){let modal=document.createElement('div');modal.className='mcp-setup-modal';modal.innerHTML=`<div class="mcp-setup-panel"><div class="mcp-setup-head"><strong>${esc(server)} setup</strong><button class="mcp-setup-close" type="button">×</button></div><div data-setup-body><div class="plugin-empty">Loading…</div></div></div>`;document.body.appendChild(modal);const close=()=>modal.remove();modal.querySelector('.mcp-setup-close').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};try{const r=await fetch(`/plugins/setup/${encodeURIComponent(server)}`,{cache:'no-store'});const setup=await r.json();if(!r.ok)throw new Error(setup.detail||'Could not load setup.');modal.querySelector('.mcp-setup-head strong').textContent=setup.title||`${server} setup`;buildSetup(modal.querySelector('[data-setup-body]'),setup,'')}catch(error){modal.querySelector('[data-setup-body]').innerHTML=`<div class="plugin-empty">${esc(error.message)}</div>`}}
  function augmentPluginRows(){const panel=document.getElementById('agentiePluginsPanel');if(!panel)return;panel.querySelectorAll('.mcp-row').forEach(row=>{const inspect=row.querySelector('[data-mcp]');if(!inspect||row.querySelector('[data-setup-mcp]'))return;const server=inspect.dataset.mcp;if(!server)return;const configure=document.createElement('button');configure.type='button';configure.className='mcp-configure';configure.dataset.setupMcp=server;configure.textContent='Configure';configure.onclick=e=>{e.stopPropagation();openSetup(server)};row.appendChild(configure)})}
  const observer=new MutationObserver(()=>augmentPluginRows());observer.observe(document.body,{childList:true,subtree:true});augmentPluginRows();
})();
