(()=>{
  if(window.__agentiePluginSetupWired)return;window.__agentiePluginSetupWired=true;
  const style=document.createElement('style');style.textContent=`
    .mcp-setup-card{display:grid;gap:10px}.mcp-setup-status{font-size:11px;color:var(--muted)}.mcp-setup-error{padding:9px;border-radius:9px;background:color-mix(in srgb,#ef4444 10%,var(--soft));color:#ef4444;font-size:11px;line-height:1.4;word-break:break-word}.mcp-setup-field{display:grid;gap:5px}.mcp-setup-field label{font-size:11px;font-weight:650}.mcp-setup-field input{width:100%;border:1px solid var(--border);border-radius:9px;background:var(--soft);color:var(--text);padding:9px 10px;outline:0}.mcp-setup-field input:focus{border-color:#0b84ff;box-shadow:0 0 0 2px color-mix(in srgb,#0b84ff 18%,transparent)}.mcp-setup-actions{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.mcp-setup-actions button,.mcp-setup-actions a{border:1px solid var(--border);border-radius:9px;padding:7px 10px;background:var(--panel);color:var(--text);font-size:11px;text-decoration:none;cursor:pointer}.mcp-setup-actions .primary{background:#0b84ff;color:#fff;border-color:#0b84ff}.mcp-setup-actions .danger{color:#ef4444}.mcp-setup-note{font-size:10px;color:var(--muted);line-height:1.4}.mcp-configure{border:1px solid var(--border);background:var(--panel);color:var(--text);padding:5px 8px;border-radius:8px;font-size:11px;cursor:pointer;flex:none}.mcp-configure:hover{background:var(--soft)}.mcp-setup-modal{position:fixed;inset:0;z-index:10050;background:rgba(0,0,0,.44);display:grid;place-items:center;padding:18px}.mcp-setup-panel{width:min(520px,100%);max-height:86vh;overflow:auto;background:var(--panel);border:1px solid var(--border);border-radius:16px;padding:16px;box-shadow:0 20px 60px rgba(0,0,0,.28)}.mcp-setup-head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:12px}.mcp-setup-head strong{font-size:15px}.mcp-setup-close{border:0;background:transparent;color:var(--muted);font-size:20px;cursor:pointer}.mcp-configured-badge{font-size:9px;border:1px solid var(--border);border-radius:999px;padding:2px 6px;color:var(--muted);margin-left:5px}
  `;document.head.appendChild(style);

  const esc=v=>{const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML};
  function sendChat(text){const input=document.getElementById('messageInput'),send=document.getElementById('sendButton');if(!input||!send||!text)return;input.value=text;input.dispatchEvent(new Event('input',{bubbles:true}));send.click()}
  function setupLinks(setup){const links=[];if(setup.get_key_url)links.push(`<a href="${esc(setup.get_key_url)}" target="_blank" rel="noopener noreferrer">Get API key</a>`);if(setup.connect_url&&setup.connect_url!==setup.get_key_url)links.push(`<a href="${esc(setup.connect_url)}" target="_blank" rel="noopener noreferrer">Connect</a>`);if(setup.docs_url)links.push(`<a href="${esc(setup.docs_url)}" target="_blank" rel="noopener noreferrer">Setup guide</a>`);return links.join('')}
  function formMarkup(setup){
    const fields=(setup.fields||[]).map(f=>`<div class="mcp-setup-field"><label>${esc(f.label||f.env)}${f.configured?' <span class="mcp-configured-badge">Saved</span>':''}</label><input type="${f.secret===false?'text':'password'}" autocomplete="off" data-setup-env="${esc(f.env||f.id)}" placeholder="${esc(f.configured?'Saved — enter a new value to replace it':(f.placeholder||''))}"></div>`).join('');
    const custom=setup.custom_env_supported?`<details><summary style="font-size:11px;color:var(--muted);cursor:pointer">Custom environment credential</summary><div class="mcp-setup-field" style="margin-top:8px"><label>Environment variable</label><input type="text" autocomplete="off" data-custom-env-name placeholder="EXAMPLE_API_KEY"></div><div class="mcp-setup-field" style="margin-top:8px"><label>Secret / API key</label><input type="password" autocomplete="off" data-custom-env-value placeholder="Paste secret"></div></details>`:'';
    return `${fields}${custom}`;
  }
  function collectValues(root){const values={};root.querySelectorAll('[data-setup-env]').forEach(input=>{if(input.value.trim())values[input.dataset.setupEnv]=input.value.trim()});const name=root.querySelector('[data-custom-env-name]')?.value.trim(),value=root.querySelector('[data-custom-env-value]')?.value.trim();if(name&&value)values[name]=value;return values}
  async function saveAndTest(server,root,retry){const status=root.querySelector('[data-setup-status]'),button=root.querySelector('[data-save-setup]');if(button)button.disabled=true;if(status)status.textContent='Saving and testing connection…';try{const values=collectValues(root);if(!Object.keys(values).length)throw new Error('Enter an API key or credential first.');const r=await fetch(`/plugins/setup/${encodeURIComponent(server)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({values})});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Could not save credential.');if(status){status.textContent=data.connected?'Connected successfully.':(data.message||'Credential saved.');if(!data.connected)status.textContent+=(data.error?` ${data.error}`:'')}if(data.connected&&retry)setTimeout(()=>sendChat(retry),180);setTimeout(augmentPluginRows,250)}catch(error){if(status)status.textContent=error.message||'Setup failed.'}finally{if(button)button.disabled=false}}
  async function clearSetup(server,root){const status=root.querySelector('[data-setup-status]');if(status)status.textContent='Clearing saved credentials…';try{const r=await fetch(`/plugins/setup/${encodeURIComponent(server)}`,{method:'DELETE'});if(!r.ok)throw new Error('Could not clear credentials.');if(status)status.textContent='Saved credentials cleared.';root.querySelectorAll('input').forEach(i=>i.value='')}catch(error){if(status)status.textContent=error.message}}
  function buildSetup(root,setup,retry){root.classList.add('mcp-setup-card');root.innerHTML=`<div class="mcp-setup-status">${setup.configured?'Credential saved locally':'Not configured'}</div>${setup.description?`<div class="card-meta">${esc(setup.description)}</div>`:''}${setup.error?`<div class="mcp-setup-error">${esc(setup.error)}</div>`:''}${formMarkup(setup)}<div class="mcp-setup-actions"><button class="primary" type="button" data-save-setup>Save & test</button>${setupLinks(setup)}<button class="danger" type="button" data-clear-setup>Clear saved key</button></div><div class="mcp-setup-note">Secrets stay in Agentie's local workspace and are never displayed back in chat. Saving updates the running Agentie process immediately.</div><div class="mcp-setup-status" data-setup-status></div>`;root.querySelector('[data-save-setup]').onclick=()=>saveAndTest(setup.server,root,retry);root.querySelector('[data-clear-setup]').onclick=()=>clearSetup(setup.server,root)}
  function renderSetupCard(card,message){const wrap=document.createElement('div');wrap.className='card-wrap';const el=document.createElement('div');el.className='result-card';wrap.appendChild(el);const title=document.createElement('div');title.className='card-title';title.textContent='🔌 '+String(card.title||`${card.server} setup`);el.appendChild(title);if(message){const meta=document.createElement('div');meta.className='card-meta';meta.textContent=message;el.appendChild(meta)}const form=document.createElement('div');form.style.marginTop='10px';el.appendChild(form);buildSetup(form,card,card.retry_command||'');return wrap}

  const previousRender=window.renderCard;if(typeof previousRender==='function')window.renderCard=function(card,message){if(card&&card.type==='mcp_setup')return renderSetupCard(card,message);return previousRender(card,message)};

  async function openSetup(server){let modal=document.createElement('div');modal.className='mcp-setup-modal';modal.innerHTML=`<div class="mcp-setup-panel"><div class="mcp-setup-head"><strong>${esc(server)} setup</strong><button class="mcp-setup-close" type="button">×</button></div><div data-setup-body><div class="plugin-empty">Loading…</div></div></div>`;document.body.appendChild(modal);const close=()=>modal.remove();modal.querySelector('.mcp-setup-close').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};try{const r=await fetch(`/plugins/setup/${encodeURIComponent(server)}`,{cache:'no-store'});const setup=await r.json();if(!r.ok)throw new Error(setup.detail||'Could not load setup.');modal.querySelector('.mcp-setup-head strong').textContent=setup.title||`${server} setup`;buildSetup(modal.querySelector('[data-setup-body]'),setup,'')}catch(error){modal.querySelector('[data-setup-body]').innerHTML=`<div class="plugin-empty">${esc(error.message)}</div>`}}
  function augmentPluginRows(){const panel=document.getElementById('agentiePluginsPanel');if(!panel)return;panel.querySelectorAll('.mcp-row').forEach(row=>{const inspect=row.querySelector('[data-mcp]');if(!inspect||row.querySelector('[data-setup-mcp]'))return;const server=inspect.dataset.mcp;if(!server)return;const configure=document.createElement('button');configure.type='button';configure.className='mcp-configure';configure.dataset.setupMcp=server;configure.textContent='Configure';configure.onclick=e=>{e.stopPropagation();openSetup(server)};row.appendChild(configure)})}
  const observer=new MutationObserver(()=>augmentPluginRows());observer.observe(document.body,{childList:true,subtree:true});augmentPluginRows();
})();
