(()=>{
  if(window.__agentieTelegramPlugin)return;window.__agentieTelegramPlugin=true;
  const esc=v=>{const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML};
  const style=document.createElement('style');style.textContent=`.telegram-modal{position:fixed;inset:0;z-index:10060;background:rgba(0,0,0,.44);display:grid;place-items:center;padding:18px}.telegram-panel{width:min(520px,100%);background:var(--panel);color:var(--text);border:1px solid var(--border);border-radius:16px;padding:17px;box-shadow:0 20px 60px rgba(0,0,0,.28)}.telegram-head{display:flex;align-items:center;justify-content:space-between}.telegram-head strong{font-size:16px}.telegram-close{border:0;background:transparent;color:var(--muted);font-size:21px;cursor:pointer}.telegram-copy{font-size:11px;color:var(--muted);line-height:1.5;margin:8px 0 13px}.telegram-field{display:grid;gap:5px}.telegram-field label{font-size:11px;font-weight:650}.telegram-field input{box-sizing:border-box;width:100%;padding:9px 10px;border:1px solid var(--border);border-radius:9px;background:var(--soft);color:var(--text)}.telegram-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.telegram-actions button,.telegram-actions a{border:1px solid var(--border);border-radius:9px;padding:8px 11px;background:var(--panel);color:var(--text);font-size:11px;text-decoration:none;cursor:pointer}.telegram-actions .primary{background:#0b84ff;border-color:#0b84ff;color:#fff}.telegram-actions .danger{color:#ef4444}.telegram-status{margin-top:11px;padding:9px 10px;border-radius:10px;background:var(--soft);font-size:11px;line-height:1.5}.telegram-code{font-size:24px;font-weight:800;letter-spacing:.12em;margin:8px 0}.telegram-error{color:#ef4444}`;document.head.appendChild(style);
  async function call(url,options){const r=await fetch(url,options),d=await r.json();if(!r.ok)throw new Error(d.detail||d.message||'Telegram request failed.');return d}
  function render(root,state){const connected=state.connected,configured=state.configured;root.innerHTML=`<div class="telegram-head"><strong>Telegram channel</strong><button class="telegram-close" type="button">×</button></div><div class="telegram-copy">Connect your own bot from BotFather. Agentie encrypts the token locally and never displays it again. Only the private Telegram account paired with the one-time code can reach your agents.</div><div class="telegram-field"><label>Bot API token ${state.has_saved_token?'<span style="color:var(--muted)">· saved</span>':''}</label><input type="password" autocomplete="off" data-token placeholder="${state.has_saved_token?'Saved — enter only to replace':'123456789:AA…'}"></div><div class="telegram-actions"><button class="primary" data-save>Save & validate</button>${configured?'<button data-pair>Generate pairing code</button>':''}<a href="https://t.me/BotFather" target="_blank" rel="noopener noreferrer">Open BotFather</a>${configured?'<button class="danger" data-disconnect>Disconnect</button><button class="danger" data-revoke>Remove token</button>':''}</div>${state.pair_code?`<div class="telegram-status">Send this one-time code to <strong>@${esc(state.bot_username||'your bot')}</strong> in a private Telegram chat:<div class="telegram-code">${esc(state.pair_code)}</div>It expires in 10 minutes.</div>`:''}<div class="telegram-status${state.last_error?' telegram-error':''}" data-status>${state.last_error?esc(state.last_error):connected?`Connected to @${esc(state.bot_username)} as ${esc(state.paired_user||state.paired_chat_id)}.`:configured?`Bot @${esc(state.bot_username||'')} is validated. Generate a code to pair your Telegram account.`:'Not connected.'}</div>`;
    root.querySelector('.telegram-close').onclick=()=>root.closest('.telegram-modal').remove();
    root.querySelector('[data-save]').onclick=async()=>{const token=root.querySelector('[data-token]').value.trim();if(!token){root.querySelector('[data-status]').textContent='Paste a BotFather token first.';return}root.querySelector('[data-status]').textContent='Validating with Telegram…';try{render(root,await call('/plugins/telegram',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})}))}catch(e){root.querySelector('[data-status]').textContent=e.message}};
    root.querySelector('[data-pair]')?.addEventListener('click',async()=>{try{render(root,await call('/plugins/telegram/pair',{method:'POST'}))}catch(e){root.querySelector('[data-status]').textContent=e.message}});
    root.querySelector('[data-disconnect]')?.addEventListener('click',async()=>{if(confirm('Disconnect this Telegram account?'))render(root,await call('/plugins/telegram',{method:'DELETE'}))});
    root.querySelector('[data-revoke]')?.addEventListener('click',async()=>{if(confirm('Remove the saved bot token and disconnect Telegram?'))render(root,await call('/plugins/telegram?revoke_token=true',{method:'DELETE'}))});
  }
  window.openTelegramPlugin=async()=>{const modal=document.createElement('div');modal.className='telegram-modal';const panel=document.createElement('div');panel.className='telegram-panel';panel.innerHTML='<div class="plugin-empty">Loading…</div>';modal.appendChild(panel);document.body.appendChild(modal);modal.onclick=e=>{if(e.target===modal)modal.remove()};try{render(panel,await call('/plugins/telegram'))}catch(e){panel.innerHTML=`<div class="telegram-error">${esc(e.message)}</div>`}};
})();
