from __future__ import annotations

import csv
import io
import re
from pathlib import Path
from typing import Any

from docx import Document
from docx.enum.section import WD_SECTION
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor
from openpyxl import Workbook
from openpyxl.chart import BarChart, Reference
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from pptx import Presentation
from pptx.dml.color import RGBColor as PptRGBColor
from pptx.util import Inches as PptInches, Pt as PptPt

from agentie.core.artifact_naming import artifact_filename,creator_from_session
from agentie.core.document_design import choose_style, document_title, first_numeric_series, parse_blocks, numeric_series, chart_png_bytes
from agentie.core.file_service import UPLOADS, inspect_file, unique_path
from agentie.core.memory_store import latest_assistant_text
from agentie.core.result_memory import resolve_result_reference

_REFERENCE_RE = re.compile(r"\b(?:this|that|it|the previous answer|previous answer|last answer|above|what you just wrote|what you wrote)\b", re.I)
_DOCX_RE = re.compile(r"\b(?:create|make|generate|export|save|turn|convert)\b.*\b(?:docx|word document|word file)\b|\b(?:docx|word document|word file)\b.*\b(?:create|make|generate|export|save|turn|convert)\b", re.I)
_XLSX_RE = re.compile(r"\b(?:create|make|generate|export|save|turn|convert)\b.*\b(?:xlsx|excel|spreadsheet)\b|\b(?:xlsx|excel|spreadsheet)\b.*\b(?:create|make|generate|export|save|turn|convert)\b", re.I)
_PPTX_RE = re.compile(r"\b(?:create|make|generate|export|save|turn|convert)\b.*\b(?:pptx|powerpoint|presentation|slide deck|slides)\b|\b(?:pptx|powerpoint|presentation|slide deck|slides)\b.*\b(?:create|make|generate|export|save|turn|convert)\b", re.I)


def _safe_filename(name: str | None, suffix: str, prefix: str,creator:str="Agentie") -> str:return artifact_filename(creator,name,suffix,prefix)
def _extract_filename(message: str, suffix: str) -> str | None:
    m=re.search(rf"\b(?:called|named|as)\s+[\"']?([^\"']+?\{suffix})\b",message,re.I);return m.group(1).strip() if m else None
def _explicit_content(message: str) -> str | None:
    m=re.search(r"\b(?:with|using|from)\s+(?:the\s+)?(?:text|content|data)\s*[:\-]?\s*(.+)$",message,re.I|re.S)
    if not m:return None
    value=m.group(1).strip();return value.strip(" \"'") if value and not _REFERENCE_RE.fullmatch(value.strip(" .?!\"'")) else None
def _resolve_content(session_id:str,message:str)->str|None:
    content=_explicit_content(message)
    if content is None:content=resolve_result_reference(session_id,message)
    if content is None and (_REFERENCE_RE.search(message) or len(message.split())<=14):content=latest_assistant_text(session_id,max_chars=120000)
    return content

def _hex(value:str)->RGBColor:return RGBColor.from_string(value)
def _ppt_hex(value:str)->PptRGBColor:return PptRGBColor.from_string(value)
def _cell_shading(cell,color:str):
    tcPr=cell._tc.get_or_add_tcPr();shd=tcPr.find(qn('w:shd'))
    if shd is None:shd=OxmlElement('w:shd');tcPr.append(shd)
    shd.set(qn('w:fill'),color)
def _docx_style(doc:Document,style,creator:str="Agentie"):
    section=doc.sections[0];section.top_margin=Inches(.72);section.bottom_margin=Inches(.72);section.left_margin=Inches(.82);section.right_margin=Inches(.82)
    normal=doc.styles['Normal'];normal.font.name='Aptos';normal.font.size=Pt(style.body_size);normal.font.color.rgb=_hex(style.text);normal.paragraph_format.space_after=Pt(7);normal.paragraph_format.line_spacing=1.12
    for name,size,color in [('Title',style.title_size,style.accent),('Heading 1',18,style.accent),('Heading 2',14,style.text),('Heading 3',12,style.text)]:
        s=doc.styles[name];s.font.name='Aptos Display' if name!='Normal' else 'Aptos';s.font.size=Pt(size);s.font.bold=True;s.font.color.rgb=_hex(color);s.paragraph_format.space_before=Pt(12);s.paragraph_format.space_after=Pt(6)
    header=section.header.paragraphs[0];header.text='AGENTIE';header.alignment=WD_ALIGN_PARAGRAPH.RIGHT
    if header.runs:header.runs[0].font.size=Pt(8);header.runs[0].font.bold=True;header.runs[0].font.color.rgb=_hex(style.muted)
    footer=section.footer.paragraphs[0];footer.text=f'Generated by {creator} · Agentie';footer.alignment=WD_ALIGN_PARAGRAPH.CENTER
    if footer.runs:footer.runs[0].font.size=Pt(8);footer.runs[0].font.color.rgb=_hex(style.muted)
def _add_docx_title(doc,title,creator,style):
    p=doc.add_paragraph();p.alignment=WD_ALIGN_PARAGRAPH.LEFT;p.paragraph_format.space_after=Pt(4)
    r=p.add_run(title);r.bold=True;r.font.name='Aptos Display';r.font.size=Pt(style.title_size);r.font.color.rgb=_hex(style.accent)
    sub=doc.add_paragraph();sub.paragraph_format.space_after=Pt(15);r=sub.add_run(f"Prepared by {creator} · Agentie");r.font.size=Pt(9);r.font.color.rgb=_hex(style.muted)
    line=doc.add_paragraph();line.paragraph_format.space_after=Pt(10);run=line.add_run('━'*44);run.font.color.rgb=_hex(style.accent2);run.font.size=Pt(7)
def _add_docx_table(doc,rows,style):
    if not rows:return
    width=max(len(r) for r in rows);table=doc.add_table(rows=len(rows),cols=width);table.style='Table Grid'
    for r_idx,row in enumerate(rows):
        for c_idx in range(width):
            cell=table.cell(r_idx,c_idx);cell.text=str(row[c_idx]) if c_idx<len(row) else ''
            for p in cell.paragraphs:
                p.paragraph_format.space_after=Pt(2)
                for run in p.runs:run.font.name='Aptos';run.font.size=Pt(9);run.font.color.rgb=_hex('FFFFFF' if r_idx==0 else style.text);run.font.bold=r_idx==0
            if r_idx==0:_cell_shading(cell,style.accent)
            elif r_idx%2==0:_cell_shading(cell,style.soft)
    doc.add_paragraph()

def create_docx(content:str,filename:str|None=None,creator:str="Agentie",style_hint:str|None=None)->dict[str,Any]:
    if not content.strip():raise ValueError("Word document content is empty.")
    UPLOADS.mkdir(parents=True,exist_ok=True);path=unique_path(_safe_filename(filename,'.docx','document',creator));style=choose_style(content,style_hint);doc=Document();_docx_style(doc,style,creator);title=document_title(content,'Report');_add_docx_title(doc,title,creator,style)
    title_consumed=False
    for block in parse_blocks(content):
        if block['type']=='heading':
            if block['level']==1 and not title_consumed and block['text']==title:title_consumed=True;continue
            doc.add_heading(block['text'],level=min(3,max(1,block['level']-1)))
        elif block['type']=='paragraph':doc.add_paragraph(block['text'])
        elif block['type'] in {'bullets','numbered'}:
            st='List Bullet' if block['type']=='bullets' else 'List Number'
            for item in block['items']:doc.add_paragraph(item,style=st)
        elif block['type']=='table':_add_docx_table(doc,block['rows'],style)
    series=first_numeric_series(content)
    if series:
        labels,values,label=series;doc.add_heading('Visual summary',level=1);img=chart_png_bytes(labels,values,label,style);stream=io.BytesIO(img);doc.add_picture(stream,width=Inches(6.4));doc.paragraphs[-1].alignment=WD_ALIGN_PARAGRAPH.CENTER
    doc.core_properties.author = creator;doc.core_properties.title=title;doc.core_properties.subject=f"{style.label} document generated by Agentie";doc.save(path);card=inspect_file(path);card.update({'document_style':style.id,'creator':creator,'document_name':title});return card


def _markdown_table(content:str)->list[list[str]]|None:
    for block in parse_blocks(content):
        if block['type']=='table':return block['rows']
    return None
def _tabular_rows(content:str)->list[list[str]]:
    table=_markdown_table(content)
    if table:return table
    try:
        dialect=csv.Sniffer().sniff(content[:4096],delimiters=",\t;");rows=list(csv.reader(io.StringIO(content),dialect))
        if len(rows)>1 and max((len(r) for r in rows),default=0)>1:return rows[:5000]
    except Exception:pass
    lines=[x['text'] for x in parse_blocks(content) if x['type']=='paragraph'];return [['Content'],*[[x] for x in lines[:10000]]]

def create_xlsx(content:str,filename:str|None=None,creator:str="Agentie",style_hint:str|None=None)->dict[str,Any]:
    if not content.strip():raise ValueError("Spreadsheet content is empty.")
    UPLOADS.mkdir(parents=True,exist_ok=True);path=unique_path(_safe_filename(filename,'.xlsx','spreadsheet',creator));style=choose_style(content,style_hint);title=document_title(content,'Spreadsheet');rows=_tabular_rows(content);wb=Workbook();ws=wb.active;ws.title=(creator[:28]+' Data')[:31];ws.sheet_view.showGridLines=False
    thin=Side(style='thin',color='D8DDE3')
    for r_idx,row in enumerate(rows,1):
        for c_idx,value in enumerate(row,1):
            cell=ws.cell(r_idx,c_idx,value=value);cell.alignment=Alignment(vertical='top',wrap_text=True);cell.border=Border(bottom=thin)
            if r_idx==1:cell.font=Font(name='Aptos',bold=True,color='FFFFFF');cell.fill=PatternFill('solid',fgColor=style.accent);cell.alignment=Alignment(vertical='center')
            else:cell.font=Font(name='Aptos',size=10,color=style.text);cell.fill=PatternFill('solid',fgColor='FFFFFF' if r_idx%2 else style.soft)
    for col in range(1,max((len(r) for r in rows),default=1)+1):
        width=min(45,max(12,max((len(str(ws.cell(r,col).value or '')) for r in range(1,min(ws.max_row,250)+1)),default=12)+2));ws.column_dimensions[get_column_letter(col)].width=width
    ws.row_dimensions[1].height=25;ws.freeze_panes='A2' if ws.max_row>1 else None;ws.auto_filter.ref=ws.dimensions if ws.max_row>1 else None
    series=numeric_series(rows)
    if series and len(rows)<=100:
        labels,values,label=series;chart=BarChart();chart.type='col';chart.style=10;chart.title=label;chart.y_axis.title=label;chart.x_axis.title=str(rows[0][0] or 'Category');data=Reference(ws,min_col=2,min_row=1,max_row=min(ws.max_row,len(values)+1));cats=Reference(ws,min_col=1,min_row=2,max_row=min(ws.max_row,len(values)+1));chart.add_data(data,titles_from_data=True);chart.set_categories(cats);chart.height=7;chart.width=13;ws.add_chart(chart,f"{get_column_letter(max(2,ws.max_column+2))}2")
    wb.properties.creator=creator;wb.properties.title=title;wb.save(path);card=inspect_file(path);card.update({'document_style':style.id,'creator':creator,'document_name':title});return card


def _sections(content:str)->list[tuple[str,list[str]]]:
    title=document_title(content,'Presentation');sections=[];current=None;bullets=[]
    for block in parse_blocks(content):
        if block['type']=='heading':
            if block['level']==1 and block['text']==title:continue
            if current or bullets:sections.append((current or 'Overview',bullets[:7]))
            current=block['text'];bullets=[]
        elif block['type']=='paragraph':bullets.append(block['text'])
        elif block['type'] in {'bullets','numbered'}:bullets.extend(block['items'])
    if current or bullets:sections.append((current or 'Overview',bullets[:7]))
    if not sections:sections=[('Overview',[title])]
    return [(title,[]),*sections[:16]]
def _style_slide(slide,style):
    bg=slide.background.fill;bg.solid();bg.fore_color.rgb=_ppt_hex('FFFFFF')
    for shape in slide.shapes:
        if not hasattr(shape,'text_frame'):continue
        for p in shape.text_frame.paragraphs:
            for r in p.runs:r.font.name='Aptos';r.font.color.rgb=_ppt_hex(style.text)
    if slide.shapes.title:
        for p in slide.shapes.title.text_frame.paragraphs:
            for r in p.runs:r.font.color.rgb=_ppt_hex(style.accent);r.font.bold=True

def create_pptx(content:str,filename:str|None=None,creator:str="Agentie",style_hint:str|None=None)->dict[str,Any]:
    if not content.strip():raise ValueError("Presentation content is empty.")
    UPLOADS.mkdir(parents=True,exist_ok=True);path=unique_path(_safe_filename(filename,'.pptx','presentation',creator));style=choose_style(content,style_hint);prs=Presentation();prs.slide_width=PptInches(13.333);prs.slide_height=PptInches(7.5);sections=_sections(content);title,_=sections[0];slide=prs.slides.add_slide(prs.slide_layouts[0]);slide.shapes.title.text=title;slide.placeholders[1].text=f"{creator} · Agentie";_style_slide(slide,style)
    for heading,bullets in sections[1:]:
        slide=prs.slides.add_slide(prs.slide_layouts[1]);slide.shapes.title.text=heading[:100];frame=slide.placeholders[1].text_frame;frame.clear()
        for idx,b in enumerate(bullets or ['No additional details provided.']):
            p=frame.paragraphs[0] if idx==0 else frame.add_paragraph();p.text=b[:420];p.level=0;p.font.size=PptPt(19)
        _style_slide(slide,style)
    prs.core_properties.author=creator;prs.core_properties.title=title;prs.save(path);card=inspect_file(path);card.update({'document_style':style.id,'creator':creator,'document_name':title});return card


def try_office_request(session_id:str,message:str)->dict[str,Any]|None:
    kind='docx' if _DOCX_RE.search(message) else 'xlsx' if _XLSX_RE.search(message) else 'pptx' if _PPTX_RE.search(message) else None
    if not kind:return None
    content=_resolve_content(session_id,message)
    if not content:return {'message':f"What should I put in the {kind.upper()} file? Paste the content or say “use the previous answer.”",'card':None,'needs_content':True}
    creator=creator_from_session(session_id);style_hint=message
    if kind=='docx':card=create_docx(content,_extract_filename(message,'.docx'),creator,style_hint)
    elif kind=='xlsx':card=create_xlsx(content,_extract_filename(message,'.xlsx'),creator,style_hint)
    else:card=create_pptx(content,_extract_filename(message,'.pptx'),creator,style_hint)
    return {'message':f"Created “{card.get('document_name') or card['name']}” as {card['name']} using the {card.get('document_style','professional')} document style.",'card':card,'needs_content':False}