import tempfile
import unittest
from pathlib import Path

from agentie.core import agent_registry
from agentie.core.artifact_naming import artifact_filename,creator_from_session


class CollaborationArtifactNamingRegressionTests(unittest.TestCase):
    def setUp(self):
        self.temp=tempfile.TemporaryDirectory();self.old_agents=agent_registry.AGENTS_FILE;agent_registry.AGENTS_FILE=Path(self.temp.name)/'agents.json';self.agent=agent_registry.create_agent('Alex','CTO','coding')['agent']
    def tearDown(self):
        agent_registry.AGENTS_FILE=self.old_agents;self.temp.cleanup()

    def test_creator_is_taken_from_persistent_agent_session(self):
        self.assertEqual(creator_from_session(f"{self.agent['session_prefix']}main"),'Alex')
        self.assertEqual(creator_from_session('ui:base'),'Agentie')

    def test_generated_and_explicit_names_are_compact_and_agent_owned(self):
        self.assertEqual(artifact_filename('Alex',None,'.pdf','report'),'Alex-Agentie-report.pdf')
        self.assertEqual(artifact_filename('Alex','launch plan.pdf','.pdf','report'),'Alex-launch-plan.pdf')
        self.assertLess(len(artifact_filename('A Very Long Agent Name That Should Stay Compact',None,'.docx','document')),80)

    def test_pdf_and_office_services_use_agent_creator(self):
        pdf=Path('agentie/core/pdf_service.py').read_text(encoding='utf-8');office=Path('agentie/core/office_artifacts.py').read_text(encoding='utf-8')
        self.assertIn('creator_from_session(session_id)',pdf);self.assertIn('author=creator',pdf)
        self.assertIn('creator_from_session(session_id)',office);self.assertIn('doc.core_properties.author = creator',office);self.assertIn('Generated by {creator} · Agentie',office)

    def test_collaboration_strip_uses_real_team_jobs_and_clickable_agents(self):
        ui=Path('frontend/plugin_access.js').read_text(encoding='utf-8')
        self.assertIn('collab-strip',ui);self.assertIn("message:'Show team jobs'",ui);self.assertIn("['queued','working']",ui);self.assertIn('rememberTeam(card)',ui);self.assertIn('row?.click()',ui);self.assertIn('b.title=a.name',ui)


if __name__=='__main__':unittest.main()
