import unittest
from pathlib import Path
from tempfile import TemporaryDirectory
from unittest.mock import patch

from agentie.core import file_service, skill_registry, visual_artifacts
from agentie.core.local_router import route_local_actions


class VisualsMotionRegressionTests(unittest.TestCase):
    def test_builtin_visuals_motion_skill_is_real_and_local(self):
        skill = skill_registry.DEFAULT_SKILLS.get("visuals-motion")
        self.assertIsNotNone(skill)
        self.assertTrue(skill["enabled"])
        self.assertIn("diagram", skill["capabilities"])
        self.assertIn("motion_graphics", skill["capabilities"])
        self.assertIn("files_write", skill["permissions"])

    def test_arrow_graph_parser_supports_branches_without_duplicate_nodes(self):
        nodes, edges = visual_artifacts._parse_graph("CEO -> Chief of Staff; Chief of Staff -> Sales; Chief of Staff -> Finance")
        self.assertEqual(nodes, ["CEO", "Chief of Staff", "Sales", "Finance"])
        self.assertEqual(edges, [("CEO", "Chief of Staff"), ("Chief of Staff", "Sales"), ("Chief of Staff", "Finance")])

    def test_static_svg_is_created_locally_as_downloadable_artifact(self):
        with TemporaryDirectory() as tmp, patch.object(file_service, "UPLOADS", Path(tmp)), patch.object(visual_artifacts, "UPLOADS", Path(tmp)):
            card = visual_artifacts.create_svg_diagram(
                "Sales Process",
                ["Lead", "Qualify", "Proposal", "Close"],
                [("Lead", "Qualify"), ("Qualify", "Proposal"), ("Proposal", "Close")],
                "sales.svg",
                "Ben",
            )
            path = Path(tmp, card["name"])
            self.assertTrue(path.exists())
            self.assertEqual(card["suffix"], ".svg")
            self.assertEqual(card["visual_kind"], "diagram")
            self.assertEqual(card["creator"], "Ben")
            source = path.read_text(encoding="utf-8")
            self.assertIn("marker-end=", source)
            self.assertIn("Sales Process", source)
            self.assertIn("Generated by Ben", source)

    def test_svg_escapes_user_labels_instead_of_injecting_markup(self):
        with TemporaryDirectory() as tmp, patch.object(file_service, "UPLOADS", Path(tmp)), patch.object(visual_artifacts, "UPLOADS", Path(tmp)):
            card = visual_artifacts.create_svg_diagram(
                "Safe Diagram",
                ["Start <script>alert(1)</script>", "Done & Ready"],
                [("Start <script>alert(1)</script>", "Done & Ready")],
                creator="Agentie",
            )
            source = Path(tmp, card["name"]).read_text(encoding="utf-8")
            self.assertNotIn("<script>alert(1)</script>", source)
            self.assertIn("&lt;script&gt;", source)
            self.assertIn("Done &amp; Ready", source)

    def test_motion_graphic_is_self_contained_animated_html_with_duration_and_replay(self):
        with TemporaryDirectory() as tmp, patch.object(file_service, "UPLOADS", Path(tmp)), patch.object(visual_artifacts, "UPLOADS", Path(tmp)):
            card = visual_artifacts.create_motion_graphic(
                "Laundry Workflow",
                ["Order", "Wash", "Dry", "Iron", "Ready"],
                [("Order", "Wash"), ("Wash", "Dry"), ("Dry", "Iron"), ("Iron", "Ready")],
                "laundry.html",
                "Mira",
                10,
            )
            path = Path(tmp, card["name"])
            source = path.read_text(encoding="utf-8")
            self.assertEqual(card["visual_kind"], "motion_graphic")
            self.assertTrue(card["animated"])
            self.assertEqual(card["duration_seconds"], 10)
            self.assertIn("@keyframes nodeIn", source)
            self.assertIn("@keyframes progress", source)
            self.assertIn("Replay", source)
            self.assertNotIn("https://", source)

    def test_natural_static_request_routes_through_existing_skill_router_without_provider(self):
        with TemporaryDirectory() as tmp, patch.object(file_service, "UPLOADS", Path(tmp)), patch.object(visual_artifacts, "UPLOADS", Path(tmp)):
            result = skill_registry.route_skill_command("Create a flowchart: Lead -> Qualify -> Proposal -> Close")
            self.assertIsNotNone(result)
            self.assertEqual(result["card"]["visual_kind"], "diagram")
            self.assertEqual(result["card"]["nodes"], 4)
            self.assertTrue(Path(tmp, result["card"]["name"]).exists())

    def test_main_local_router_reaches_visual_skill_without_provider(self):
        with TemporaryDirectory() as tmp, patch.object(file_service, "UPLOADS", Path(tmp)), patch.object(visual_artifacts, "UPLOADS", Path(tmp)):
            routed = route_local_actions("Create a flowchart: Idea -> Validate -> Build -> Launch")
            self.assertEqual(routed["unresolved"], [])
            self.assertEqual(len(routed["results"]), 1)
            self.assertEqual(routed["results"][0]["card"]["visual_kind"], "diagram")

    def test_natural_motion_request_honors_requested_seconds(self):
        with TemporaryDirectory() as tmp, patch.object(file_service, "UPLOADS", Path(tmp)), patch.object(visual_artifacts, "UPLOADS", Path(tmp)):
            result = skill_registry.route_skill_command("Create a 10 second animated motion graphic: Order -> Wash -> Dry -> Ready")
            self.assertEqual(result["card"]["visual_kind"], "motion_graphic")
            self.assertEqual(result["card"]["duration_seconds"], 10)

    def test_natural_request_can_name_the_svg_file(self):
        with TemporaryDirectory() as tmp, patch.object(file_service, "UPLOADS", Path(tmp)), patch.object(visual_artifacts, "UPLOADS", Path(tmp)):
            result = skill_registry.route_skill_command("Create a flowchart called sales.svg: Lead -> Close")
            self.assertEqual(result["card"]["name"], "Agentie-sales.svg")
            self.assertTrue(Path(tmp, "Agentie-sales.svg").exists())

    def test_request_without_enough_structure_asks_for_nodes_instead_of_faking_a_diagram(self):
        result = visual_artifacts.try_visual_request("", "Create a diagram for our laundry business")
        self.assertIsNotNone(result)
        self.assertIsNone(result["card"])
        self.assertTrue(result.get("needs_content"))
        self.assertIn("Lead -> Qualify", result["message"])

    def test_disabled_visual_skill_does_not_create_files(self):
        with patch.object(skill_registry, "skill_enabled", return_value=False):
            result = visual_artifacts.try_visual_request("", "Create a flowchart: A -> B -> C")
        self.assertIn("disabled", result["message"].lower())
        self.assertIsNone(result["card"])

    def test_explicit_filename_keeps_agentie_artifact_naming_contract(self):
        with TemporaryDirectory() as tmp, patch.object(file_service, "UPLOADS", Path(tmp)), patch.object(visual_artifacts, "UPLOADS", Path(tmp)):
            card = visual_artifacts.create_svg_diagram("System", ["A", "B"], [("A", "B")], "architecture.svg", "Alex")
            self.assertEqual(card["name"], "Alex-architecture.svg")


if __name__ == "__main__":
    unittest.main()
